### ISSUE TITLE
[Bug] Downloads are broken

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#100]
Sorry, it's me again :)

**RomM version**
docker:1.5

**Describe the bug**
Download of a roms always stops at 411kb

**To Reproduce**
1. Select a game (GBA in my case)
2. Click on Download button
3. The file is downloaded but the size is 411kb

**Expected behavior**
The file is downloaded in its full size.

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS (Linux Debian)
 - Browser Vivaldi, Chrome
 - Version latest on 29/03/2023

**Comment by zurdi15** [comment]
No need to say sorry, you are helping me a lot my friend. Just realized its true, tested the feature but didn't realize it stops at 411B.

**Comment by zurdi15** [comment]
Fixed downloads for RomM folder structure 1 in last release [v1.6.1](https://github.com/zurdi15/romm/releases/tag/v1.6.1)
