### ISSUE TITLE
[Feature] Show version number

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#101]
Can you please insert the version number somewhere?
Maybe nearby the dark/light theme toggle?

**Comment by zurdi15** [comment]
Hello! I am on holidays right now and I am going to be a little bit disconnected for a few days. After that I going back to work again so hard :)

But for sure I am adding it. Actually the place after the theme toggle is a good idea

**Comment by DebugDax** [comment]
Looks like this is coming in 1.6.1 as it's part of 29d4bd8d3a6e585668d838fddca837cf341973ed.

**Comment by zurdi15** [comment]
Added in last release [v1.6.1](https://github.com/zurdi15/romm/releases/tag/v1.6.1)
