### ISSUE TITLE
[Feature] Choose IGDB entry manually

### ISSUE THREAD

**Issue by paultroeger** [zurdi15/romm#103]
Some Games do not get recognized even when they have an entry in the IGDB Database. 
The 'Search IGDB' button returns no results and therefore i can not link an IGDB entry to my game.

It would be nice if you could manually pick the IGDB entry.
There could be an additional field in the 'Edit' Section of a game. 
(See mock image)
This field would contain just the IGDB ID.
After editing the IGDB ID and applying the new data/cover should be fetched and saved.

Alternatively the 'Search IGDB' button could be improved to allow more filters then just the file name.

I made a quick Mock of how the menu could look like:
![image](https://user-images.githubusercontent.com/41645798/229280246-c25df8db-67f0-40b6-aea1-d3b6596557ff.png)

Loving the project so far. Thanks for the hard work.

**Comment by crispybegs** [comment]
https://github.com/zurdi15/romm/issues/76

**Comment by zurdi15** [comment]
> #76

Closed due to duplicated ussue
