### ISSUE TITLE
[Feature] Figured out how to add RomM to iPhone homescreen with custom icon

### ISSUE THREAD

**Issue by crispybegs** [zurdi15/romm#105]
in case there are any other apple users out out there, i just worked out to make RomM act like an app.
Originally, I just added a safari link to 192.168.1.XXX:4044 but the icon it created from the site was a bit ugly and incoherent.

![IMG_4FEF6BB4ECDA-1](https://user-images.githubusercontent.com/129169122/229306019-b83799ae-9d6c-4e1f-b793-ce24c392f8d8.jpeg)

But if you 

1. open the shortcuts app
2. tap + in top right corner 
3. add action 
4. tap web option and in the search bar at the top type "URL"
5. select the option in the list below that with the safari icon named "open URLs
6. in the panel that appears again with a safari icon that says 'Open **URL**' tap the word URL and enter the url to your RomM instance
7. enter a name for the shortcut at the very top of the screen and press 'done' at the bottom
8. click the blue slider icon top right of the screen
9. choose 'add to home screen'
10. choose a new icon by clicking the lower option halfway down the screen
11. click 'add' and you're done

now you have a nice app-looking link to your game library

<img width="476" alt="Screenshot 2023-04-01 at 18 46 08" src="https://user-images.githubusercontent.com/129169122/229306496-ab58e723-55a2-4498-a97d-65d0ca9a1413.png">

**Comment by ceratic** [comment]
That's the manual way. 
As an alternative, could the browser do that automatically as soon there is a Web App Manifest defined within the app.
https://web.dev/learn/pwa/web-app-manifest/#adding-a-web-app-manifest-to-your-pwa
https://app-manifest.firebaseapp.com/

**Comment by crispybegs** [comment]
> That's the manual way. As an alternative, could the browser do that automatically as soon there is a Web App Manifest defined within the app. https://web.dev/learn/pwa/web-app-manifest/#adding-a-web-app-manifest-to-your-pwa https://app-manifest.firebaseapp.com/

yes a PWA would be nice, but it looks like @zurdi15 has his hands quite full enough with other stuff before getting to anything like that

**Comment by DebugDax** [comment]
I don't think you need to go PWA if you're just looking for it to feel like an app on iPhone.

You simply defined some icons and meta tags and it just works.

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

`
<head>
<link rel="apple-touch-icon" href="touch-icon-iphone.png">
<link rel="apple-touch-icon" sizes="152x152" href="touch-icon-ipad.png">
<link rel="apple-touch-icon" sizes="180x180" href="touch-icon-iphone-retina.png">
<link rel="apple-touch-icon" sizes="167x167" href="touch-icon-ipad-retina.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
</head>`

**Comment by ceratic** [comment]
Yes, that would be enough for an iPhone or iPad. But not everyone uses Apple mobile devices. An App Manifest instead would cover android and desktop / Chromebooks  shortcuts on top of iPhone.

**Comment by DebugDax** [comment]
> Yes, that would be enough for an iPhone or iPad. But not everyone uses Apple mobile devices. An App Manifest instead would cover android and desktop / Chromebooks shortcuts on top of iPhone.

This issue was opened with the feature request of iPhone Home Screen icon. Not making the app a full PWA across multiple platforms. If you want that functionality then open another feature request because it wouldn’t fit the scope of this issue.

**Comment by crispybegs** [comment]
to be fair, i didn't actually request this, i just left a small guide for anyone who wanted to do the next best thing, since i know zurdi has a lot on his plate already

**Comment by zurdi15** [comment]
Hi guys,
as I am not an apple user, I am not going to develop anything "just apple related" so I am closing this issue and opening a new one with a generic feature for this request [android + iphone]. I think the best approach is the PWA solution.

Thank you very much for your interes in RomM.
