### ISSUE TITLE
[Bug] Prune Empty Platform Headings

### ISSUE THREAD

**Issue by jshackles** [zurdi15/romm#106]
**RomM version**
1.6

**Describe the bug**
RomM doesn't automatically prune headings / directories which are empty.  Instead, it leaves it intact with a "0" next to it.  Clicking on the empty heading loads a page that says "Feels cold here :( ".  I encountered this because initially I created a directory for PlayStation called "ps1" instead of "ps".  When I renamed the directory from "ps1" to "ps" then scanned in RomM, it correctly created the PlayStation heading but also left the "ps1" heading as empty.

**To Reproduce**
1. Create a directory for roms (it can either follow the official directory guide, or not), put some files here
2. Scan that directory with RomM, it will be added to the application
3. Delete all of the files in that directory
4. Scan again with RomM, the heading will now be empty but still present

**Expected behavior**
If RomM encounters a directory or heading with no roms in it, or cannot find a directory it previously scanned, delete that heading in the application.  RomM already deletes the individual rom entries when they're deleted, so this should be extended to headings as well.  Currently, there is no way in the UI to remove these empty headings.

**Screenshots**
![Screenshot](https://imgur.com/fbNyTTW.png)

**Comment by zurdi15** [comment]
Hello! I can't reproduce your issue: Did you renamed the ps1 folder to ps or did you create a new ps folder and the ps1 still remains in the filesystem?

If a platform folder exists in the filesystem, even if there are no games inside, will appera in RomM

**Comment by jshackles** [comment]
Weird.  I renamed the ps1 folder to ps, and got the above.  The "ps1" folder was no longer in my filesystem.  

However, I just completely deleted my library, and started over from scratch - which obviously fixed the problem.
