### ISSUE TITLE
[Feature] Custom SQLite Database Location

### ISSUE THREAD

**Issue by DebugDax** [zurdi15/romm#115]
**Is your feature request related to a problem? Please describe.**
The SQLite database is getting created wherever the library directory is. This is modifying the folder structure of the library collection and inserting data onto users folders when it should be kept independent. This is also an issue if you want to mount the library as read-only or if the container is running without privilege to write to that location, then the app will fail to launch since it must write to the external location.

**Describe the solution you'd like**
Add a volume config:
`- "/home/user/data/romm/database:/romm/database"`
That the Docker container can respect and save into.

**Comment by zurdi15** [comment]
SQLite location now ca be binded in the last release [v1.6.1](https://github.com/zurdi15/romm/releases/tag/v1.6.1)
