### ISSUE TITLE
[Feature] Folder-system association

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#152]
In my case the PlayStation folder is called psx instead of ps.
I would like to have the option to tell romm that the folder "psx" should be treated like the folder "ps".

How?
There could be an option on a config file somewhere to "override" system names.
This should even being done by the web interface.
There could be a "System" field that get valued byr RomMM and that can be changed by the user on will.
This field could be a combo box under the "gear" (option) menu similarly to the "Platform [ Scan ]".

**Comment by fatflyingpigs** [comment]
Yep, I have a similar issue with gamecube being 'ngc' instead of 'gc'. I've gotten around it by using a folder of symlinks, but it's far from an ideal solution.

**Comment by therobbiedavis** [comment]
This is what I ended up doing:
![image](https://user-images.githubusercontent.com/7907265/232136984-5517d813-7fb7-42ca-b5bd-e5dbf87e5ded.png)

**Comment by XargonWan** [comment]
Another solution would be to symlink all the folders contained in the original roms library inside a new folder that will be used by romm, then rename the symlinks to match romm.

...But I decided that I will just wait for this feature to come, the only limit into having the unassociated system is the scraping.

**Comment by zurdi15** [comment]
Platform folders association added as part of the config in [v1.8](https://github.com/zurdi15/romm/releases/tag/v1.8)
