### ISSUE TITLE
[Feature] WonderSwan/Color implementation

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#153]
In the readme wonderswan and wonderswan color are not present, however in my case wonderswan had some roms scraped but not wonderswan color:

![image](https://user-images.githubusercontent.com/6771419/231378274-12a11b66-f091-4f7e-ad00-9f18de82d506.png)

**Comment by zurdi15** [comment]
Added in the last release [v1.6.4](https://github.com/zurdi15/romm/releases/tag/v1.6.4)
