### ISSUE TITLE
[Documentation] Expand config file information

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#154]
Where do I have to put this file?

![image](https://user-images.githubusercontent.com/6771419/231379262-55f63b07-c3ae-4811-8100-5132be4ddf5e.png)

**Comment by zurdi15** [comment]
In the [docker-compose](https://github.com/zurdi15/romm/blob/v1.6.3/docker/docker-compose.example.yml) example you can see that it needs to be binded to ``/romm/config.yml``, but indeed I need to add at least a link to the example or just put that info directly in the docs.
