### ISSUE TITLE
[Bug] Size too much specific + suggestion

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#176]
**RomM version**
1.7

This folder-as-a-game's size is too specific, I think it needs to be truncated.
GNOME file manager says the folder is 307,7MB

NOTE: maybe it would be good to show GB after the game size is 1024MB or more.

![image](https://user-images.githubusercontent.com/6771419/232093176-3be366dd-923e-4a78-b8b0-75d2fedc7667.png)

![image](https://user-images.githubusercontent.com/6771419/232094083-6638fb85-eb5b-4bc8-ba9a-b4c2e64256f5.png)

BTW, nice grahpics! :)

**Comment by zurdi15** [comment]
Yeah totally true, the game size info still needs some work.

Adding at least the conversion to GB in the next version

**Comment by zurdi15** [comment]
Fixed in [v1.7.1](https://github.com/zurdi15/romm/releases/tag/v1.7.1) :)
