### ISSUE TITLE
[Feature] Nested folders in multi-file games support

### ISSUE THREAD

**Issue by therobbiedavis** [zurdi15/romm#179]
**RomM version**
1.7

**Describe the bug**
The multi-file game logic introduced in v1.6.3 does not incorporate sub-folders or their files into the zip. This is necessary for PS3 Roms.

**To Reproduce**
1. Get a PS3 Rom
2. Add to RomM
3. Try to download
4. See that only first level is compressed

**Expected behavior**
All sub levels are included in the zip and size calculation.

**Screenshots**
PS3 Structure:
![image](https://user-images.githubusercontent.com/7907265/232137797-3105a94f-a231-442e-965e-65703f473d26.png)
![image](https://user-images.githubusercontent.com/7907265/232137859-4e1fd494-d39d-4ec0-b60a-f026845e0635.png)
![image](https://user-images.githubusercontent.com/7907265/232137913-36ea88b7-0229-4904-a010-8727e2fcfa9e.png)

RomM View and Zip Download:
![image](https://user-images.githubusercontent.com/7907265/232138201-aebc94f9-1ec3-4b89-90e0-159410a18505.png)

**Comment by therobbiedavis** [comment]
I'll also say it wiill certainly help with switch update and dlc management as well.
![image](https://user-images.githubusercontent.com/7907265/232139443-295ba00f-fe0f-4267-abd0-8c1ad5022d8c.png)

**Comment by zurdi15** [comment]
Hi! it needs more work to get all level files in multifile games, but it is not a bug, rigth now this is how RomM works, so I am changing it as a feature if you don't mind :)

**Comment by zurdi15** [comment]
Support for subfolders inside multi part games added in [v1.8](https://github.com/zurdi15/romm/releases/tag/v1.8)

**Comment by dannyglover** [comment]
> Support for subfolders inside multi part games added in [v1.8](https://github.com/zurdi15/romm/releases/tag/v1.8)

Has it? All my PS3 games in Romm still just download the first file in the games directory, not a zip of the entire thing. 
When I click download, only `PS3_DISC.SFB` gets downloaded. 

I have tried a force complete scan on my PS3 library, but it doesn't make a difference. 
My install of Romm is fully up to date.

Any ideas?
Thanks again for Romm!

**Comment by dannyglover** [comment]
> Support for subfolders inside multi part games added in [v1.8](https://github.com/zurdi15/romm/releases/tag/v1.8)

@zurdi15 
Has it? All my PS3 games in Romm still just download the first file in the games directory, not a zip of the entire thing. 
When I click download, only `PS3_DISC.SFB` gets downloaded. 

![Image](https://github.com/user-attachments/assets/b65511a1-7efe-48d6-816a-0bfa4bae987b)

I have tried a force complete scan on my PS3 library, but it doesn't make a difference. 
My install of Romm is fully up to date.

Any ideas?
Thanks again for Romm!

**Comment by gantoine** [comment]
Wait for 3.8 to release, we reworked the file system scanner to deep scan folders and detect dcl/hashes/etc.

**Comment by dannyglover** [comment]
> Wait for 3.8 to release, we reworked the file system scanner to deep scan folders and detect dcl/hashes/etc.

I just updated to the latest release and all the issues are resolved.
Thanks!
