### ISSUE TITLE
[Bug] Bug title

### ISSUE THREAD

**Issue by Fabaderheld** [zurdi15/romm#180]
**RomM version**
1.7.1

**Describe the bug**
In prior versions unknown roms had a gray background while mouse over, this is not the case anymore and makes it nearly impossible to read the name

**To Reproduce**
Mouse over over any unknown rom
(Tried to downgrade to test an older versions, but this caused issues and romm didn't start anymore)

**Expected behavior**
Show gray background as in prior versions

**Screenshots**
![image](https://user-images.githubusercontent.com/4440238/232183142-cff65664-2b53-4b56-9137-af88765613a4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.0.22621.0
 - Browser Chrome
 - Version 111.0.5563.147

**Additional context**
Sorry to bother you again :(

**Comment by zurdi15** [comment]
Hi! don't worry my friend. Are you using light theme or the dark theme?

**Comment by Fabaderheld** [comment]
The dark theme

on the light theme it's no issue
![image](https://user-images.githubusercontent.com/4440238/232195780-3540f49f-0af1-44df-8bf6-7573a8bcf65a.png)

**Comment by zurdi15** [comment]
Hmm interesting. I didn't change that, this is how it looks like in my testing:

light theme:
![imagen](https://user-images.githubusercontent.com/34356590/232195917-5cd0918b-742d-4049-abd5-9fcc51f44215.png)

dark theme:
![imagen](https://user-images.githubusercontent.com/34356590/232195937-4efc862a-eb86-4912-a2aa-9f207e580459.png)

Try cleaning browser cache and localStorage

**Comment by Fabaderheld** [comment]
Hmmm,

after switching back to dark it's working again...

might be some caching after the upgrade

**Comment by Fabaderheld** [comment]
Coffee is on me ;)

**Comment by zurdi15** [comment]
I just saw it! Thank you very much my dude, really. That keeps me so motivated.

I was very excited 😄
