### ISSUE TITLE
[Other] Size unit missing

### ISSUE THREAD

**Issue by Fabaderheld** [zurdi15/romm#182]
**RomM version**
1.7.1

**Describe the bug**
* Sometimes the size unit is missing
* Sometimes it reappears after a refresh
* Sometimes it disappears after scraping
* Always happens for a whole platform, it never has a mixed behavior on a platform
* Scraped or not does not matter, but might change when scraped

**Expected behavior**
Always show the size unit

**Screenshots**
![image](https://user-images.githubusercontent.com/4440238/232209651-04261f6b-a8d1-4f3d-9028-b4308c057e9e.png)
![image](https://user-images.githubusercontent.com/4440238/232209738-d47f3e0d-c708-4ae6-ba77-53805a13307e.png)

**Desktop (please complete the following information):**
 - OS: Windows  10.0.22621.0
 - Browser Chrome
 - Version 111.0.5563.147

 - OS: Windows  10.0.22621.0
 - Browser Edge
 - Version 112.0.1722.46

**Additional context**
I'll do some more testing to narrow it down

**Comment by zurdi15** [comment]
I am sorry, I can't reproduce your error. Did you scan with the ``full scan`` option activated?

**Comment by Fabaderheld** [comment]
Not while testing, I'll do that when I'm back at the keyboard.

**Comment by zurdi15** [comment]
Ohh okay, you need to ``full scan`` then. You can check in the [release](https://github.com/zurdi15/romm/releases/tag/v1.7.1) notes that in order to made the change you need to ``full scan``

**Comment by Fabaderheld** [comment]
Ok my bad, i avoid this since I added ~3000 Amiga roms the full scan took almost 2 hours :D

**Comment by zurdi15** [comment]
Oh sorry, I know. 

You need to do it because before 1.7.1 size was stored in MB in the database and if you don't force the scan of already scanned games it won't update the size and won't add the units (that is the reason why for some platforms the you don't have the units)

**Comment by zurdi15** [comment]
It is like if I add some more metadata to the games, you will need to force full scan in order to re-scan games for the additional metadata

**Comment by Fabaderheld** [comment]
Well this answers my question what a full scan does :P. I'll do it ASAP and report back

**Comment by zurdi15** [comment]
Oh yes, I think I don't explain it anywhere, my bad.

Full scan is indeed to re-scan, because by default RomM will only scan games that are not present in the database to optimize scan time

**Comment by Fabaderheld** [comment]
Full scan still running but it looks good. 

Issue closed!
