### ISSUE TITLE
[UI/UX] Mouseover text is unreadable

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#185]
When the cursor hovers a cover art in the roms details (not game details) the name is shown, however it's unreadable in many circumstances.

![image](https://user-images.githubusercontent.com/6771419/232479214-8675055f-303b-4cdd-885a-86a319ee3852.png)

**Comment by zurdi15** [comment]
I assume that you just updated to 1.7.1 version? Other users reported similar issues. It seems that something in the browser is cached after the change of the color palette I made. Did you tried to change to light theme and then to dark again?

**Comment by XargonWan** [comment]
Right, it fixed it, sorry.
