### ISSUE TITLE
[Feature] ROM filename/savename correction

### ISSUE THREAD

**Issue by IngwiePhoenix** [zurdi15/romm#186]
Hello there!

I found this through Reddit r/selfhosted! :)

**Is your feature request related to a problem? Please describe.**
I have been dumping and collecting ROMs for literally one and a half decades and some of the filenames - and thus associated saves - have become increasingly mixed-named. I try to adhere to a scheme manually, but it'd be helpful if this tool could help out! Since you are already fetching data from IGDB, this might be useful.

**Describe the solution you'd like**
The software should be able to offer the user to automatically fix filenames - and associated save names - based on a preconfigured scheme. For instance, the one I use is `$title [$region $lang][$version].$ext`. The user should be able to configure this in their config to fit it into their default scheme.

**Describe alternatives you've considered**
Offer a suggested filename.

**Additional context**
None I could think of.

**Comment by XargonWan** [comment]
Can I suggest `$title [$region][$lang][$version].$ext`?

**Comment by GAntoine** [comment]
> Since you are already fetching data from IGDB, this might be useful

From what I can tell, IGDB can't tell us the region of a specific ROM file, just a list of regions associated with the game. An integration with no-intro might prove more fruitful, since we can compare SHA hashes.

**Comment by zurdi15** [comment]
I close the issue since we already have a specific way to manage ``regions``/``languages`` and for now we are not going to allow different structures for it.
