### ISSUE TITLE
[Feature] Timeline Master System / Mega Drive (Genesis) / Saturn support?

### ISSUE THREAD

**Issue by Fabaderheld** [zurdi15/romm#194]
Any timeline when those Sega systems will be supported?

thanks

Faba

**Comment by zurdi15** [comment]
I am sorry, Mega Drive (Genesis) is already supported. The platform name must be ``genesis-slash-megadrive``, forgot to put it in the platforms support. 
Others are already in develop branch. Next release will support them.

**Comment by Fabaderheld** [comment]
Great! Thanks for all your work!

**Comment by zurdi15** [comment]
Master system and Saturn support added in [v1.8](https://github.com/zurdi15/romm/releases/tag/v1.8)
