### ISSUE TITLE
SQLite Support

### ISSUE THREAD

**Issue by cbattlegear** [zurdi15/romm#20]
Would love to run this without having to deploy a full mariadb container to run it. 

Wanted to just put in a quick request for SQLite support, will also look into the code and see if I can just PR it. 

Thanks!

**Comment by zurdi15** [comment]
Well, this is my first open source project and I didn't thought it was going to have such a good support, so it would be great to see that PR!

In any case, I will do it eventually, I know setting this up can work perfectly with a SQLite

**Comment by zurdi15** [comment]
Just testing this feature: https://github.com/zurdi15/romm/pull/21

If everything goes as expected, today you have the SQLite compatibility in the v1.2
