### ISSUE TITLE
[Feature] Search by name or ID

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#208]
I wish to be able to search not only for ID but even by name.

**Example:**
I have a game named `Ristar - The Shooting star.gg` however in IGDB is just `Ristar` and even if `Ristar` is contained in `Ristar - The Shooting star.gg` it's not found.
So it would be good to let the user input a different name instead of opening the IGDB website and search for the game, then copy and paste the ID.

**Describe alternatives you've considered**
Parse the game name and if nothing is found do a second search that contains one or more words giving additional possible results.

![image](https://user-images.githubusercontent.com/6771419/234783541-733f4000-cd07-4cd0-b88d-97fcefa666ca.png)

**Comment by zurdi15** [comment]
Now rom details can be manually edited in the [v1.8.1](https://github.com/zurdi15/romm/releases/tag/v1.8.1). Of course future new metadata will be editable.
