### ISSUE TITLE
[Other] Broken videos on README.MD

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#213]
Videos are broken on README.MD

![image](https://user-images.githubusercontent.com/6771419/235150273-91c116f6-594d-4318-8c30-19dda8c50be7.png)

**Comment by zurdi15** [comment]
True, didn't realized about it. Anyway I need to remake them with the new UI.

**Comment by zurdi15** [comment]
Fixed and updated with screenshots instead of videos
