### ISSUE TITLE
[Feature] Improved error handling of a bad folder structure

### ISSUE THREAD

**Issue by calebsmithdev** [zurdi15/romm#217]
**Is your feature request related to a problem? Please describe.**
This is related to the initial project scan and immediate failing when the folder structure is setup incorrectly. In my case, I had the folder mounted but did not have a `roms` folder inside each platform.

**Describe the solution you'd like**
Instead of showing an empty error message (API resulted in a 500), show another type of error message to confirm a 500, or catch the error to show a more relevant message.

**Additional context**
I do not have the original log now with the failed messaging, but it was related to the function get_roms when trying to retrieve the roms for the first platform.

**Comment by zurdi15** [comment]
Improved in the new release [v1.8.3](https://github.com/zurdi15/romm/releases/tag/v1.8.3).
