### ISSUE TITLE
Dreamcast support

### ISSUE THREAD

**Issue by crispybegs** [zurdi15/romm#22]
please may we have dreamcast in the supported systems so we get a pretty icon in the system list?

**Comment by ceratic** [comment]
Dreamcast is already added in the develop branch. Shouldn't be long before it's in the master

**Comment by zurdi15** [comment]
Dreamcast support added in the fresh new [v1.2](https://github.com/zurdi15/romm/releases/tag/v1.2) release. Check release notes to see how to proper set the Dreamcast icon!
