### ISSUE TITLE
[Bug] Scan triggering duplicate entries

### ISSUE THREAD

**Issue by therobbiedavis** [zurdi15/romm#221]
**RomM version**
1.8.1

**Describe the bug**
Scan seems to triggering two scans, causing duplicate entries

**To Reproduce**
1. Go to Library > Scan
2. Add a platform
3. Click Scan

**Expected behavior**
A scan should not trigger two scans or duplicates

**Screenshots**
![image](https://user-images.githubusercontent.com/7907265/235703251-6e1f23a6-344d-49b9-9811-0f4f988e470d.png)
![image](https://user-images.githubusercontent.com/7907265/235703383-656ba3a4-9e68-4188-9927-e6a699ce9dac.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 112.0.5615.138

**Comment by therobbiedavis** [comment]
It doesn't seem to duplicate when running `Complete rescan`. I will get back to you in a few hours to let you know if it de-dupes.

**Comment by therobbiedavis** [comment]
Sorry for the delay. A `Complete rescan` does **not** de-dupe.

**Comment by zurdi15** [comment]
Bad news then, I don't know why this happened. Did you manage to de-dupe somehow?

**Comment by therobbiedavis** [comment]
> Bad news then, I don't know why this happened. Did you manage to de-dupe somehow?

Manually deleting the duped entries.

**Comment by zurdi15** [comment]
Bug solved in the new release [v1.8.3](https://github.com/zurdi15/romm/releases/tag/v1.8.3). Sorry for the inconvenience.

**Comment by Typhonragewind** [comment]
> Bug solved in the new release [v1.8.3](https://github.com/zurdi15/romm/releases/tag/v1.8.3). Sorry for the inconvenience.

Does it also dedupe, or do we have to do it manually?

**Comment by zurdi15** [comment]
Sorry, it doesn't dedupe, just fixed the double scan bug. In any case, I will implement bulk options to delete or rename (as you suggested [here](https://github.com/zurdi15/romm/issues/251)
