### ISSUE TITLE
[Bug] Data too long for column 'r_slug'

### ISSUE THREAD

**Issue by deftdev** [zurdi15/romm#229]
**RomM version**
v1.8.1

**Describe the bug**
When adding Zelda:BOTW on switch, i get the following error: Data too long for column 'r_slug'

The slug it is trying to enter is 'the-legend-of-zelda-breath-of-the-wild-and-the-legend-of-zelda-breath-of-the-wild-expansion-pass-bundle'

Full log attached:

[romm_log.txt](https://github.com/zurdi15/romm/files/11411030/romm_log.txt)

**Comment by zurdi15** [comment]
Fixed in [v1.8.2](https://github.com/zurdi15/romm/releases/tag/v1.8.2)

Now games with large names should be scanned without problems
