### ISSUE TITLE
[Feature] See 'all games' on homepage

### ISSUE THREAD

**Issue by crispybegs** [zurdi15/romm#23]
It would be nice to have an 'all games' option at the top of the system list, so you can see everything in your library at once

**Comment by zurdi15** [comment]
A dynamic load scrolling should be implemented for this, just as a note.

If anyone else have any other idea to not lose tons of performance is appreciated.

**Comment by AlexKalopsia** [comment]
I think that having alphabetic navigation could at least help with this. Some form of lazy loading (new results are loaded as you scroll), but also being able to jump to a specific letter seems like a possible good approach (at least almost all media servers handle it this way)

**Comment by GAntoine** [comment]
FWIW with paginated loading now a thing, "jumping" to a specific letter would be much harder to implement since most items in the list aren't rendered.

**Comment by gantoine** [comment]
Closing this as we're not planning to implement it (mainly for performance reasons, but also for UI).
