### ISSUE TITLE
[Other] Docker-compose not working

### ISSUE THREAD

**Issue by jbmfg** [zurdi15/romm#231]
Cant figure out what im doing wrong.  Tried with sqlite and mariadb.  No logs from romm are available so not sure what its problem is.  When docker-compose up -d is run, i get nothing except a message from docker saying "restarting".  Here is my docker-compose.yml:
` 
version: '3'
services:
  romm:
    image: 'zurdi15/romm:latest'
    container_name: romm
    environment:
      - ROMM_DB_DRIVER="mariadb" 
      - DB_HOST=romm_db
      - DB_PORT=3306 
      - DB_USER=romm-user
      - DB_NAME=romm
      - DB_PASSWD=REDACTED
      - CLIENT_ID=REDACTED
      - CLIENT_SECRET=REDACTED
    volumes:
      - '/media/Storage/roms:/romm/library'
      - '/media/Storage/docker/romm/resources:/romm/resources'
      - '/media/Storage/docker/romm/config.yml:/romm/config.yml'
      - '/media/Storage/docker/romm/database:/romm/database' 
    ports:
      - '8094:80'
    depends_on:
      - romm_db
    restart: "unless-stopped"

  romm_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: romm_db
    environment:
      - MYSQL_ROOT_PASSWORD=REDACTED
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=REDACTED
    volumes:
      - /media/Storage/docker/romm/sqlconfig:/config
    ports:
      - 3306:3306
    restart: "unless-stopped"
`

**Comment by kampma** [comment]
Try removing the quotes from around mariadb. 

- ROMM_DB_DRIVER="mariadb"

**Comment by kampma** [comment]
You’re the third person I’ve seen having this same issue. (Myself included.). Simple fix worked for me; don’t know if it’s system specific. Recommend the example docker compose YAML file should be adjusted to not include the quotes or to at least have a comment suggesting this fix for some users.

**Comment by zurdi15** [comment]
Hi! I don't know in which systems or with which tools this happens, but as @kampma  sugguested other users fixed it removing the quotes.

Try it and if it works the issue can be closed.

Also as @kampma  sugguested I removed the quotes in the example.

**Comment by DarkVirtue** [comment]
I was also having this issue (Debian 12, Docker 23.05, docker-compose 1.29.2) exactly as described by @jbmfg . Removing the quotes from around the `ROMM_DB_DRIVER` value (I'm using sqlite) fixed it for me, as @kampma suggested.
