### ISSUE TITLE
[Feature] Bulk edit/rescan option

### ISSUE THREAD

**Issue by crispybegs** [zurdi15/romm#24]
request to have a bulk edit option so you can, for example, delete or edit a bunch of games at once rather than clicking into each one individually. Audiobookshelf here as an example..

<img width="618" alt="Screenshot 2023-03-28 at 11 22 51" src="https://user-images.githubusercontent.com/129169122/228207231-a5ab14eb-01f8-4959-b2e7-b6dc8ca2fb6a.png">

**Comment by zurdi15** [comment]
For which kind of bulk edit you would use this apart from bulk download or delete?
