### ISSUE TITLE
[Feature] More systems support

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#245]
This issue is for asking the addittion of more systems:
- [x] gameandwatch
- [x] amstradcpc
- [x] gamegear
- [x] pc98
- [ ] pico-8
- [x] pokemini
- [ ] tic-80

Engine systems:
- [ ] easyrpg (rpgmaker)
- [ ] openbor
- [ ] solarus

Others:
- [x] doom (wads, mods, AmberELEC .doom files)
- [ ] ecwolf (same as above, .ecwolf)

**Comment by philipjholm** [comment]
@zurdi15 
Is there any reason why not PC (Microsoft Windows) is not supported (seems to be available on IGDB)? If not, could I please ask for that to be added?

**Comment by zurdi15** [comment]
PC is [supported](https://github.com/zurdi15/romm#-platforms-support) under the ``win`` slug!

**Comment by GAntoine** [comment]
Closing this as all the IGDB-supported games have been added.

**Comment by Mereks** [comment]
With the new metadata providers, any chance of ecwolf (Wolf3d, Blake Stone, etc?)

**Comment by gantoine** [comment]
@Mereks If it's not on the support platforms list in the docs there's no metadata for it.

**Comment by Mereks** [comment]
Thanks for the quick response! Though Doom (prboom) isnt listed on the supported page, it is supported though?

**Comment by Alleyway-Jack** [comment]
> Thanks for the quick response! Though Doom (prboom) isnt listed on the supported page, it is supported though?

Doom is supported. Idk about any metadata for it though.

**Comment by Skeeve** [comment]
Seems PICO-8 games are also on IGDB now. At least I could find POOM and PICOHOT.
