### ISSUE TITLE
[Feature] Initial homepage is a little bare?

### ISSUE THREAD

**Issue by crispybegs** [zurdi15/romm#246]
purely cosmetic comment, but the home page on first load has a lot of dead space. 
maybe it could be populated with.. the last 5 or 10 games uploaded or something, just to give it some visual oomph?

<img width="1423" alt="Screenshot 2023-05-10 at 21 21 12" src="https://github.com/zurdi15/romm/assets/129169122/e910b2f8-4ca6-4c19-a16d-815cecb905eb">

**Comment by zurdi15** [comment]
Yeah! I know. I am opened to suggestions about what to put in there.

I just wanted a home page because I knew in the future would be useful but still didn't think on what to put so... Feel free to think about it :)

**Comment by crispybegs** [comment]
actually, maybe a summary count of games per console? kind of like the sidebar, but a better overview?
and you can also click on one of the consoles and go through to the library?

<img width="1423" alt="Screenshot 2023-05-10 at 21 21 12" src="https://github.com/zurdi15/romm/assets/129169122/ff3b021f-7897-49c4-a553-93a92834101b">

**Comment by crispybegs** [comment]
yes, shit mock up, but you get what i mean

**Comment by binarygeek119** [comment]
how about how many uploads/downloads and how many saves files aswell

**Comment by GAntoine** [comment]
Take a peek at https://github.com/zurdi15/romm/pull/247

**Comment by zurdi15** [comment]
Added in the new release [v1.8.3](https://github.com/zurdi15/romm/releases/tag/v1.8.3).

**Comment by zurdi15** [comment]
> how about how many uploads/downloads and how many saves files aswell

I will add more like this stuff little by little
