### ISSUE TITLE
[Feature] PSP Iso games

### ISSUE THREAD

**Issue by r4lix** [zurdi15/romm#249]
Hi, i love your work, do you think in the future ROMM will be able to scan ISO for PSP Games ?

**Comment by zurdi15** [comment]
Hi! PSP is already supported by RomM :) 

Check the compatibility list, you just need to have a ``psp`` folder.

**Comment by r4lix** [comment]
> Hi! PSP is already supported by RomM :)
> 
> Check the compatibility list, you just need to have a `psp` folder.

oh ok, so maybe it's an issue with my config, i have a psp folder with a psp iso game but nothing on romm
