### ISSUE TITLE
[UI/UX] Make more clear what the 'delete' function is doing

### ISSUE THREAD

**Issue by crispybegs** [zurdi15/romm#25]
The delete funtion should make clear whether the game is being deleted only from the UI or from the filesystem entirely.
Again, audiobookshelf as an example

<img width="625" alt="Screenshot 2023-03-28 at 11 26 19" src="https://user-images.githubusercontent.com/129169122/228207937-411d1293-b95e-4680-ae0e-d3e38cd0c279.png">

**Comment by zurdi15** [comment]
Issue solved in release (v1.4)[https://github.com/zurdi15/romm/releases/tag/v1.4]
