### ISSUE TITLE
[Feature] Option to scan "this system"

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#250]
After the scanning options are moved into a separate menu on the bottom of the page is hard to reach if I just want to "scan this system".

Let's say that I am on GBA and I want to scan it, I should go down to reach the option page to choose GBA from the list and do a scan.

I would like to have a scan button somwhere comfy from the system page itself or a quick way to access the option menu from where I am.

**Comment by zurdi15** [comment]
Added in the new release [v1.8.3](https://github.com/zurdi15/romm/releases/tag/v1.8.3)
