### ISSUE TITLE
[Bug] Files no longer shown after complete rescan

### ISSUE THREAD

**Issue by therobbiedavis** [zurdi15/romm#262]
**RomM version**
1.8.3

**Describe the bug**
Scan does not seem to be picking up files anymore.
![image](https://github.com/zurdi15/romm/assets/7907265/2076c275-2167-43ab-84cd-76386d50e4dc)

**To Reproduce**
1. Run a complete rescan on a platform (that has games in subfolders)
2. Once complete, go to game info in RomM

**Expected behavior**
Files should be shown in files dropdown. Screenshot taken to prior to 1.8.3.
![before-1 8 3](https://github.com/zurdi15/romm/assets/7907265/7970227c-2d43-43fa-be88-fc9a238625a5)

**Screenshots**
Scan logs:
![image](https://github.com/zurdi15/romm/assets/7907265/e4deac61-dc8a-4be7-adc8-1c4c3230a059)

File structure:
![image](https://github.com/zurdi15/romm/assets/7907265/3ceb6ce9-c404-4815-af55-a86629f83cfd)

Docker Compose:
![image](https://github.com/zurdi15/romm/assets/7907265/eb915737-8873-4098-a67f-2761380979d9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 113.0.5672.93

**Comment by zurdi15** [comment]
Just released a new version with the fix :) [v1.8.4](https://github.com/zurdi15/romm/releases/tag/v1.8.4)
