### ISSUE TITLE
[Bug] Can't download large files

### ISSUE THREAD

**Issue by Raptime** [zurdi15/romm#266]
**RomM version**
1.8.4

**Describe the bug**
downloading big ROM (2GB+) doesn't work. small ROM (20MB) download fine

**To Reproduce**
1. Select Switch as a platform
2. Download a game
3. It says "Downloading xxx..."
4. Nothing happens

**Expected behavior**
ROM should start downloading, just like when you download a smaller ROM

**Additional context**
docker logs -f romm doesn't show any error

**Comment by GAntoine** [comment]
I'm able to download a 10GB+ file just fine, so my guess is the request is timing out when trying to prepare the file for download. Could you open the developer console, navigate to the Network tab, try to download the file and post the result/headers of the request?

<img width="605" alt="Screenshot 2023-05-23 at 11 03 52 AM" src="https://github.com/zurdi15/romm/assets/3247106/5e740fbf-c265-4914-992c-16023812593e">

**Comment by Raptime** [comment]
Looks like a timeout indeed. I'm using Romm in a docker container and I mount an NFS drive for the ROMs, could be why...
![image](https://github.com/zurdi15/romm/assets/4553932/5ab4792e-92fe-4573-be5d-7961a2674e4e)
![image](https://github.com/zurdi15/romm/assets/4553932/3892beef-9ab3-4d6e-86a6-8322bff86850)

**Comment by GAntoine** [comment]
So all the posts I can find about `NS_BASE_STREAM_CLOSED` speak of a caching issue in Firefox. I'm gonna try the same thing on my hosted instance with another 10GB file. In the meantime, can you let me know if there are any errors in the console?

**Comment by Raptime** [comment]
The following error in the console appears after the timeout (sorry, I should have included it in my earlier reply):
```
Uncaught (in promise) DOMException: The operation was aborted. download.65cfb14c.js:12:93650
    Ft http://docker.home.example.org:8123/assets/download.65cfb14c.js:12
    AsyncFunctionThrow self-hosted:814
    (Async: async)
    forEach self-hosted:203
    Ft http://docker.home.example.org:8123/assets/download.65cfb14c.js:12
    0 http://docker.home.example.org:8123/assets/Details.30da469b.js:1
    Sm http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    Qt http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    ct http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    ct http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    n http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    (Async: EventListener.handleEvent)
    Nn http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    pm http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    Cm http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    I http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    B http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    g http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    D http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    run http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    update http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    ee http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    K http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    U http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    g http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    w http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    I http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    B http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    g http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    D http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    run http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    update http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    ee http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    K http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    U http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    g http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    w http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    I http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    B http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    g http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    D http://docker.home.example.org:8123/assets/index.83f1f892.js:1
    run http://docker.home.example.org:8123/assets/index.83f1f892.js:1
```

**Comment by VermiumSifell** [comment]
Regarding "https://github.com/zurdi15/romm/blob/master/frontend/src/services/download.js" is it necessary to do this part?
```
        var file = await fetch(file_full_path)
        var fileBlob = await file.blob()
        saveAs(fileBlob, rom.file_name)
```

Can't be just send the file right away without making it a blob and use "saveAs" function? Can't we just in some way return the file? I'm not an expert at all on managing files in JavaScript. But I also think this part should be a part of backend and listen for progress from backend and then when file is ready (if multiple files, it may take some time, otherwise just send it right away). I have no idea if my idea is something that is better (or work) but just wanted to try help improving download part

**Comment by GAntoine** [comment]
@VermiumSifell You're not far off; we can easily handle downloading single-file roms, or ones where the parts are already zipped. The issue lies with multi-file ROMs, since they'd still require some form of on-the-fly compression.

**Comment by GAntoine** [comment]
Alright I've got something working for both single file and multi-file download https://github.com/GAntoine/romm/pull/1

It's based off my pagination PR, so that'll need to go in first before this can get merged.

cc @zurdi15

**Comment by VermiumSifell** [comment]
> @VermiumSifell You're not far off; we can easily handle downloading single-file roms, or ones where the parts are already zipped. The issue lies with multi-file ROMs, since they'd still require some form of on-the-fly compression.

Cool, btw cant we just send the files individually?

**Comment by GAntoine** [comment]
> cant we just send the files individually

We can but then we go back to the original issue, which is downloading using `fetch`, and will require the file to be built in memory before it's downloaded.

**Comment by VermiumSifell** [comment]
Can we change from using `fetch` to something else? I think some games are really huge and not all people can give their `romm` 16GB+ RAM

**Comment by GAntoine** [comment]
> There are some things I want to fix from the current PR

By all means feel free to modify it, or comment with suggestions of things we can improve (on either of them).

**Comment by VermiumSifell** [comment]
> If you can think of another way to _fetch_ multiple files without a direct-download link I'm all ears!

Altough, why not use a direct-link? Is it bad in some way? Since we do a "GET" request we can make sure it is not executed, and therefor get all files individually which _should_ improve performance of downloads, aswell as showing progress for user a lot better. Maybe we can implement a API endpoint with ratelimits to the files? And stream the file to the user instead?

**Comment by VermiumSifell** [comment]
> Btw, I'm currently trying to rewrite whole backend over to NodeJS, with async/await and TypeScript. I hope I can make a PR of it later, otherwise I likk just make it as a fork of romm :)

Most stuff rewritten now. screenshots and some minor fixes left!
![image](https://github.com/zurdi15/romm/assets/47034338/141c88a2-1b6f-468d-96bb-f0b46c67ff8d)

**Comment by zurdi15** [comment]
Wow dude you are fast. Sorry for the late response, I am sadly out of time right now to work too much on this, and didn't think too much about this NodeJS refactor of the backend. 

I am not an expert in NodeJS but I don't want RomM to be so fragmented this early in the development having two different backends or having a fork, so If @GAntoine agree with this (as he is the main contributor other than me) we can discuss to having the full backend replacement in the main fork.

What is the advantage of doing it in NodeJS against doing it with python fastapi?

**Comment by GAntoine** [comment]
So I've worked with both Python/Fast and Node, and I find both to be perfectly capable frameworks, especially at the scale of a project like this one. Type safety is useful even on the backend, but we don't need to switch to a Node to reap those benefits (python > 3.5 has built-in typing).

@zurdi15 Are you familiar/have you worked with with Node (or other JS-on-the-backend)?

@VermiumSifell What's your motivation for this change? And if we do decide to make the switch at some point, we should consider Node alternatives like [Deno](https://deno.land/) or [Bun](https://bun.sh/).

**Comment by VermiumSifell** [comment]
Mostly because I know of NodeJS a lot more, and find TypeScript amazing, I think of keeping this as a fork of romm, my motivation is to improve the download mechanism and I wanted to rewrite it to NodeJS too. So just something I prefer :P

**Comment by GAntoine** [comment]
Yeah that's totally understandable, we like to work with what we know. 😄  That being said, **unless we can come up with quantifiable benefits to migrating off FastAPI/Python**, IMO our time would be better spend improving the current codebase. Node and Python are about equal in performance, have a lot of developers who know the languages/frameworks, support async/concurrency, and support typing.

While your contributions to this project would be greatly appreciated, you're always welcome to fork and maintain a version written in Node. If you happen to have time on your hands, and your fork outpaces this project in terms of functionality over the next weeks/months, we should absolutely revisit the idea of migrating over.

Oh and please let me know when your rewrite is available, I'd love to take a look through the code!
