### ISSUE TITLE
[Bug] Unable to scan library

### ISSUE THREAD

**Issue by deanpribetic** [zurdi15/romm#270]
**RomM version**
v1.8.4

**Describe the bug**
Scans are not completing. I start a scan and it cycles forever. In the log the following is being repeated:

`INFO:     192.168.6.26:0 - "GET /socket.io/?EIO=4&transport=websocket HTTP/1.1" 400 Bad Request`

**To Reproduce**
1. Go to Library
2. Select Scan
3. Push the Scan button

**Expected behavior**
A scan is run and completes

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser safari and firefox
 - Version safari v16.4 and Firefox 113.0.2

**Comment by calebsmithdev** [comment]
Do you see an error or anything in your Docker logs outside of that?

**Comment by deanpribetic** [comment]
The only other message I'm seeing is

`Invalid websocket upgrade (further occurrences of this error will be logged with level INFO)`

**Comment by deanpribetic** [comment]
A small update. I reinstalled and am getting the same error.

**Comment by zurdi15** [comment]
I am sorry dude, I have no idea what is going on here. Do you jave RomM setup in the same computer are you triying to access from?

**Comment by deanpribetic** [comment]
Ah - I figured this out. Problem was on my end. I have Romm running behind Nginx Proxy Manager but I didn't have websockets support turned on. Sorry - that was my bad! I should have twigged with the error message!

**Comment by calebsmithdev** [comment]
I wondered if that might be the case. I run into that issue more often than I should 😅  - thanks for sharing the solution for you!
