### ISSUE TITLE
[Feature] Search Roms inside Romm

### ISSUE THREAD

**Issue by RandomLegend** [zurdi15/romm#272]
I would love to have a search function inside Romm so i can quickly find the roms i want.

Have a little search bar and/or have it automatically activated by typing. Filter either in real time or let it process to find something.

It could then be categorized by the consoles. If you search for just pokemon for example i would reduce the console tabs to only the pokemon games.

Thanks for considering! :-)

**Comment by RandomLegend** [comment]
I'm sorry - i didn't see there already was a search bar inside the consoles.

It would be awesome to have a search bar on the main page aswell.

**Comment by zurdi15** [comment]
I like the idea of filter the sidebar just with the consoles that have at least one filtered game. In any case the filter doesn't reset when changing the platform, so I don't think it is needed in the main page.
