### ISSUE TITLE
[Feature] Scheduled scans

### ISSUE THREAD

**Issue by philipjholm** [zurdi15/romm#274]
Add the possibility in settings to have automatic scheduling of game scans. Like for example to run each hour or something like that.

**Comment by GAntoine** [comment]
Cool idea! Right now scanning happens via websocket, so there are a couple options we can evaluate:

* Add HTTP API endpoint(s)
* Add custom python shell commands (and run via `cron`)
* Build scheduling fnct within RomM and manage in the settings

How do you see it working from your POV?

**Comment by philipjholm** [comment]
@GAntoine I would definitely vote on the last option to have it configurable in the settings. To be honest, I was kind of looking for it there the first time I went there.

**Comment by GAntoine** [comment]
With the addition of Redis/RQ in #321, one option for this is to use [rq-scheduler](https://github.com/rq/rq-scheduler), which supports cron-style syntax for running recurring jobs.

However since we're watching a file system, we could go even simpler and use [watchdog](https://python-watchdog.readthedocs.io/en/stable/), running targeted scans when new files are detected.

**Comment by GAntoine** [comment]
@AndrewBudziszek Scan-on-schedule is totally possible, but I struggle to see a use case where "scan on file system change detected" won't offer a better experience. Network bing mounts maybe?

**Comment by Casuallynoted** [comment]
When running my Plex server with network shares that store data, I noticed that it wouldn't detect file changes. In a case like that, scheduled scans were a godsend. Also, when setting up the server for the first time.

**Comment by GAntoine** [comment]
@Casuallynoted You'll be happy to hear we'll soon be supporting both! https://github.com/zurdi15/romm/pull/357

**Comment by zurdi15** [comment]
This was added in the release [2.1.0](https://github.com/zurdi15/romm/releases/tag/v2.1.0)
