### ISSUE TITLE
[Feature] Track upcoming games

### ISSUE THREAD

**Issue by philipjholm** [zurdi15/romm#275]
Maybe a bit out of scope for this project but I can really see the potential of this app and I think this would make a lot of sense and give a lot of value.

It would be awesome if it was possible to search for a game for a specific platform, find the one you want and then add them to a watchlist. When saved to a watchlist it gets the meta data such as release date. It could then be shown in a list sorted on release date. This would give you a overview of upcoming games you want to keep track on and maybe even throw in some kind of notification feature such as post to discord. 

This would require to also have some background updating of meta data so that release dates are up to date as they can change from time to time.

**Comment by GAntoine** [comment]
RomM is a manager and organizer for your game files focused (at the moment)  on retro games. While the scope will probably grow to include things like "wanted lists", there's no plan to start tracking future releases. There are great non-self-hosted options out there like https://www.completionator.com/ or https://gamestracking.com/
