### ISSUE TITLE
[UI/UX] Remove top banners

### ISSUE THREAD

**Issue by philipjholm** [zurdi15/romm#276]
I love the simple and clean look of this app but the banners at the top kind of annoys me as they just take a lot of space and serves no purpose. I bit of a silly request but I suggest removing them.

**Comment by GAntoine** [comment]
Can you post a screenshot of exactly which banner you're talking about?

**Comment by zurdi15** [comment]
I guess he is talking about the blurred background header in the game details page.

 I would say that maybe you feel now the details page is empty because there is still a lot of room for more useful stuff, but it will grow little by little.

**Comment by GAntoine** [comment]
If you're using Ublock Origin, here's a filter that should work: `##.mb-10.mt-10.mx-auto.v-card--variant-text.v-card--density-default.v-theme--rommDark.v-card`

**Comment by philipjholm** [comment]
> 

Yeah I know there are extensions for that but then it has to be done on each computer and to my knowledge not possible to do on android chrome. If I would be able to inject my own custom css server side in the app that would solve the problem though 🙂

**Comment by GAntoine** [comment]
> not possible to do on android chrome

yeah it's too bad chrome on android doesn't support extensions, one of the reasons i sometimes used firefox on android

> inject my own custom css server side

this is a cool idea, and one we'd probably want to support at some point, but it's fairly low priority. could you start a new issue for "custom css"?
