### ISSUE TITLE
[Other] Force detect a game during scan?

### ISSUE THREAD

**Issue by zodac** [zurdi15/romm#285]
Is there any way to force the mapping of a ROM file to an entry in IGDB during the library scan? For example, I have the ROM Pokémon Trading Card Game.gb, and I can see there is an entry in IGDB:
https://www.igdb.com/games/pokemon-trading-card-game

However, it still fails to get picked up:

INFO:     [RomM][2023-06-19 00:46:44] Identified as Game Boy
INFO:     [RomM][2023-06-19 00:46:44] Scanning Pokémon Trading Card Game.gb
WARNING:  [RomM][2023-06-19 00:46:46] Pokemon Trading Card Game not found in IGDB

I can use the UI to map them after the fact, but is there any way to add that metadata to the file? For example, I think Emby/Jellyfin supports adding `[tvdbid=1234]` to a directory name to link a folder to a specific entry - something for RomM would be very convenient too. :)

**Comment by GAntoine** [comment]
Neat idea! Not one that's supported at the moment sadly.

In your case, is the ROM under "Game Boy" or "Game Boy Color"? Pokemon TDG is only available for "Game Boy Color", but I see the platform identified as "Game Boy".

**Comment by zodac** [comment]
@GAntoine , thanks for that. Yeah, for my example it was just mis-categorised - here's another one though that should be in the correct category:

```
INFO:     [RomM][2023-06-19 22:08:30] Identified as Nintendo 3DS
INFO:     [RomM][2023-06-19 22:08:30] Scanning Pokémon Super Mystery Dungeon.cia
WARNING:  [RomM][2023-06-19 22:08:32] Pokemon Super Mystery Dungeon not found in IGDB
```

They're simple enough to find with the ID though and I can quickly set it up through the UI.
But it would be handy (somewhere down the line!) to be able to pull that info from the filename if provided.

Perfectly reasonable if it's not something worth including, just figured I'd raise it. :)

**Comment by GAntoine** [comment]
I think, in this case, it has to do with the `é` in Pokémon.

@zurdi15 Looking over the code, it seems the file name is run through `unidecode` before its sent to IGDB: `search_term: str = uc(get_search_term(file_name))`. Do you know why that is?

That being said, yes supporting something like `[igdbid=2842]` would be cool. Just need to figure out how it would mesh with some of the no-intro/rom scanning work.

**Comment by zurdi15** [comment]
I think this is a good idea.

> @zurdi15 Looking over the code, it seems the file name is run through `unidecode` before its sent to IGDB: `search_term: str = uc(get_search_term(file_name))`. Do you know why that is?

This is here because IGDB API search engine works so bad with special characters and most of the times it doesn't find the game if it has special characters in the name, I'll test those same examples and I'll let you know :)

> That being said, yes supporting something like `[igdbid=2842]` would be cool. Just need to figure out how it would mesh with some of the no-intro/rom scanning work.

About the scan, this should be transparent because this should be included as a special tag, like the region or the version, so we could use it to search directly by ID without problem.

**Comment by GAntoine** [comment]
Closing this as support for special characters during scans will improve in 1.9.2

**Comment by zodac** [comment]
> Closing this as support for special characters during scans will improve in 1.9.2

Hey @GAntoine , I know this was closed since my specific issue was resolve with better handle for special characters. I've updated to the latest version, but I think there's still some issues.

1) If I have games named similarly, the auto-detect is quite often picking up the wrong game from IGDB.
For example, a search for `God of War` returns `God of War 2` as the first search result, meaning my `God of War` (first game) is incorrecly tagged. Similar issue with `Pokémon Stadium` being detected as `Pokémon Stadium 2`. And another odd one with `Pokémon Emerald` being detected as `Pokémon Emerald Randomizer` as that is the first result.

2) Some games are still not being returned from an IGDB search by name. I'm searching for `Pokémon Super Mystery Dungeon` and `Pokemon Super Mystery Dungeon`, both returning no results, despite it clearly existing in IGDB. I need to search by ID to get it detect correctly:
https://www.igdb.com/games/pokemon-super-mystery-dungeon--1
![image](https://github.com/zurdi15/romm/assets/2502611/24c5afb7-47c0-4ce0-b632-3fef95745a71)

Could the idea of including a tag for IGDB in the ROM file name potentially be revisted? I can of course manually select the 'bad' ROMs after a scan, but as the library grows that's not sustainable if things need to be re-scanned. Renaming the files `Pokémon Super Mystery Dungeon [igdbid=10906]` and having a search on import for `igdbid` (similar to other tags), might be a better long-term solution?

Nothing urgent of course, interested to hear if others are having the same issue too. I can raise a fresh issue for discussion if required also. :)

**Comment by GAntoine** [comment]
1. I've opened a PR to improve search results: https://github.com/zurdi15/romm/pull/360
2. Seems like an issue with IGDB, I can't get it to return anything when searching for that title. Searches for "Pokemon Mystery" on the 3DS only returns [Pokémon Mystery Dungeon: Gates to Infinity](https://www.igdb.com/games/pokemon-mystery-dungeon-gates-to-infinity) 🤷🏼 
3. We can re-evaluate when we start working on the no-intro integration, and I'm curious to see what the effect will be
