### ISSUE TITLE
Add documentation for running on Unraid

### ISSUE THREAD

**Issue by GAntoine** [zurdi15/romm#290]
### Discussed in https://github.com/zurdi15/romm/discussions/289

<div type='discussions-op-text'>

<sup>Originally posted by **sfumat0** June 26, 2023</sup>
> I have seen a user reporting RomM working well on Unraid. I am attempting to set this up but failing. Is there a simple guide? I have used the docker-compose.example.yml to add in the variables, ports and paths but it doesn't seem to be creating the db or creating the config.
> This is my first post so please forgive me if this is not the right place to request support.</div>

**Comment by Smurre95** [comment]
I'm running it in unraid. with out any issues. I have not released the template as i was not sure it was done yet. I'm not home right now but i might be able to share this template later this week. But it was working fine for me just created a template no docker compose or so

**Comment by sfumat0** [comment]
I have it running but after the scan of atari2600 (as an initial test), the UI is very slow and after a few days the library was empty so I am sure I have not setup my template correctly. Here is a screenshot of my template (converted from Community App Store). I would love to update to latest release and start testing more.

![Zurdi15-romm](https://github.com/zurdi15/romm/assets/38845484/421b54bb-33d3-48d6-9490-753780658a7a)

**Comment by sfumat0** [comment]
I just wanted to report back that I updated to v1.9 and everything is working very well, everything is very responsive. I made no changes to the template just updated. I'll monitor over the next few days to ensure the config persists.

It would be great to see official UnRAID Community Apps support.

Great work on this project, really excited to see how far this goes and hope that I can contribute in some way over time.

**Comment by GAntoine** [comment]
@sfumat0 @Smurre95 World either of you be keen on writing short setup instructions to get RomM running on Unraid? Even something posted here as a comment would help tremendously, and we can expand on it, then move it to an appropriate place.

On a related note, I'm going to open another issue for community app support, which we can backlog separately.

**Comment by Smurre95** [comment]
Yeah sure im open to do that. I have never added a template to the unraid community app but i have used and created alot of them when it comes to dockers that did not have a template. I would say for unraid best is to get an official template and have support on that one

**Comment by GAntoine** [comment]
> I would say for unraid best is to get an official template and have support on that one

Awesome! While you get something written up, I'll get Unraid setup and ready to go. If I'm able to get RomM running successfully using your template (sorry if I'm using the wrong wording, I'm not familiar with Unraid), I'll export the XML and [submit it](https://forums.unraid.net/topic/57181-docker-faq/#comment-566084) to the Community Apps team.

**Comment by Smurre95** [comment]
Here is a pastebin of my XML file
https://pastebin.com/nk5Mistq

So i redid mine since i saw sfumats when i hade the access issue. So this is kinda generic from my opinion. Removed all my keys and stuff. The only thing that needs to be added is the location to your roms then it should just deploy

Might need to be a image for it to be added since right now the docker dose not have one

**Comment by GAntoine** [comment]
Thank you so much! I've expanded on the file you posted, and will give it a try later this evening (after I figure Unraid out lol).

```xml
<Container version="2">
   <Name>RomM</Name>
   <Repository>zurdi15/romm:latest</Repository>
   <Registry>https://hub.docker.com/r/zurdi15/romm</Registry>
   <Network>bridge</Network>
   <MyIP/>
   <Shell>sh</Shell>
   <Privileged>false</Privileged>
   <Support>https://github.com/zurdi15/romm/issues</Support>
   <Project>https://github.com/zurdi15/romm</Project>
   <Overview>RomM is a game library manager focused on retro games. Manage and organize all of your games from a web browser.</Overview>
   <ExtraSearchTerms>rom emulation gaming</ExtraSearchTerms>
   <Beta>False</Beta>
   <Category>MediaApp:Other</Category>
   <Date>2023-08-06</Date>
   <WebUI/>
   <TemplateURL/>
   <Icon>https://raw.githubusercontent.com/zurdi15/romm/master/romm.svg</Icon>
   <ExtraParams/>
   <PostArgs/>
   <CPUset/>
   <Requires>
   Redis
   MariaDB *(optional)*
   </Requires>
   <Screenshot>https://raw.githubusercontent.com/zurdi15/romm/master/.github/screenshots/home.png</Screenshot>
   <Screenshot>https://raw.githubusercontent.com/zurdi15/romm/master/.github/screenshots/gallery.png</Screenshot>
   <Screenshot>https://raw.githubusercontent.com/zurdi15/romm/master/.github/screenshots/details.png</Screenshot>
   <Screenshot>https://raw.githubusercontent.com/zurdi15/romm/master/.github/screenshots/search.png</Screenshot>
   <Config Name="Port" Target="80" Default="80" Mode="tcp" Description="" Type="Port" Display="always" Required="false" Mask="false">8091</Config>
   <Config Name="Library" Target="/romm/library/" Default="/romm/library" Mode="rw" Description="Game files" Type="Path" Display="always" Required="false" Mask="false"/>
   <Config Name="Config" Target="/romm/config" Default="" Mode="rw" Description="Config YAML file" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/romm/</Config>
   <Config Name="CLIENT_ID" Target="CLIENT_ID" Default="" Mode="" Description="IGDB Client ID" Type="Variable" Display="always" Required="false" Mask="false"/>
   <Config Name="CLIENT_SECRET" Target="CLIENT_SECRET" Default="" Mode="" Description="IGDB Client Secret" Type="Variable" Display="always" Required="false" Mask="false"/>
   <Config Name="Resources" Target="/romm/resources/" Default="" Mode="rw" Description="Metadata storage (covers, screenshots)" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/romm/resources/</Config>
   <Config Name="Logs" Target="/romm/logs" Default="" Mode="rw" Description="Log file storage" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/romm/logs</Config>
   <Config Name="Database" Target="/romm/database" Default="" Mode="rw" Description="Only needed if using SQLite" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/romm/database</Config>
</Container>
```

**Comment by Smurre95** [comment]
If you need some testing help i have my unraid available ish. Im no guru on unraid but I know my way basics around it. Just tell me im happy to help. Since im not so much of a coder anything for the community to move forward :D

**Comment by sfumat0** [comment]
I am also happy to test, I can maybe write up a step-by-step process if it helps until an official Community App is made?

Without an official community app, there is an option in UnRAID to build an app from Docker Hub, this will create a template and then the environment variables/paths can be added to that template by the user, this is how I installed. Note that I used mysql as I had issues with MariaDB although this is likely an issue on my side and I am not sure if using MariaDB carries any benefits. See image below:

![RomM UnRAID](https://github.com/zurdi15/romm/assets/38845484/dd2bb40f-7093-40ce-ab02-b9f9ec330683)

Everything is working as far as I can see, the only real downside is that the app icon is not added to the Docker section which is a minor thing.

**Comment by zurdi15** [comment]
I can't test this neither for lack of hardware, but thank you very much for contributing with this and testing who anyone that can do it!

**Comment by GAntoine** [comment]
> Will try the update romM template now to see how it looks

Please do let me know if the updated XML template is valid!

> I can maybe write up a step-by-step process if it helps until an official Community App is made?

Yes that would be super helpful, even some basic instructions would go a long way to getting Unraid users setup.

**Comment by sfumat0** [comment]
Please forgive me if this could be in a better format, before an official (or unofficial) community app is hosted in UnRAID, here are the steps I took to get this working in the UnRAID GUI:

1. Click 'APPS', search for 'zurdi15 romm' and then click the link (Click Here To Get More Results From DockerHub).

![1](https://github.com/zurdi15/romm/assets/38845484/2582da70-dcae-4505-8463-23f8f2e6c64b)

2. You should see 'romm' as the first option if you typed the search term correctly in step 1. Click 'Install'.

![2](https://github.com/zurdi15/romm/assets/38845484/6efb8696-d5d7-45dd-b1b3-d6365ee4ff07)

3. Click 'YES' on the pop up window to determine configuration.

![3](https://github.com/zurdi15/romm/assets/38845484/5fc2c451-bfa9-4871-8bee-b04a72d602ca)

4. Next you will see the base template for RomM, as below. Note that my app name shows 'romm-1' this is because I already have the app installed. You will see 'romm' on first installation.

![4](https://github.com/zurdi15/romm/assets/38845484/88c331d0-4586-444e-b922-d2465fd14c96)

5. Configure the required environment variables, ports and paths as per the example [docker-compose.yml](https://github.com/zurdi15/romm/blob/master/examples/docker-compose.example.yml) - You should see something similar to the below image. Note, this is using mysql, to configure with MariaDB, you will need to add this to the template.

![5](https://github.com/zurdi15/romm/assets/38845484/c0e0ae7e-c3e2-46c8-91f8-2c5ca2a1039e)


.... I hope this helps.

**Comment by sfumat0** [comment]
I should add that, with this setup I have a wonderful collection mapped:

![6](https://github.com/zurdi15/romm/assets/38845484/96fee603-eb3a-4e55-b4ea-d710a6f33e3f)

**Comment by GAntoine** [comment]
This is amazing, and should be enough to write a short wiki page. Could you do me one more favour and [export the XML](https://forums.unraid.net/topic/57181-docker-faq/#comment-566084) file? I'd like to compare it against the one submitted by smurre/merge them together before submitting it the CA team.

**Comment by Smurre95** [comment]
The settings he have is the same is mine since i copyied this settings when i re did mine. Have not had time to test the current template. But will do so soon

**Comment by Smurre95** [comment]
![image](https://github.com/zurdi15/romm/assets/9026729/c1eaedbc-4f7b-436c-b8f6-42d021b952bf)
The template looks to be loading in to unraid. But tested the picture and that one did not load in to my current docker so might need a diffrent size on that one ?

**Comment by GAntoine** [comment]
On a related note, I've just published a Wiki page with the instructions posted above: https://github.com/zurdi15/romm/wiki/Running-on-Unraid

**Comment by sfumat0** [comment]
Just a note that I clicked 'force update' which behaves correctly but it looks as though it has wiped my appdata folder, all resources still remain. I will need to rescan all platforms again but I will test if it duplicates resources.

![7](https://github.com/zurdi15/romm/assets/38845484/d7d49ef9-c8b9-42b3-9885-9423dfe88e62)

**Comment by sfumat0** [comment]
I've scanned 1 platform back in and it runs through the process of scanning at a similar speed, it does not duplicate any of the resources. There is no data in my appdata directory though. This doesn't seem correct. @Smurre95 - Do you see data in your config folder?

**Comment by Smurre95** [comment]
The config folder i dont think works because it refers to a YML file and not a folder so it seems to ignore it
![image](https://github.com/zurdi15/romm/assets/9026729/21825d1f-87aa-4276-b08e-c45e34f5dce1)
All the others is here

**Comment by GAntoine** [comment]
>  it refers to a YML file and not a folder so it seems to ignore it

That makes sense, I've updated the XML file to reflect the the fact it's s file.

**Comment by Smurre95** [comment]
![image](https://github.com/zurdi15/romm/assets/9026729/58d9c5da-20fc-4f30-a8aa-9693a88f24eb)
Updated my template with the following link and that worked
https://raw.githubusercontent.com/zurdi15/romm/master/romm.png

Thanks @zurdi15 for the updated PNG
@GAntoine If you have not updated the link then use the one i used above in the template and that should work

**Comment by Smurre95** [comment]
Should add the follwoing in the template
http://[IP]:[PORT:8091]/

![image](https://github.com/zurdi15/romm/assets/9026729/0488dbd9-91b6-4d44-8c53-c57cc8f8dcdb)
<Category/>
  <WebUI>http://[IP]:[PORT:8091]/</WebUI>
  
  
![image](https://github.com/zurdi15/romm/assets/9026729/8568faee-078e-4be1-b04b-abb026a19a85)

**Comment by Smurre95** [comment]
With the new RC3 out i have updated my template with redis varaibales and stuff. Should i share a new XML ?

**Comment by zurdi15** [comment]
Yes sure! Share it and I will update it once we release 2.0.0. Thank you!!

**Comment by GAntoine** [comment]
With the documentation in the wiki, I'm going to close this issue for now. Let's continue any conversations around the Unraid XML file in #323.
