### ISSUE TITLE
[Bug] Artwork downloads on scan but doesn't load into the app

### ISSUE THREAD

**Issue by kobeissi2** [zurdi15/romm#298]
**RomM version**
v1.8.4

**Describe the bug**
Artwork downloads but doesn't load

**To Reproduce**
1. Scan roms
2. Click on platform
4. See images not loading

**Expected behavior**
Downloaded artwork should load

**Screenshots**
![image](https://github.com/zurdi15/romm/assets/22063792/99e67621-5c95-4430-83ae-228ece3c3c81)
![image](https://github.com/zurdi15/romm/assets/22063792/ec6fd3b9-c215-4a27-9755-921600f1f2af)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 114.0.5735.199

**Smartphone (please complete the following information):**
N/A

**Additional context**
I tried setting the permissions to 777 just to see if it's a permission error but they still don't load.

**Comment by kobeissi2** [comment]
Image address is: http://localip/assets/romm/resources/xbox360/Red%20Dead%20Redemption%20-%20Game%20of%20the%20Year%20Edition/cover/small.png

> Could you right-click on the image that's not showing up, copy the URL and paste it here? And what happens if you try to open the image in a new tab?

Image address is: http://[Local IP]/assets/romm/resources/xbox360/Red%20Dead%20Redemption%20-%20Game%20of%20the%20Year%20Edition/cover/small.png

If I open in a new tab, I see this empty page: 
![image](https://github.com/zurdi15/romm/assets/22063792/4ddd790a-d7d1-4eb6-8c6e-5877f24011f7)

**Comment by kobeissi2** [comment]
Oops accidentally closed it. Sorry.

**Comment by GAntoine** [comment]
I see, and could you post your docker-compose file?

**Comment by kobeissi2** [comment]
I'm using the example one from this repo as a reference with TrueNas Scale. Could that be a cause even though it finds the ROMs, pulls the artwork and saves them to the directory?

**Comment by kobeissi2** [comment]
Works on my phone so its probably something on my PC blocking it  Will close this since it is an error on my end. Thanks for trying to help!
