### ISSUE TITLE
[Bug] Unable to find IGDB search results with revision in filename

### ISSUE THREAD

**Issue by helgehatt** [zurdi15/romm#301]
Description
---
No cover is found for games with (rev-Vx.x) in their file name.

Example
---
`Search IGDB` action with file name `Donkey Kong Country (U) (rev-V1.2) [!].smc` yields no results.

`Search IGDB` action with file name `Donkey Kong Country (U) [!].smc` yields nine results.

**Comment by GAntoine** [comment]
Well couple things here, first is that `(rev-V1.2)` is not a supporter revision format, as most systems expect `[Rev 1.2]`. In your case the scan is crashing when it hits that unexpected string. I'll fix the crash in an upcoming PR, but you'll need to update your ROM titles to a supported format.

**Comment by helgehatt** [comment]
Okay, but that format is from your «Tags support» section which states:

> Revision tags must be prefixed with "rev-": (rev-1) / (rev-v2) / (rev-whatever)

so maybe update the documentation as well?

Why not just remove everything in parenthesis and brackets in the query to IGDB? Then the query string would just be `Donkey Kong Country`. E.g. `re.sub(r" \(.+?\)", "", Path(filename).stem)` and similarly for brackets.

The format `(Vx.x)` should ideally be supported and recognized as revision as it is widely used in games downloaded from archive.org

**Comment by GAntoine** [comment]
Yeah that sounds reasonable, I'll take a crack at that regex and update my PR (and the docs) accordingly. 👍🏼

**Comment by helgehatt** [comment]
Would be nice if `(V1.2)` was recognized as revision without `rev` similar to how `(U)` is recognized as region without `reg`.

**Comment by GAntoine** [comment]
Something to consider in the future, but for the time being the current structure should cover most cases.
