### ISSUE TITLE
[Bug] Download button broken on iOS

### ISSUE THREAD

**Issue by helgehatt** [zurdi15/romm#319]
**RomM version**
1.9.1

**Describe the bug**
Download button is broken on iOS after updating to latest version. Now it just opens(?) an index.html file. See screenshot below

![B9248C8F-8D73-4745-8FC8-AB5459874CA9](https://github.com/zurdi15/romm/assets/12933913/bc8120bb-e7de-417f-a203-fd54db87f997)

**Comment by helgehatt** [comment]
I can check if it works on my laptop later, or if it’s the same there. I can also check the contents of the html file.

**Comment by GAntoine** [comment]
This is likely related to #297 and should be fixed once #316 relases in 1.9.2. I'll ping you when it does so you can try the fix.

**Comment by GAntoine** [comment]
Closing as a new version was released today.
