### ISSUE TITLE
Download Notification

### ISSUE THREAD

**Issue by ceratic** [zurdi15/romm#32]
At the moment, it is only possible to see if a download has started via the dev-tools of the browser. 

This isn't a problem with small files like GBA games or similar ones where it pops up relatively fast in the browser downloads, but when it goes to PS2 or Switch Games for instance, it would be nice to see a notification that the Download started.

**Comment by zurdi15** [comment]
Released [v1.2.2](https://github.com/zurdi15/romm/releases/tag/v1.2.2) with the feature added!
