### ISSUE TITLE
[Feature] PS2/OPL support

### ISSUE THREAD

**Issue by binarygeek119** [zurdi15/romm#324]
**Is your feature request related to a problem? Please describe.**
no, just something that would be nicer to have.

**Describe the solution you'd like**
opl or open ps2 loader loads iso from a nas or network share.
it has a 32 character limit. meaning some of the name is cut off
it also doesnt require the SERIAL to be in the name but loads faster with them in the name.
```
SLUS_207.45.Shrek 2.iso
SLUS_206.85.Ape Escape 2.iso
```
it be nice if you could scan the iso for the SERIAL there are a few tools out there that do this very thing. the SERIAL then could be used on a list (which are out there as well) to find the full name.
**Describe alternatives you've considered**
the ability to skip over the SERIAL  in the filename
```
SLUS_207.45.Shrek 2.iso
SLUS_206.85.Ape Escape 2.iso

```
becomes 
```
Shrek 2.iso
Ape Escape 2.iso
```
**Additional context**
this sound only need to happen with ps2 games.
ps2 iso renamer: https://www.psx-place.com/resources/eziso-renamer-by-raydenx.700/
another ps2 renamer: http://www.psxrenzukoken.com/nk2/download/psx-renamer-1-7-database/
this also has a database file the could be used.

**Comment by binarygeek119** [comment]
ive looked in to this a bit more
here is a link to a tool that does just that.

https://github.com/valters-tomsons/PS2-Game-Title-Finder

you will need this file aswell
https://github.com/mirror/pcsx2/blob/master/bin/GameIndex.dbf

**Comment by GAntoine** [comment]
I had some trouble parsing `GameIndex.dbf` into a format usable in python, so I [translated it to JSON](https://gist.github.com/GAntoine/ee232414768d7affb68516e71f1c3a04) (minus the patches).

Matching serial number with filename should be simple enough.

**Comment by binarygeek119** [comment]
just make sure to use the way OPL uses the codes.
SLUS_206.85
wordcode + _ + 3#'s + . + . + 2#'s
SLUS + _ + 206 + . + 85
only say this as your json uses SLES-55671.
you may be planning to do some converting in code.
