### ISSUE TITLE
[Bug] Deleted Games don't appear to update UI correctly

### ISSUE THREAD

**Issue by AndrewBudziszek** [zurdi15/romm#325]
**RomM version**
v1.9

**Describe the bug**
When deleting records from UI, the UI doesn't update accordingly. 

**To Reproduce**
1. Delete a game from your library in the UI
2. Observe game disappearing from library, but count in sidebar remains the same (even after reload)

**Expected behavior**
When deleting a game from your library, the games disappear from the library and the sidebar updates accordingly.
Any subsequent scans should pick the game back up again.

**Screenshots**
![image](https://github.com/zurdi15/romm/assets/8484828/ae60bb60-68c3-4a22-a4da-ab6a5442934e)

**Platform**
 - Running in Firefox

**Comment by GAntoine** [comment]
Confirmed, seems we don't emit a `refreshPlatforms` event on delete, like we do on scan.
