### ISSUE TITLE
 [Feature] Unzip files on the fly

### ISSUE THREAD

**Issue by victor10100111001** [zurdi15/romm#33]
Hi Zurdi,
You asked me to open an issue on unzipping files. I think this can both be done on the server side or in the browser. I think it is worth noting that this will cause a delay in the download process (especially for large files).

**Comment by zurdi15** [comment]
Hi, could you separate this issue in two? This remains as unzip files and open other one with multiple languages/revision flags

Thank you!

**Comment by victor10100111001** [comment]
> Hi, could you separate this issue in two? This remains as unzip files and open other one with multiple languages/revision flags
> 
> Thank you!

Done

**Comment by GAntoine** [comment]
As we've done the work to move ZIPing to the server, and this would introduce (sometimes significant) download delays, it's not something we're looking to do at this time.
