### ISSUE TITLE
[Bug] Multifiles download not downloading only eating server RAM

### ISSUE THREAD

**Issue by Smurre95** [zurdi15/romm#332]
**RomM version**
Version of RomM you are using
1.9.1
**Describe the bug**
When trying to download files that is a multi file selection i don't see any way that the download i starting or even starts creating a zip file. But in my main system i see the docker eating more and more ram. This is for any size of multi file selection. Once i let it be for about 30 min and it had almost all of my 40 GB of server ram allocated to it and still no download completed to my system. Dose not matter the size of the files. Tested with a Gamecube dual disc game so that would be about 3GB in total.

**To Reproduce**
Download more than one file form the same game

**Expected behavior**
To create a zip and then start the download

**Screenshots**

**Desktop (please complete the following information):**
Firefox
Version 116.0.2 (64-bit)
And
Edge
Version 115.0.1901.200 (Official build) (64-bit

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GAntoine** [comment]
I've seen this as well, and AFAICT it's due to python's inability to stream ZIP data. The fact that it keeps eating up memory is weird, but there are a couple solutions around this that I'd like to try.

**Comment by Smurre95** [comment]
![image](https://github.com/zurdi15/romm/assets/9026729/e0ad7b8e-57b3-4ce0-b56d-c1dca65a25bc)
So tested this now just to get a picture of it. Here is a 4 GB game using 10 GB RAM to zip. The work around I have right now is to pre zip all the correct files as one. so that it dose not get detected as multifile but as a zip. Any way just wanted to bring some light to this

**Comment by zurdi15** [comment]
Thank you for pointing it out. I never tried with something bigger than 1GB and didn't noticed.

**Comment by Smurre95** [comment]
![image](https://github.com/zurdi15/romm/assets/9026729/a426857a-8c4e-4cab-bae7-13f712104ac5)
Tested and working flawlessly on my system. OFC i was dum and tride it on Firefox at first but then went to edge and it downloaded the compresed file :D

**Comment by zurdi15** [comment]
Right now the downloader should be very much consistent!

**Comment by GAntoine** [comment]
@Smurre95 Are you using the latest version of master to test it (building you own image)? If so, can you try downloading multiple multi-file games at the same time, and let me know how it behaves?

**Comment by zurdi15** [comment]
I tested it and it works so smooth, but would be nice if @Smurre95 could test it.

**Comment by Smurre95** [comment]
ah i have run the dev-latest docker image and that works with out any issues
Also downloading two seems to work
![image](https://github.com/zurdi15/romm/assets/9026729/c65f321d-6691-433c-a0dd-31e7103aa4bd)
