### ISSUE TITLE
[Other] Discord Server - OPENED!

### ISSUE THREAD

**Issue by binarygeek119** [zurdi15/romm#334]
might be nice to setup a discord server.
people could ask for help, share setup screenshots, ideas, post bugs, and more.
ive seen many project on here go to discord to help grow.

**Comment by GAntoine** [comment]
I'm all for launching a discord server, and I think it's also a great place for us to keep the community informed on upcoming work and longer term plans, and have conversations in the open.

I would stress that we keep bug reports and feature requests to github issues, and limit help in discord to things like docker setup, mapping network drives, running on unraid, etc., the kinds of problems that are user-specific. Discord is not a forum, is not indexed by search engines, and is therefore not well suited for discovery/search.

**Comment by zurdi15** [comment]
RomM discord server is currently WIP, once it is properly setted up we will announce and open it to the community!

**Comment by zurdi15** [comment]
RomM official discord server is open! You can join with the invitation in the [README](https://github.com/zurdi15/romm#the-romm-community)

**Comment by Pfuenzle** [comment]
The invite in your README expired, is there a new link?

**Comment by zurdi15** [comment]
> The invite in your README expired, is there a new link?

I jus tested it and it worked for me 😕 

Can you paste here the link you are getting or the expired message?

**Comment by Pfuenzle** [comment]
On my phone the link is working fine for me I just realized, maybe the discord on my computer is buggy or something, sorry :)
