### ISSUE TITLE
[Feature] Better logs & error reporting

### ISSUE THREAD

**Issue by fatflyingpigs** [zurdi15/romm#336]
**Is your feature request related to a problem? Please describe.**
Semi bug related, I had an issue migrating to the new config, related to #65 .

Invalid platform in library has non-specific log entry. `Platforms not found. Check RomM folder structure here: https://github.com/zurdi15/romm#-folder-structure`

**Describe the solution you'd like**
Error should state additional information/specifics for the error. Searching this repo there is no info on how to enable debug mode or verbose logs. It doesn't say what platform is incorrect nor why.

**Describe alternatives you've considered**
I've tried a dozen things to 'fix' my config, including using the config.example file, but ultimately I need more information myself

Also:
**RomM version**
Latest, v1.9.1. It would be helpful if the program version was stated somewhere in the UI, maybe the settings page

**Comment by GAntoine** [comment]
I agree that logs could use some love overall, but in this case the issue is that no platforms could be found in the filesystem, not just a specific one.

> Platform**s** not found.

Could you post the romm section of your docker-compose.yml file and the config.yaml file?

> It would be helpful if the program version was stated somewhere in the UI, maybe the settings page

Also a good idea. 👍🏼

**Comment by zurdi15** [comment]
> > It would be helpful if the program version was stated somewhere in the UI, maybe the settings page
> 
> Also a good idea. 👍🏼

This was in the settings page since some versions ago In the `control panel` !!

![image](https://github.com/zurdi15/romm/assets/34356590/304c0526-a651-445b-b371-4574d6c13fab)

**Comment by fatflyingpigs** [comment]
My dyslexic ass had my previous library mapped to `/library/roms`, where the new path (according the docker compose) example is `/romm/library`. It works now!

And not sure what happened with the version in the settings... I remember distinctly checking it... probably some error on my part 🍺💫🥴
