### ISSUE TITLE
[Feature] Change zoom level for games grid

### ISSUE THREAD

**Issue by crispybegs** [zurdi15/romm#34]
is there a way of having an adjustable zoom level for the games grid? it looks fine on my laptop, but when on my desktop the covers are massive and you can only see a few at a time.

![Screenshot 2023-03-28 at 14 20 23](https://user-images.githubusercontent.com/129169122/228250430-a839a45c-9ef4-4758-bc2d-afe7442fada7.jpg)

Example zoom adjustment, with the contol bottom-right of the screen

![Screenshot 2023-03-28 at 14 18 38](https://user-images.githubusercontent.com/129169122/228251004-1818370b-4e5a-4d5e-82a2-e0600fe66f67.jpg)
![Screenshot 2023-03-28 at 14 18 56](https://user-images.githubusercontent.com/129169122/228251012-1ce3d3bf-a7f3-4fa3-be0d-e7c05eebb263.jpg)
![Screenshot 2023-03-28 at 14 19 25](https://user-images.githubusercontent.com/129169122/228251042-95de6992-90d2-4f67-a302-a59dfa43e40f.jpg)

**Comment by zurdi15** [comment]
Actually thought about this a lot, already have how to implement it in mind. Added to feature list

**Comment by XargonWan** [comment]
Addiotnal feature: show as detailed list with image on the right, name, details:

```
[ IMG ]   Game Name      Platform     Metadata1    Metadata2
[ IMG ]   Game Name      Platform     Metadata1    Metadata2
[ IMG ]   Game Name      Platform     Metadata1    Metadata2
[ IMG ]   Game Name      Platform     Metadata1    Metadata2
```

**Comment by zurdi15** [comment]
Added both gallery views in the last release [v1.6.5](https://github.com/zurdi15/romm/releases/tag/v1.6.5). Now games gallery can be display in three different views
