### ISSUE TITLE
[UI/UX] Game Cards should all be the same size, even if downloaded image is smaller.

### ISSUE THREAD

**Issue by AndrewBudziszek** [zurdi15/romm#340]
All cards should be of the same size (specifically height in my example)

![image](https://github.com/zurdi15/romm/assets/8484828/7260f1ce-3eb3-4be5-bf20-75390347ef95)

**Comment by GAntoine** [comment]
Yeah I'm annoyed by those as well, but I'm undecided about the best approach to take. Thoughts?

|A|B|C|D
|---|---|---|---|
|<img width="192" alt="Screenshot 2023-08-13 at 8 02 59 PM" src="https://github.com/zurdi15/romm/assets/3247106/f6034d67-d247-4555-94c9-dfd6272552fd">|<img width="192" alt="Screenshot 2023-08-13 at 8 03 16 PM" src="https://github.com/zurdi15/romm/assets/3247106/a0f81aba-019f-443e-a440-c692a3c5a196">|<img width="193" alt="Screenshot 2023-08-13 at 8 03 31 PM" src="https://github.com/zurdi15/romm/assets/3247106/598b03a9-09d3-4453-9745-ec3845fdbb22">|<img width="191" alt="Screenshot 2023-08-13 at 8 03 49 PM" src="https://github.com/zurdi15/romm/assets/3247106/7d568150-8bf9-4185-9a53-508352270437">|

**Comment by zurdi15** [comment]
Yeah something we didn't address yet but annoying. I think the best approach is the last one because I found sometimes bigger covers than the standard, so we can force them to be smaller, and force the small to be bigger.

**Comment by GAntoine** [comment]
I also think B makes the most "sense", but I'm pulled towards A and C for _aesthetic_ reason (even though it distorts the image pretty badly).

**Comment by zurdi15** [comment]
Hm in that case I am not sure, maybe C has my vote.

**Comment by zurdi15** [comment]
> I'd rather have a good image with a border than a bad image just to fit the frame.

Yeah that is true too. Maybe is a good thing to encourage someone to upload a proper cover to IGDB. You convinced me, my vote is for B.

**Comment by studioj2y** [comment]
B is good enough, showing there's different "formats" for different systems
