### ISSUE TITLE
[Bug] Unable to close file view on iOS

### ISSUE THREAD

**Issue by helgehatt** [zurdi15/romm#345]
**RomM version**
1.10

**Describe the bug**
Okay, so the download button now gives me the correct file instead of the `index.html` file, which I can `Open in…` and `Save to Files` to download a ROM to my local storage. The only problem is that there is no way to close the file view, and I have to close the app to go back. Here’s the "file view":

![D993AE6F-432C-4F04-BF1A-0BFAD180DC26](https://github.com/zurdi15/romm/assets/12933913/c3507dcf-aff3-428a-8b2d-c519d906fa9c)

**Comment by zurdi15** [comment]
Hmm this seems to be something iOS specific, because in android it just downloads it directly without going to the "file view". I can't try in iOS but if somehow you can try in android would be nice aswel.

I'll tag it as `help needed` to let other iOS users test this issue

**Comment by helgehatt** [comment]
I’m running the app as a PWA.

Tested directly in the Safari browser now and I  get this dialog instead:

![D620EC50-3F60-40EC-B7A8-E7BC2124D950](https://github.com/zurdi15/romm/assets/12933913/0bb1f8dd-cd58-41b8-851a-00f1dd3f3c45)

**Comment by zurdi15** [comment]
This is the thing, RomM is not ready yet to be used as PWA, so expect a lot of bugs. For now only direct browser usage is supported.

**Comment by helgehatt** [comment]
I see. I should’ve tested in the browser first. I just didn’t imagine the behavior would be different.

Thanks for letting me know.

**Comment by zurdi15** [comment]
It is different beacuse to work as PWA, it needs a worker that handles the backend requests and it works different :)
