### ISSUE TITLE
[Other] error bind mount using example compose file

### ISSUE THREAD

**Issue by javijuji** [zurdi15/romm#35]
I tried running the example compose file and keep getting an error related to a missing bind mount. 

_failed to deploy a stack: time="2023-03-28T13:30:15Z" level=warning msg="The \"Vi\" variable is not set. Defaulting to a blank string." Network romm_default Creating Network romm_default Created Container romm_db Creating Container romm_db Created Container romm Creating Container romm Created Container romm_db Starting Error response from daemon: Bind mount failed: '/data/compose/56/config' does not exists_

I am guessing this is related to the following:
Also not sure what the undefined Vi variable is

    volumes:
      - ./config:/config

I tried changing this to 

    volumes:
      - ./volume1/docker/romm:/config
      
_failed to deploy a stack: time="2023-03-28T13:34:24Z" level=warning msg="The \"Vi\" variable is not set. Defaulting to a blank string." Network romm_default Creating Network romm_default Created Container romm_db Creating Container romm_db Created Container romm Creating Container romm Created Container romm_db Starting Error response from daemon: Bind mount failed: '/data/compose/58/volume1/docker/romm' does not exists_

Should I create a config folder inside the data folder? I'd rather have config files in volume1/docker/romm and roms in volume1/data/media/roms

I can see it did actually try to create the database 

![image](https://user-images.githubusercontent.com/43682030/228258610-7bfa572d-94a8-4b40-a2e5-3c1117da778f.png)
![image](https://user-images.githubusercontent.com/43682030/228258855-cef21493-19cb-4a5d-965b-5dde330bd6d9.png)

currently compose file without the sensitive info

>`version: '3'
services:
  romm:
    image: 'zurdi15/romm:latest'
    container_name: romm
    network_mode: bridge0
    environment:
      - ROMM_DB_DRIVER="mariadb" # This variable can be set as: mariadb | sqlite. If it is not defined, sqlite will be the database by default
      - DB_HOST=romm_db # Only if ROMM_DB_DRIVER='mariadb'
      - DB_PORT=3306 # Only if ROMM_DB_DRIVER='mariadb'
      - DB_USER=romm-user # Only if ROMM_DB_DRIVER='mariadb'
      - DB_PASSWD=alreadychangedthis # Only if ROMM_DB_DRIVER='mariadb'
      - CLIENT_ID=gottheclientid
      - CLIENT_SECRET=gotthesecretaswell
      - STEAMGRIDDB_API_KEY=WIP
    volumes:
      - ./volume1/data/media/roms:/library
    ports:
      - '82:80' #80 was in use by pihole. Changed this to 82 on host
    depends_on:
      - romm_db
    restart: "unless-stopped"

 > romm_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: romm_db
    environment:
      - MYSQL_ROOT_PASSWORD=changedthisone
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=alsochangedthisone
    volumes:
      - ./config:/config #did not change this bind
    ports:
      - 3306:3306
    restart: "unless-stopped"
`

**Comment by ceratic** [comment]
Try leaving the leading "." within the volume mapping. 
```
volumes:
  - /volume1/docker/romm:/config
  ```

instead of 
```
volumes:
  - ./volume1/docker/romm:/config
```


That should fix your problem when mounting the dir within DSM7

**Comment by javijuji** [comment]
> Try leaving the leading "." within the volume mapping.
> 
> ```
> volumes:
>   - /volume1/docker/romm:/config
> ```
> 
> instead of
> 
> ```
> volumes:
>   - ./volume1/docker/romm:/config
> ```
> 
> That should fix your problem when mounting the dir within DSM7

Done! Thank you. Working now.

**Comment by javijuji** [comment]
Getting a different error now but it is unrelated

CRITICAL: [ROMM] Not supported "mariadb" database

tried deploying on docker synology and docker baremetal on a NUC with same results

**Comment by javijuji** [comment]
Managed to get this working. Forgot to delete the old database after redeploying the new stack which means database was using the old (Invalid because it had @) DB password.
