### ISSUE TITLE
[Feature] Deleted Items

### ISSUE THREAD

**Issue by KillahB33** [zurdi15/romm#351]
**Is your feature request related to a problem? Please describe.**
I have deleted files from the UI but everytime I rescan it gets readded. Is this just because I'm not using redis? or is it just the way it is?

**Describe the solution you'd like**
Once an item is deleted don't show it in the ui, or give an option to hide and then another option to show hidden

**Describe alternatives you've considered**
I'll just have to delete it every time, haha.

**Additional context**
This is specifically for my switch, I have a shop file present in the same folder so everytime i scan the switch directory that files shows up again.

**Comment by zurdi15** [comment]
This is not a bug, this is how RomM works. If you just delete one entry from RomM but you don't delete it from the filesystem, indeed each rescan will re-add the entry. You have few options here:

 - Use the "delete from filesystem" checkbox to delete the entry entirely from the system:
 
![image](https://github.com/zurdi15/romm/assets/34356590/a2b9fa3f-ca34-43a7-acbc-7b9203e90390)

 - Move it to other location in your filesystem
 - Add it to the excluded files in the config file. You have examples [here](https://github.com/zurdi15/romm#%EF%B8%8F-configuration-file)

**Comment by KillahB33** [comment]
Excluded is perfect, I missed that. Thank you!
