### ISSUE TITLE
[Feature] Game Save Support

### ISSUE THREAD

**Issue by LordZeuss** [zurdi15/romm#364]
Would it be possible to have a list of saves for each console? Like lets say I select the GBA. I would like to select a save file to download.

It would be even greater if you could add save files for a specific game. Say GBA -> Pokemon Fire Red and you can view saves that you have uploaded.

Just an idea. Thanks!

**Comment by GAntoine** [comment]
We've got another issue tracking this request, so I'm merging this one into it. #55
