### ISSUE TITLE
[Feature] Ability to set custom icons for platforms

### ISSUE THREAD

**Issue by Casuallynoted** [zurdi15/romm#368]
**Is your feature request related to a problem? Please describe.**
I don't know if it can be called a problem, but atm there are platforms that currently just use the generic icon because there aren't icons for them. I think this will always be a thing to some extent because there are so many obscure platforms out there!

**Describe the solution you'd like**
It would be neat to be able to change the name and icon of a platform and set your own if you'd like. That way, you can build out a more cohesive library even if your platforms are somewhat obscure.

**Describe alternatives you've considered**
Alternatively, we could expand the set of icons available to cover everything currently on IGDB but that's a lot of work and idk how much benefit it would yield past a certain point.

**Comment by GAntoine** [comment]
Great idea, but it'll take us a bit of time to get to it.

If you're really keen on having custom icons today (and not too picky about where you source them), you can mount `/var/www/html/assets/platforms` to some local folder and place all of your custom `.ico` platform icons in there, alongside the ones [provided in this project](https://github.com/zurdi15/romm/tree/release/frontend/assets/platforms).

**Comment by GAntoine** [comment]
Wrote a quick wiki page with the same info: https://github.com/zurdi15/romm/wiki/Custom-Platform-Icons

**Comment by crispybegs** [comment]
> Wrote a quick wiki page with the same info: https://github.com/zurdi15/romm/wiki/Custom-Platform-Icons
> 
> I'll be closing this issue since there's now a document and fairly easy way to use your own icons.

is this no longer a feature? the wiki page is empty
