### ISSUE TITLE
[UI/UX] MAME games and file naming/IGDB metadata

### ISSUE THREAD

**Issue by Casuallynoted** [zurdi15/romm#369]
I've been getting into MAME roms recently (would likely fit under the "arcade" platform in romm), and realised that MAME roms have to have specific names in order to load properly within MAME. There are XML files used for renaming apps that can match games up to specific names and pull the matching game info.

The tricky part is that if they're using the proper names, IGDB metadata almost never gets pulled. I was thinking possibly there could be a way  of auto-matching mame zips with the correct names to their IGDB metadata without requiring the user to manually go through and label each game or rename them to something that won't load in the emulator. Definitely want to get others thoughts on this one as I know this is a bit more of a niche topic.

**Comment by GAntoine** [comment]
Can you give me an example of some of those specific file names?

**Comment by Casuallynoted** [comment]
I can do one better! Here's the latest Hyperspin MAME xml with all the games and their expected file names:

https://gist.github.com/Casuallynoted/5cf0c0a92ed27305068014d93a72012d

**Comment by GAntoine** [comment]
Oh awesome! We have something similar for PS2 OPL support, and upcoming work for Switch TitleDB. Is there a public source for this XML file that gets updated regularly? Something like https://github.com/blawar/titledb/tree/master, unless we don't need to update it regularly and can just include it once?

**Comment by Casuallynoted** [comment]
> Oh awesome! We have something similar for PS2 OPL support, and upcoming work for Switch TitleDB. Is there a public source for this XML file that gets updated regularly? Something like https://github.com/blawar/titledb/tree/master, unless we don't need to update it regularly and can just include it once?

Good question! Typically there would be a source from HyperSpin, but they've been redoing their site. Let me see if I can get the link still though...


Got it!

http://hyperlist.hyperspin-fe.com/genall.php?system=6

**Comment by GAntoine** [comment]
Ok it was actually quite easy to add this to https://github.com/zurdi15/romm/pull/357 since I already built the systems to update the file(s) nightly. Once it merges (hopefully in the 2.1 RC) it'll map shortnames to fill game names!

![Image](https://github.com/zurdi15/romm/assets/3247106/d984757c-4071-4d3b-b70e-e3ec4437a0f8)


![Image](https://github.com/zurdi15/romm/assets/3247106/a578352e-df3a-408c-845a-ab346ec7f341)

**Comment by w00tlarr** [comment]
Hiya: http://hyperlist.hyperspin-fe.com/genall.php?system=6 is down for me today. DNS failure?
Is it OK to grab from https://gist.github.com/Casuallynoted/5cf0c0a92ed27305068014d93a72012d instead?

**Comment by Casuallynoted** [comment]
> Hiya: http://hyperlist.hyperspin-fe.com/genall.php?system=6 is down for me today. DNS failure? Is it OK to grab from https://gist.github.com/Casuallynoted/5cf0c0a92ed27305068014d93a72012d instead?

Yeah, sadly the site’s been up and down a lot lately with the changes they’ve been making. I’m not against my gist being used as a backup in the event the original site is down!

**Comment by GAntoine** [comment]
The gist is exactly what we'd need but the file was too large to include directly in the code base. I don't think there's an easy way to replace the hyperspin URL with the gist to fetch it, or manually upload an XML file.

**Comment by Casuallynoted** [comment]
> The gist is exactly what we'd need but the file was too large to include directly in the code base. I don't think there's an easy way to replace the hyperspin URL with the gist to fetch it, or manually upload an XML file.

Just to clarify, atm if someone were to manually download the gist text, pop that into a mame.xml in the proper folder, would that work as a temporary solution?

**Comment by GAntoine** [comment]
You got it! If placed under `handler/fixtures/mame.xml` it should just work, even with the task disabled.

**Comment by Casuallynoted** [comment]
> You got it! If placed under `handler/fixtures/mame.xml` it should just work, even with the task disabled.

Sadly, mine doesn't seem to be- the MAME games all still have the zip titles. Is there anything in the logs that would help me debug it?

**Comment by GAntoine** [comment]
You can run a rescan and look at the log output, see what it says about "not found in IGDB". Also make sure the file permissions make it readable.

**Comment by w00tlarr** [comment]
I'm not too familiar with python/github... but I docker volumized /backend/tasks/update_mame_xml.py with this change and it worked:

class UpdateMAMEXMLTask(RemoteFilePullTask):
    def __init__(self):
        super().__init__(
            func="tasks.update_mame_xml.update_mame_xml_task.run",
            description="mame xml update",
            enabled=ENABLE_SCHEDULED_UPDATE_MAME_XML,
            cron_string=SCHEDULED_UPDATE_MAME_XML_CRON,
            url="https://gist.githubusercontent.com/Casuallynoted/5cf0c0a92ed27305068014d93a72012d/raw/1c030bd19787ff1f7dad2242c61cc9735296f8aa/gistfile1.txt",
            file_path=FIXTURE_FILE_PATH,
        )

**Comment by GAntoine** [comment]
Yeah that'll work, guess we can switch to it for now and build a way to hotswap the source in the future. PR is welcome!

**Comment by Casuallynoted** [comment]
> You can run a rescan and look at the log output, see what it says about "not found in IGDB". Also make sure the file permissions make it readable.

What's weird is when I manually run a rescan, all it gives me is:

INFO:     [RomM][2023-11-04 19:48:57] 🔎 Scanning 
19:48:57 high: endpoints.scan.scan_platforms(['arcade'], False, []) (2be0cc2e-2fe3-4cfa-bc13-5c2a41cb7fcb)
INFO:     [RomM][2023-11-04 19:48:58] · arcade
INFO:     [RomM][2023-11-04 19:48:58]   Identified as Arcade 🎮

And then nothing else.

**Comment by gantoine** [comment]
Closing as the next release will use a different source for the XML file
