### ISSUE TITLE
[Bug] IGDB handshake times out regularly

### ISSUE THREAD

**Issue by hotleadsingerguy** [zurdi15/romm#375]
**RomM version**
2.0.0-rc.2

**Describe the bug**
While doing the initial scan the scanner will make it through 50-70 roms at a time, then stop. Logs show a handshake timeout with IGDB. Starting scan again works fine, but will hit the same wall.

**To Reproduce**
1. Go to Scan page
2. Click on Scan
3. At some point titles will stop being populated in the list of identified items
4. Check docker-compose logs romm

**Expected behavior**
Handshake/timeout issues should be retested or avoided entirely, if possible

**Log File**
[error.txt](https://github.com/zurdi15/romm/files/12649994/error.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Chrome (latest)

**Server**
- OS: Ubuntu Server 22.04 LTS

**Additional Context**
-Running multiple Pi-Holes, but no blocks detected.
-Running Unifi Dream Machine Pro as primary router, geo-blocking most countries in the world (but no blocks detected here)

Original discussion here: https://discord.com/channels/1138838206532554853/1153319115554033685

**Comment by zurdi15** [comment]
As commented in the discord server, seems like IGDB have a timeout when detecting too many requests. Also as @hotleadsingerguy said seems like that timeout is there for at least 120s, so managing that should fix any issue with large libraries.
