### ISSUE TITLE
[Bug] Searching for a game only returns games that have been seen in the interface

### ISSUE THREAD

**Issue by Casuallynoted** [zurdi15/romm#378]
**RomM version**
2.0rc5

**Describe the bug**
When searching for a game in a big library, it only seems to search the game that have currently been scrolled through. So for example, when first loading my Xbox library if I search for Tetris, it says no results found. However, if I scroll down to where Tetris is in the games list, then I am able to search for it.

**To Reproduce**
1. Open a platform's library
2. Type the name of a game that is toward the end of the list into the search box
3. Game will not be found

**Expected behavior**
Ideally, it should be able to pull games regardless of whether the UI has loaded them- this would definitely make navigating larger libraries a lot easier.

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser: Chrome
 - Version: 117

**Comment by Casuallynoted** [comment]
This issue seems to be resolved in the latest dev release! Won't close yet cause wanna have one of the devs confirm, but on my end search seems to be pulling even from items at the end of the list :)

**Comment by zurdi15** [comment]
Yeah this issue is solved already! :)
