### ISSUE TITLE
[Feature] Display multi-disk games as one game

### ISSUE THREAD

**Issue by Casuallynoted** [zurdi15/romm#381]
**Is your feature request related to a problem? Please describe.**
At the moment, importing a multi-disk game means that you'll have multiple entries of what appear to be the same exact game in your list, without distinction.

**Describe the solution you'd like**
It would be neat to see the game have little icon in the the top right to indicate it's a multi-disk game, and have multiple download options for each disk contained all under one entry.

**Comment by GAntoine** [comment]
RomM already support multi-disk games, and all you need to do is place all the discs under 1 folder. What does your file structure look like?

**Comment by Casuallynoted** [comment]
> RomM already support multi-disk games, and all you need to do is place all the discs under 1 folder. What does your file structure look like?

Oh shoot, I'm an idiot! I'll fix that hahaha
