### ISSUE TITLE
[Bug] MaxRetryError while scanning

### ISSUE THREAD

**Issue by helgehatt** [zurdi15/romm#390]
**RomM version**
1.10

**Describe the bug**

Got the following error while scanning:
```
Task exception was never retrieved
future: <Task finished name='Task-57' coro=<AsyncServer._handle_event_internal() done, defined at /usr/local/lib/python3.10/dist-packages/socketio/asyncio_server.py:522> exception=SSLError(MaxRetryError("HTTPSConnectionPool(host='images.igdb.com', port=443): Max retries exceeded with url: /igdb/image/upload/t_original/k1tmntgpkmuzqrffb0hh.jpg (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))"))>
```

The error is not handled in the frontend and continues "scanning" indefinitely.

**Comment by GAntoine** [comment]
IGDB has been having intermittent SSL issue for the lat few weeks, and this looks like one of them. RomM 2.0  (which will release later this month) has improved error handling which should suppress most of these errors.
