### ISSUE TITLE
[BUG] Could not get twitch auth token: check client_id and client_secret

### ISSUE THREAD

**Issue by jonathan-gatard** [zurdi15/romm#394]
**RomM version**
docker : latest (1.10)

**Describe the bug**
"Could not get twitch auth token: check client_id and client_secret"

**To Reproduce**
Use docker-compose + romm image

**Expected behavior**
Retrieve token from Twitch

**Screenshots**
![image](https://github.com/zurdi15/romm/assets/2879180/1170db85-f816-45c1-8bf8-8b5dff4f9b46)

**Additional context**
This is my docker-compose:
![image](https://github.com/zurdi15/romm/assets/2879180/0bab21f0-a194-42d4-8c36-071e92027529)

1 - FYI, I changed the port to 84 in nginx.conf, it works I have access to GUI
2 - When I POST request to API, it works
![image](https://github.com/zurdi15/romm/assets/2879180/b75348d2-ed39-40e3-b70d-e6bbf2b8f62a)
3 - My ENV var are correctly initialized in the docker
![image](https://github.com/zurdi15/romm/assets/2879180/f353a28f-9856-44e9-80be-35c46246185b)

4 - My Twitch config, I'm not sure about http://localhost
![image](https://github.com/zurdi15/romm/assets/2879180/4e313391-0fef-4982-bf0d-51dd0d44f875)

**Comment by jonathan-gatard** [comment]
Update:

It almost works with image dev-latest
Token is working, Scan is working, but auth is not working:
![image](https://github.com/zurdi15/romm/assets/2879180/541ebdfe-689f-48cf-acb4-5c8b485759cc)

It disconnect me in loop:
![image](https://github.com/zurdi15/romm/assets/2879180/1a60505a-c791-4721-b5dc-07d99ca50218)

**Comment by GAntoine** [comment]
Right so the docs are currently wrong for `1.x` images (non-preview), the key should be `CLIENT_ID` and `CLIENT_SECRET`, but the new keys will work fine on `dev-latest`.

As for the auth issue, it's either a) not able to set a session cookie on the main host or b) failing CSRF validation. Can you check the console in your browser and lmk the error message that appears along the 403 error code?

**Comment by jonathan-gatard** [comment]
Hi,

![image](https://github.com/zurdi15/romm/assets/2879180/2d04a030-07d9-4b44-b5d0-5e82d50e5e94)

Below the console log:
`{
    "message": "Request failed with status code 403",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 403\n    at _0 (https://romm.xxxxx.fr/assets/index.5858bdb4.js:15:952)\n    at XMLHttpRequest.f (https://romm.xxxxxx.fr/assets/index.5858bdb4.js:15:4051)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 120000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "x-csrftoken": ".eJwFwdsOQzAAANB_8S7ZTDoeF9U2pczMGt5QdJgp4rKv3zmajeyCw0awCwnDroBFxlm-jku2UGC_Qkh5zzyJcmew9IDhxPjOCrMaO96xyGOcuGs-3OtWgSPoc0MCe9-25BOncNhx81vO2QQnsqpV-JyW2Ce7PkeFhV2AToFqyXrryka8a8KeqvGAnKUeVCZMU0UnU-dOHbexCOM7gl6k_QG4EDoO.eW97qp6HC8hEKFMyqG0FaEAn0k8"
        },
        "baseURL": "/api",
        "method": "get",
        "url": "/platforms"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 403
}`

**Comment by GAntoine** [comment]
Hmm well you've got a CSRF token set, can you try clearing your cookies (session and csrf) and reloading, then sign in again?

If that then still doesn't work, can you post a screenshot of your cookies (should include session id and csrf cookie)? Also I'm assuming you're using a reverse proxy to access romm.xxxxx.fr?

**Comment by jonathan-gatard** [comment]
I don't have improvement even if I clean cookies, storage, etc... I also tried private mode.
Below crsftoken and session cookies :
![image](https://github.com/zurdi15/romm/assets/2879180/1ae73f48-0f77-403f-a35d-8080562295ed)

Yes I am using reverse proxy, below the config:
![image](https://github.com/zurdi15/romm/assets/2879180/4878e1a9-db3b-4f0e-94a4-94fe7f79ef33)
![image](https://github.com/zurdi15/romm/assets/2879180/6ff29369-fe16-4daf-8e09-4f8e5999eec9)

**Comment by gantoine** [comment]
@jonathan-gatard Sorry it took a while to get back to this, just to verify are you currently running redis somewhere? Authentication requires you to run Redis, check out the [wiki](https://github.com/zurdi15/romm/wiki/Authentication) for more details.
