### ISSUE TITLE
[Feature] Recently Added carousel

### ISSUE THREAD

**Issue by therobbiedavis** [zurdi15/romm#400]
**Is your feature request related to a problem? Please describe.**
I'd like for myself or others to see what was recently added to my romm instance. It can be a bit tedious to load up a platform page and wait for all the IGDB images to load.

**Describe the solution you'd like**
I think it might be a neat feature to have a "Recently Added" carousel on the main page; either above or below the platform listings. My thought is it would be similar to Plex (see image).
![image](https://github.com/zurdi15/romm/assets/7907265/d9d3d029-9878-404b-9cf1-4fdd2c43b3b6)

**Describe alternatives you've considered**
I have not considered other alternatives

**Comment by zurdi15** [comment]
@therobbiedavis I just opened a [PR](#416) and added a screenshot for this!

**Comment by zurdi15** [comment]
Added in #416
