### ISSUE TITLE
[Feature] Route single rom Downloads through the backend

### ISSUE THREAD

**Issue by psych0d0g** [zurdi15/romm#405]
**Is your feature request related to a problem? Please describe.**
For security reasons it would make sense to have downloads processed by the backend code, even for single file downloads, so that when a user has authentication enabled, someone with a direct link can not download any files without being logged in.

Currently downloads of single files are directly handled by a static symlink inside of the docker container that enables nginx to directly access the files in question and statically serve them for downloading.

**Comment by zurdi15** [comment]
Yeah you are totally right, this is something we need to address in the next iteration of the user management system.
