### ISSUE TITLE
[Bug] Wrong Console shown when clicking sidebar

### ISSUE THREAD

**Issue by bbbreaddd** [zurdi15/romm#408]
**RomM version**
2.0.0
**Describe the bug**
Wrong console showing up when choosing a console from the sidebar
**To Reproduce**
1. Pick any console
2. Pick a game from that console
3. Choose another console from the sidebar
4. Last console pressed shown instead of the one I pressed

**Expected behavior**
The console I pressed shows

**Screenshots**
![image](https://github.com/zurdi15/romm/assets/136384195/03696692-fb20-455c-b618-4d9eb9689cc9)

**Client:**
Firefox + Thorium Desktop(Both have the same issue)
Chrome on Android also has the same issue

https://github.com/zurdi15/romm/assets/136384195/94bf76ea-7e87-4028-873f-e0deb2654789

**Comment by GAntoine** [comment]
Confirmed, seems to be related to the romStore.
