### ISSUE TITLE
[Bug] Login loop

### ISSUE THREAD

**Issue by Djiit** [zurdi15/romm#410]
**RomM version**
2.0.0

**Describe the bug**
I have to relogin each time I visit a new page for the first time. e.g. when I visit a platform.

**To Reproduce**
1. Login
2. Go to a platform
3. See error

**Expected behavior**
I have to login once.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 118

**Additional context**
Just updated my deployment to 2.0.0

**Comment by GAntoine** [comment]
Might be related to a CSRF issue, can you clear your cookies and cache, and login again? If you still see the error, post it the network and console output here please.

**Comment by Djiit** [comment]
Same behavior with cookies/cache cleared, or from a private navigation tab : 
![img1](https://github.com/zurdi15/romm/assets/1169844/182bc2a5-c010-4dfc-b7e9-5b90275981d3)
![img2](https://github.com/zurdi15/romm/assets/1169844/473ca512-8535-4428-9c91-5eadbf651215)

I'm running romm in a kube cluster behind a nginx ingress controller. Any particular config I should set?

**Comment by zurdi15** [comment]
Can you please share your docker-compose or your docker command?

**Comment by psych0d0g** [comment]
try to increase the max proxy size on your ingress object, set this as an annotation for example:
          nginx.ingress.kubernetes.io/proxy-body-size: 256m

might also get away with a smaller proxy-body-size setting tho

**Comment by psych0d0g** [comment]
just to clarify, do you have redis setup and running? afaik thats required to store the login sessions, see: https://github.com/zurdi15/romm/wiki/Authentication

**Comment by Djiit** [comment]
Hu, I guess I missed this. Deploying a redis now...

**Comment by Djiit** [comment]
Same error. How Can I make sure romm is using the Redis? any log line I can look for ?

**Comment by Djiit** [comment]
Yeah that was it. My bad. I guess I scanned through the changelog and did not see the doc. Have a great day

**Comment by vodkapmp** [comment]
If anyone ends up here like me, and can't understand why you're stuck with a login loop even when all the redis stuff is setup.

You also need to add `ENABLE_EXPERIMENTAL_REDIS=true`
Even though that's not documented under authentication nor redis-cache docs.
https://github.com/zurdi15/romm/wiki/Authentication
https://github.com/zurdi15/romm/wiki/Redis-Cache

**Comment by gantoine** [comment]
@vodkapmp Thanks for that, we've recently updated the wiki in preparation for the 3.0 release which simplifies setup and environment variables, which means it's out of date for 2.x.
