### ISSUE TITLE
[Feature] Redis Password Option

### ISSUE THREAD

**Issue by Bovive** [zurdi15/romm#412]
**Is your feature request related to a problem? Please describe.**
Currently unable to use Redis if Redis is using a password.

**Describe the solution you'd like**
A REDIS_PASSWORD environmental variable.

**Describe alternatives you've considered**
Being able to use password@host for the REDIS_HOST environmental variable would also work.

**Additional context**
I was referred here from Discord. Thanks!

**Comment by zurdi15** [comment]
Feature added in #413
