### ISSUE TITLE
[Feature] Background scanning

### ISSUE THREAD

**Issue by LeaderbotX400** [zurdi15/romm#415]
Not sure if this is already a thing, but I can't find any reference to it

Add the ability to run scans in the background (eg. on a cron job or as a button on the dash)

**Comment by GAntoine** [comment]
If you [enable the experimental Redis back-end](https://github.com/zurdi15/romm/wiki/Experimental-Redis-Cache), scans will run in a worker (for up to 4 hours).

We also have [something in the works](https://github.com/zurdi15/romm/pull/357) that introduces task scheduling, which will include recurring background scans.
