### ISSUE TITLE
[Bug] docker-compose example typo

### ISSUE THREAD

**Issue by SadGrimReaper** [zurdi15/romm#418]
**RomM version**
2.0.1

**Describe the bug**
DB_HOST=mariadb needs to be changed to DB_HOST=romm_db

**Additional context**
I told Zurdi about a bug where mariadb wasnt named romm_db and he forgot to change the DB_Host.

**Comment by zurdi15** [comment]
You are right. Fixed in the last master [commit](https://github.com/zurdi15/romm/commit/58fa37d99a9bc5ee1fd001bc98b78896ea4789f5)

**Comment by SadGrimReaper** [comment]
Aight nice. And sorry forgot the title there.
