### ISSUE TITLE
[Feature] Option to manually trigger a task

### ISSUE THREAD

**Issue by Casuallynoted** [zurdi15/romm#437]
**Is your feature request related to a problem? Please describe.**
The new task system is AWESOME, and I love it. But at the moment you have to wait until the specified time for the scheduled task to run, there aren't any other ways of getting these tasks to trigger.

**Describe the solution you'd like**
 I think in the event we need it to do something right away (for debug purposes, especially), it might be useful to have a manual trigger button for each of the tasks that runs it on a one-time basis in addition to the specified schedule.

**Describe alternatives you've considered**
Alternatively, we could have env variables that have it run on launch but I feel like that would be weird and not as intuitive.

**Additional context**
I love the power glove! It's so bad.

**Comment by GAntoine** [comment]
@zurdi15 What do you think about adding a "Run now" button (or something like it) to the settings page where we have the enabled/disabled states for tasks? And I guess you should be able to manually run a task even if it's not enabled/scheduled?

**Comment by zurdi15** [comment]
Yeah seems like a useful feature. Running it on demand it's always a good idea.

**Comment by elliswalker** [comment]
I'm actually noticing my arcade and cps folders are not being scanned through the MAME xml scheduler. They're all set to the mame shortnames, but only things like 1942 work because, well, that's the name. haha
great work on this so far. I work in tech and this is something I've been hoping for for a while.

**Comment by gantoine** [comment]
@elliswalker could you post a screenshot of your folder structure for arcade and cps folders so i can replicate them locally and test this?

**Comment by elliswalker** [comment]
![explorer_y03e4AuBLr](https://github.com/zurdi15/romm/assets/20954295/cb2ceff7-dda9-4dd9-b029-6cab75af9d78)

side note: complete scan after updating wouldn't remove now missing files, and the tg-16/pce folders aren't recognized. I've changed them a few times and they never show back up in the platforms or library section. not sure if you know what they should be labelled as I must have something wrong. pce is the last try, and nothing came through

**Comment by elliswalker** [comment]
didn't realize how goofy some of the naming got "turbografx16--1"... bro. hahaha
however igdb only has arcade, i can't find a cps1, 2, or 3 anywhere. with the roms coming from a romset in mame format (i.e. aburner instead of afterburner) shouldnt the nightly job to fix them work?

**Comment by gantoine** [comment]
the async job should work, but it only runs on the `mame` folder/for the MAME platform:

```
if platform_idgb_id == ARCADE_IGDB_ID:
            mame_index = {"menu": {"game": []}}
            ...
```
