### ISSUE TITLE
[Feature] improve filter possibilities

### ISSUE THREAD

**Issue by fabiencharrasse** [zurdi15/romm#443]
**Is your feature request related to a problem? Please describe.**
I just installed Romm and I have several hundred games:
- With duplicates (Series of games all marked on the first number of the series for example)
- Without images (File name without space between words, therefore not recognized).

**Describe the solution you'd like**
Being able to filter the list of games according to different criteria:

_and easily target them for manual editing):_
- Games without images
- Duplicate games (multiple files for the same IGDB ID)

_to look for a game that would suit my tastes:_
- By genre, publication date, game modes, series, type of view (first/third person), etc... (All information available at IGDB)

**Describe alternatives you've considered**

**Additional context**

**Comment by RFMV34** [comment]
+1

**Comment by Casuallynoted** [comment]
I believe this has been done as of 3.0!
