### ISSUE TITLE
[Feature] Option to order by name instead of filename

### ISSUE THREAD

**Issue by Alucardac1** [zurdi15/romm#450]
**Is your feature request related to a problem? Please describe.**
The current problem is that games are listed in order of their filenames, however since filenames can vary in format depending on their source, tags, etc it can randomly place them in the list. For example, Disney games on most sources begin with "Disney's <Title Here>" however IGDB doesn't include these titles or variations. 

so "A Bugs Life" will show up in the D section because the rom file is named "Disneys A Bugs Life.chd". The same goes for some NDS rom files, which when named may start with their identification number, This results in them being pushed to the front of the Library instead of their correct alphabetical section.

**Describe the solution you'd like**
An option or default to order lists according to their metadata name instead of their filename, this is only currently possible in the list view, but needs to be applied each time its used.

**Describe alternatives you've considered**
The alternatives include renaming every rom file using the in app system, however it would destroy any name formatting which may be required for some frontends such as Emulation Station, there is also no way I can find to do this on mass. On top of this the rename tool also as of writing is effected by bug #392 which causes the filenames to be garbled if the library is also a Samba share or used in Windows and the name uses certain special characters.

**Comment by gantoine** [comment]
This will be generally available in the next release.
