### ISSUE TITLE
[Feature] Differentiate "delete" and "hide"

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#456]
The actual "delete" function is in fact an "hide" function unless I check the delete file box: the rom is still there hence is not managed in RomM.

I suggest to split the hide function and the delete function upon confirmation.

**Comment by zurdi15** [comment]
Hmm you are right, but to "unhide" you need to rescan. For practical purposes it is as if it had never been scanned or recently added. I don't feel like it is like "hide". Being hidden should be like if you can't see it but any other user can see it in his account.

This said, I think can be a good idea to implement a real "hide" feature. What do you think?

**Comment by gantoine** [comment]
IMO the current UI works well, as deleting files is destructive and **should** be an extra step in the process.

**Comment by csudderth** [comment]
I think a good use case for hiding ROMs would be hiding based on region, revision, or other tags. I'd like to be able to have RomM manage all of my roms, but only normally display my USA ROMs with the option of viewing other regions if needed.

**Comment by gantoine** [comment]
@csudderth check out #404
