### ISSUE TITLE
[Feature] Exclusion improvement with UI management

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#457]
Now the filters are managed via this file: https://github.com/zurdi15/romm/blob/release/examples/config.example.yml

I believe that this feature can be enhanced.

## Step 1
- instead of splitting the exclusion patterns into single files, multi files, names and extensions it could be based on a logic similar to the gitignore file: the pattern is excluded based on the path, so `.xml` can exclude whatever path contains `.xml`, such as `roms/gb/gamelist.xml` or `roms/.xml/sonic.zip`
- these paths can be edited via Settings -> Control Panel and they don't need an app restart (but probably it would trigger a quick library rescan).

## Step 2
Give the ability to exclude an element via contextual menu. Example:
- Open the contextual menu on a scanned file that appears as readme.txt inside the gb system (roms/gb/readme.txt).
- Press Ignore (or Exclude)
- A popup will ask what to ignore, in this case the options will be:
1. Full path: roms/gb/readme.txt
2. Basename: *readme*
3. Extension: *.txt
4. Custom (see below)

These exclusions are added to the UI in the Step 1.

※ On custom I can declare a custom rule (in this case would be the same as Step 1 as it could be not even related with the actual item), for example: roms/gb/*.txt because I may want to exclude the txt files only in the gb folder and show them in the snes folder.

### NOTE
The exclusion can be an actual file such as the .gitignore so it would be easier to move between deployments.

**Comment by zurdi15** [comment]
I already thought about managing the config file from the UI, but you made it very detailed, thank you very much.

I like the contextual menu idea a lot tho.

**Comment by XargonWan** [comment]
We were talking about this in RomM: https://github.com/zurdi15/romm/discussions/296

**Comment by gantoine** [comment]
Complete!
