### ISSUE TITLE
[Feature] Allow Continuation of Scanning Process After RomsNotFoundException

### ISSUE THREAD

**Issue by psych0d0g** [zurdi15/romm#460]
**Is your feature request related to a problem? Please describe.**
Currently, when the RomM scanning process encounters a non-existing platform roms folder and raises a RomsNotFoundException, it halts the entire scanning process, requiring the user to restart the scan from the beginning. This can be inconvenient and time-consuming, especially when dealing with multiple platforms.

**Describe the solution you'd like**
I would like to suggest an enhancement to RomM's scanning functionality. When a RomsNotFoundException is encountered, RomM should log the issue and continue scanning the next platform instead of terminating the entire scan process. This would significantly improve the user experience and save time when fixing or excluding specific platform folders.

**Describe alternatives you've considered**
An alternative approach could be to implement a manual resume feature that allows users to restart the scan process from the point where it was interrupted due to a RomsNotFoundException. However, this would require additional user intervention and might be more complex to implement.

**Additional context**
This enhancement would improve RomM's usability and efficiency, especially when dealing with large collections of roms.

```
23:54:56 [Job 99cc710d-250f-4ee5-bc05-85a98169907f]: exception raised while executing (endpoints.scan.scan_platforms)
Traceback (most recent call last):
  File "/backend/utils/fs.py", line 232, in get_roms
    fs_single_roms: list[str] = list(os.walk(roms_file_path))[0][2]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/backend/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
    rv = job.perform()
  File "/backend/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
    self._result = self._execute()
  File "/backend/lib/python3.10/site-packages/rq/job.py", line 1318, in _execute
    coro_result = loop.run_until_complete(result)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/backend/endpoints/scan.py", line 53, in scan_platforms
    fs_roms = fs.get_roms(scanned_platform.fs_slug)
  File "/backend/utils/fs.py", line 234, in get_roms
    raise RomsNotFoundException(p_slug) from exc
exceptions.fs_exceptions.RomsNotFoundException: Roms not found for platform HiVE. Check RomM folder structure here: https://github.com/zurdi15/romm#-folder-structure
```

**Comment by zurdi15** [comment]
Yeah you are totally right, RomM should warning the problem with that platform but not break the entire scan just for that.

**Comment by alexfornuto** [comment]
I hate to tack on with a "me too" comment, but I wanted to mention that it seems like romm being so particular about the directory structure and presence of non-rom files within is unreasonable. My rom directories are already sorted and organized for other tools and systems, and I can't even evaluate romm without restructuring first.

**Comment by gantoine** [comment]
If you don't mind me asking, which tools and systems are you currently using? We plan in the medium term to build-in support for the file systems of various platforms (retroarch, emudeck, onion, garlic, libretro), which should remove that obstacle.
