### ISSUE TITLE
[Feature] Rescan item upon reaming/editing

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#468]
When I rename a file via RomM I must manually delete it and trigger a rescan to update my library.
Is it possible to automatically force rescan the edited item?

**Comment by gantoine** [comment]
Are you sure that it doesn't just need a refresh? I can't imaging it would need a full rescan since we update the DB directly with the new file and path (I think...)

**Comment by XargonWan** [comment]
Yes probably you're right, I tried to refresh it and it worked.
