### ISSUE TITLE
[Other] Possible to change RomM port?

### ISSUE THREAD

**Issue by zodac** [zurdi15/romm#469]
Hi,

I know it's possible to change the exposed port through docker, but is it possible to change the internal `8080` port too? I didn't see any environment variable for it. It's currently conflicting with another application, and I was hoping it would be a simple thing to change?

**Comment by zurdi15** [comment]
Well, the internal port can't be conflicting with anything because that's not how it works, it is the external port the one that can conflict with other services in your host machine, but the internal is only visible to the container itself :/

**Comment by zodac** [comment]
If I have a docker network configured, and multiple services in the same network, they can all see the internal ports, no? I have another service using port 8080 for its internal port, and when I start up RomM, I get this error in the logs:

```
07:11:39 Worker rq:worker:9b35f751396d48d7b1b8024eb44acfca started with PID 15, version 1.15.1
07:11:39 Subscribing to channel rq:pubsub:9b35f751396d48d7b1b8024eb44acfca
07:11:39 *** Listening on high, default, low...
INFO:     [RomM][alembic.runtime.migration] Context impl SQLiteImpl.
INFO:     [RomM][alembic.runtime.migration] Will assume non-transactional DDL.
INFO:     [RomM][2023-11-19 07:11:39] Starting scheduler
ERROR:    [Errno 98] Address in use
```

**Comment by smileham** [comment]
I'm having the same issue, my docker-compose.yml uses:

  romm:
    image: zurdi15/romm
    container_name: romm
    environment:
      - IGDB_CLIENT_ID=xxx
      - IGDB_CLIENT_SECRET=xxx
    volumes:
      - /media/Drive/Games/Library:/romm/library
      - /opt/romm/config.yml:/romm/config.yml
      - /opt/romm/database:/romm/database
    ports:
      - "8090:8080/tcp"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

To map port 8090 externally to 8080 internally, which works the "first" time, but if I stop/restart the container I then get the same error as above:

INFO:     [RomM][alembic.runtime.migration] Context impl SQLiteImpl.
INFO:     [RomM][alembic.runtime.migration] Will assume non-transactional DDL.
WARNING:  [RomM][2023-11-21 17:49:54] Twitch token invalid: fetching a new one...
ERROR:    [Errno 98] Address in use
