### ISSUE TITLE
[Bug] Infinite Loading on Scan

### ISSUE THREAD

**Issue by stenny94** [zurdi15/romm#470]
**RomM version**
Docker Latest as of Nov. 21 (sha256: 5c21bf870db0253288e75e5c17b64867f514abe7982b58d7674a4bf8ef0dba8d); Github Latest is v2.1.0.

**Describe the bug**
When I scan for roms it never stops loading (scanning).

**To Reproduce**
1. Create a docker container with the IGDB Secret and Client
2. Boot the container
3. Scan
4. Infinite Loading (Error)

**Expected behavior**
Complete the scan of the roms.

**Screenshots**

https://github.com/zurdi15/romm/assets/101674800/9928123b-17dd-41f5-b5f1-565a64b30fad

**Desktop (please complete the following information):**
 - OS: [Windows, Linux]
 - Browser [Opera GX, Firefox]
 - Version [OGX: 118, FX: 119.0.1]

**Smartphone (please complete the following information):**
 - Device: [N/A]
 - OS: [N/A]
 - Browser [N/A]
 - Version [N/A]

**Additional context**
I was using Portainer to setup RomM. It could just be a user error.

**Comment by fbr1969** [comment]
Hi, I have exactly the same problem.

**Comment by gantoine** [comment]
Something probably crashed in the scan, you'll need to post the container logs @stenny94 @fbr1969

**Comment by TopHatMan** [comment]
I got the same issue this sums up my log

`WARNING:  [RomM][2023-12-02 12:42:11] Twitch token invalid: fetching a new one...
INFO:	  [RomM][2023-12-02 12:42:12] Twitch token fetched!
`

**Comment by csudderth** [comment]
I am facing the same issue and I have the same info in my log. It seems to discover a single platform, but no games, and then scans infinitely.

**Comment by csudderth** [comment]
@gantoine 

This is all I have in my logs:
```
WARNING:  [RomM][2023-12-03 08:01:22] Twitch token invalid: fetching a new one...
WARNING:  [RomM][2023-12-03 08:01:22] Twitch token invalid: fetching a new one...
INFO:	  [RomM][2023-12-03 08:01:23] Twitch token fetched!
INFO:	  [RomM][2023-12-03 08:01:23] Twitch token fetched!
INFO:	  [RomM][2023-12-03 08:02:00] 🔎 Scanning 
INFO:	  [RomM][2023-12-03 08:02:15] · wii
INFO:	  [RomM][2023-12-03 08:02:16]   Identified as Wii 🎮
```
The scan is still going, but nothing has been logged for about 48 minutes. It discovers a single platform, but doesn't progress after that. There are no games listed either.

**Comment by Wheels35** [comment]
this is also happening to me as well.

Single platform discovered, scans indefinitely

**Comment by gantoine** [comment]
I've added more logging in #490 which should let us know if the scan finds any platforms, and when it ends. I'm assuming everyone who's having this problem is for the same reason, bad folder structure.

**Comment by csudderth** [comment]
@gantoine Thank you so much! I will do a once-over of my folder structure. This is a really neat project, by the way!
