### ISSUE TITLE
[Bug] Download button not working on individual game view

### ISSUE THREAD

**Issue by XTREEMMAK** [zurdi15/romm#471]
**RomM version**
2.1.0

**Describe the bug**
When you browse to any individual game and try to download, nothing happens. Only after you refresh the page while in the game view does download start.

**To Reproduce**
1. Pick any game
2. Press the download button. Notice that the downloader doesn't start
3. Refresh the page
4. Press download button again
5. Download begins

**Expected behavior**
Download should start when pressing the button always

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome/Firefox/Edge

**Additional context**
Doesn't look like I'm getting any 400 errors on the first request from console in the browser.

**Comment by gantoine** [comment]
Interesting, are you getting anything in the network tab when downloading? Single-file roms are downloaded direct from the filesystem for speed. How big is the game you're trying to download?

**Comment by XTREEMMAK** [comment]
So strange,
So on multi disk content, they'll start no problem. In network tab, I get a websocket created and the download begins while telling it to save in zip. Sidenote, if I cancel the download and try the download button again, nothing happens until I navigate away and back into the same game and try again.

On single file games, such as GBA stuff, when I navigate to the general listing (full grid view) and hit download, downloads start fine. I dont see a websocket created in Network view, but I do see that 200 request in Docker log. So that's fine.

When I go to a game directly though and hit download, I don't see a request for it in docker, nor any new requests or websockets created when I hit download. Once I hit refresh however and try again. I do see the 200 request in docker.

This happens for any single file download regardless of size.

**Comment by gantoine** [comment]
> Sidenote, if I cancel the download and try the download button again, nothing happens until I navigate away and back into the same game and try again.

Ok that's a bug and we'll likely need to fix it at some point.

> I dont see a websocket created in Network view, but I do see that 200 request in Docker log

That's correct, as single files are direct-downloaded (and not zipped).

> This happens for any single file download regardless of size.

I think switching to passing all requests for download to the backend would make the most sense, and likely reduce the amount of these issues. @zurdi15 what do you think?
