### ISSUE TITLE
[Other] Add information about custom platforms to the wiki

### ISSUE THREAD

**Issue by Casuallynoted** [zurdi15/romm#486]
Since not all platforms will be covered by IGDB's platform list, it might be good to have information on the wiki about how to name folders and icons for custom platforms in the event users want to create them, especially as far as things like capital letters and spaces in platform names are concerned. 

For example, if I want to add the Konami Picno, and I create a folder called "picno", it shows up in the sidebar without the first letter capitalised. If I capitalise the letter, the sidebar looks correct but the icon doesn't work. Likewise, if I create the folder pocket-challenge-v2, it uses the dashes rather than the spaces to spell out the proper name, Pocket Challenge V2. I have a bit of understanding of how to properly name these but it's not very comprehensive, so I figured it might be worth having that information documented.

**Comment by gantoine** [comment]
Alright I've fixed the sidebar issue with in #487, but it requires a rescan to work correctly. As for the wiki, the only requirements are that the platform folder slug be lowercase, and words connected with `-`, like IGDB does it. You're always welcome to write a short wiki entry on how to setup custom platforms, I'm sure some users would appreciate it!

**Comment by gantoine** [comment]
Closing this as I've updated the wiki page for custom platforms
