### ISSUE TITLE
[Feature] Automatic mechanism to move roms that are available in several languages to other folders

### ISSUE THREAD

**Issue by Waffelparty** [zurdi15/romm#495]
**Is your feature request related to a problem? Please describe.**
It would be nice, if i (or we) could have an automatism, which will move/delete roms, which are available in more than one languages.

**Describe the solution you'd like**
If you have rom X in  several language available, for example US, EU and JP,  RomM should  only keep the one in the prefered languages and move the other files in another folder, outside your collection. Maybe with a list for prefered languages. If first language isnt available, use the second prefered language.

I hope you understand what my intention is. My english isnt the best.

**Comment by XargonWan** [comment]
Could [this](https://github.com/zurdi15/romm/issues/404) be a valid solution to you?

**Comment by Waffelparty** [comment]
yeah, would be a good alternative and would be much easier to manage and cleaning the collection :)

**Comment by gantoine** [comment]
Going to close this and use the other issue to manage both requests.
