### ISSUE TITLE
[UI/UX] Show games from every platforms

### ISSUE THREAD

**Issue by Cuissedemouche** [zurdi15/romm#499]
Hi,

I think it could be nice if we could just visualize all the games we have in our database, not platform specific.
I like the idea that I want to play something, don't know what and can easily scroll through all the games without selecting first a system.

**Comment by gantoine** [comment]
We have a closed issue with this request #23, essentially it would cause issues with search and pagination. We are planning on building a "collections" feature which would allow you to create custom groups of games #219
