### ISSUE TITLE
[Feature] Authentication and user management

### ISSUE THREAD

**Issue by crispybegs** [zurdi15/romm#50]
i open up some of my services _(like overseer / audiobookshelf / calibre-web / komga etc)_ via cloudflare tunnels, but all these have username / password and user management or some other authentication to help prevent bad actors.

Any plans for something similar here so we can open up to the internet relatively safely?

**Comment by victor10100111001** [comment]
> i open up some of my services _(like overseer / audiobookshelf / calibre-web / komga etc)_ via cloudflare tunnels, but all these have username / password and user management or some other authentication to help prevent bad actors.
> 
> Any plans for something similar here so we can open up to the internet relatively safely?

I dont know if this is possible with cloudflare tunnels, but with nginx proxy manager you can create access lists which will make nginx ask for a password before proxying your request.

**Comment by DebugDax** [comment]
> i open up some of my services _(like overseer / audiobookshelf / calibre-web / komga etc)_ via cloudflare tunnels, but all these have username / password and user management or some other authentication to help prevent bad actors.
> 
> Any plans for something similar here so we can open up to the internet relatively safely?

If you are using cloudflare tunnel, then in the Zero Trust panel just setup the site in the Applications menu to require authentication. Cloudflare gives you it's own page to control if any tunneled apps require logging in.

https://developers.cloudflare.com/cloudflare-one/applications/configure-apps/self-hosted-apps/

**Comment by crispybegs** [comment]
> > i open up some of my services _(like overseer / audiobookshelf / calibre-web / komga etc)_ via cloudflare tunnels, but all these have username / password and user management or some other authentication to help prevent bad actors.
> > Any plans for something similar here so we can open up to the internet relatively safely?
> 
> I dont know if this is possible with cloudflare tunnels, but with nginx proxy manager you can create access lists which will make nginx ask for a password before proxying your request.

yes but once allowed in anyone who has access can still delete / edit stuff... so a difference between access and permissions is the useful part here. There's a bunch of people i'd love to show my RomM library to but I can't as they'll have full access

**Comment by matthewmorris09** [comment]
I know you mentioned that this is lower on your immediate roadmap but I wanted to add my +1 for this feature. I just recently ran into a situation where it would have been awesome to have a family member login and have access.

**Comment by zurdi15** [comment]
Well, after a month I am reaching a relatively good code base + base features to starting to think and design the user management system, so I will put it in the priority list :)

**Comment by philipjholm** [comment]
Please make this optional if possible as I only run this locally and have no need for login.

**Comment by Coo-ops** [comment]
OIDC, please!
