### ISSUE TITLE
[Bug] Folder overrides fail to scan

### ISSUE THREAD

**Issue by DragRedSim** [zurdi15/romm#501]
**RomM version**
2.1.0 (Docker); no Redis install available

**Describe the bug**
Scanning folders which are mapped through a config file association fails.

**To Reproduce**
1. Set up folder structure for ROMs, specifically storing Genesis/MD roms in a folder titled `megadrive`
2. Add the following to your config.yml: 
`system:
  platforms:
    megadrive: 'genesis-slash-megadrive'`
3. Attempt to scan JUST the specific console 'Sega Mega Drive/Genesis' from the HTTP interface

**Expected behavior**
The folder is successfully scanned.

**Actual behavior**
The following log is emitted:
`Task exception was never retrieved

future: <Task finished name='Task-252' coro=<AsyncServer._handle_event_internal() done, defined at /backend/lib/python3.10/site-packages/socketio/asyncio_server.py:522> exception=AttributeError("'NoneType' object has no attribute 'fs_slug'")>

Traceback (most recent call last):

  File "/backend/lib/python3.10/site-packages/socketio/asyncio_server.py", line 524, in _handle_event_internal

    r = await server._trigger_event(data[0], namespace, sid, *data[1:])

  File "/backend/lib/python3.10/site-packages/socketio/asyncio_server.py", line 558, in _trigger_event

    ret = await handler(*args)

  File "/backend/endpoints/scan.py", line 100, in scan_handler

    else:

  File "/backend/endpoints/scan.py", line 35, in scan_platforms

    platform_list = [dbh.get_platform(s).fs_slug for s in platform_slugs]

  File "/backend/endpoints/scan.py", line 35, in <listcomp>

    platform_list = [dbh.get_platform(s).fs_slug for s in platform_slugs]

AttributeError: 'NoneType' object has no attribute 'fs_slug'`

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 120.0.1

**Additional context**
My suspicion is that for some reason, the folder overrides are not taken into account when the slug is looked up. Looking at the websocket traffic, the following is sent from the browser to the server: `42["scan",{"platforms":["megadrive"],"rescan":false}]`. As I understand it: `scan_handler()` is calling `scan_platforms()` with this data, and `scan_platforms()` attempts to populate its `platform_list` by calling `dbh.get_platform()` using this slug. `dbh.get_platform()` fails to find a result in its database, and returns a None object. `scan_platforms()` then attempts to subscript this None object to get its fs_slug value, which obviously fails with an error. The next line, the `platform_list = platform_list or fs_platforms` would cause an empty platform_list to be populated with the result of the earlier call to `fs.get_platforms()`, but the error occurs before this call can be made. The appropriate call to `dbh.add_platform()` only appears in the for-loop which follows the `dbh.get_platform()` call; meaning it can never be reached if it does not already exist in the database.

**Comment by gantoine** [comment]
What's interesting is that the websocket sends `["megadrive"]`, whereas i'd expect it to use the IGDB slug/slug in the url in the webhook. That's what I'm seeing locally when trying to replicate your setup.

<img width="388" alt="Screenshot 2023-12-21 at 7 33 05 PM" src="https://github.com/zurdi15/romm/assets/3247106/d21c0a58-aed0-44e3-af91-63b5c0b262ce">

**Comment by DragRedSim** [comment]
Hmm, that's odd. Especially that given if I hover over the platform in the library list on the left, it does show the linked URL as using the standard `genesis-slash-megadrive` slug... Not being too familiar with Vue, I'm not exactly sure where the flow is for selecting the individual slugs sent in the websocket.

**Comment by gantoine** [comment]
aha! If you're using the scan button in the gallery, it uses the route param:

```
socket.emit("scan", {
    platforms: [route.params.platform],
    rescan: false,
  });
```

buuuttt if you're scanning via the scan view, it uses the igdb slug!

```
platforms: platformsToScan.value.map((p) => p.slug),
```

i'll update it to use the fs_slug, which is what it's expecting to receive in the scan backend.

**Comment by DragRedSim** [comment]
That's probably why we had the confusion then; I didn't know you even could scan a platform from the gallery, only from its own page in the rail, so I didn't mention it in any greater detail than "run a scan". Good to see that watching the websockets helped us figure that bit out, in terms of the difference between how we were operating the same task - and that they had a different behaviour.

**Comment by DragRedSim** [comment]
OK, just updated my Docker to the latest (2.2.1) as at time of writing... and it's still behaving in the manner described (scanning not working for overridden platforms from the scan view; works from platform page).

Now that I think about it... actually passing the `fs_slug` is a symptom of the issue manifesting. My folder is named something that the IGDB lookup doesn't recognise, and passing in the folder name will cause the lookup not to find anything. Rather, what needs to be passed in is the original slug, as defined as the value of the key/value pair in the overrides in the config. The `fs_slug` is the folder name that is the key of the pair, and is used to define the local path, but not the one that should be being called by the scan operation.

> buuuttt if you're scanning via the scan view, it uses the igdb slug!
> 
> ```
> platforms: platformsToScan.value.map((p) => p.slug),
> ```
> 
> i'll update it to use the fs_slug, which is what it's expecting to receive in the scan backend.

It didn't actually use the IGDB slug; it used the local folder name as the value passed through the websocket, and that was causing it to lock up when the folder name did not match an IGDB slug - the inverse of what we wanted, to take the folder name and use that for a scan. Now we're deliberately passing the local folder name, for the same effect. 

As I understand it, the scan/Base.vue file defines a platformsToScan as the values selected in a web element; that element populates its options from the const Platforms, which is set to the result of `storePlatforms()`. This calls the Platforms store to return its contents. So where is the Platforms store populated? Back at `onMounted` (in the Main.vue), to the result of `api.fetchPlatforms()`, which is the result of calling the `/platforms` API endpoint. All the way back here... the values of `slug` and `fs-slug` are different, for the one platform which has a path override. And what we should be passing through the websocket as a value is the value of `slug`, so that the database can look up that slug and return a folder path to scan.

So we've introduced a bug for folder overrides, and not actually fixed the original bug; the fact that the scan process attempts to take the `fs_slug` value of a NoneType object (which is returned from the database helper) as part of the list comprehension. Not to say that this is an appropriate way of handling it, but should the command be replaced with:

```
platform_list = [dbh.get_platform(s).fs_slug for s in platform_slugs if dbh,get_platform(s) is not None]
platform_list = platform_list or [platform for platform in fs_platforms where platform in platform_slugs]
platform_list = platform_list or fs_platforms
```

This would (theoretically) only create an entry in `platform_list` if there was an entry in the database to source the fs_slug value from, and leave nothing otherwise; from there, it would then attempt to take the platform slugs provided, and find that folder in the rompath and use that; failing a match there, since `platform_list` had no values, it would be assigned all values from `fs_platforms` and proceed with those items (returned from `get_platforms()`), in order to scan everything when passed no parameter for what to scan. `fastapi.scan_platform()` would later be called passing in the fs_slug and returning a Platform, which does have the override applied within that function, and it then gets added to the database.

(Since I'm not a collaborator on the repo, I can't re-open this issue; so I'll just cc in @gantoine and @zurdi15 here.)

**Comment by zurdi15** [comment]
@DragRedSim this should be fixed in the last version :)
