### ISSUE TITLE
Auth issue

### ISSUE THREAD

**Issue by grantpeterwilliamson** [zurdi15/romm#502]
**RomM version**
v2.1.0

**Describe the bug**
first of all, im running unraid, its just been added to the community apps.

![Screenshot 2023-12-20 173044](https://github.com/zurdi15/romm/assets/64010828/eedd272f-6457-49ff-933b-cfc087b24c20)

im having a issue trying to get romm working with authentication.

i've followed the wiki on enabling ROMM_AUTH_USERNAME and ROMM_AUTH_PASSWORD and ROMM_AUTH_SECRET_KEY

i have also enabled the redis with ENABLE_EXPERIMENTAL_REDIS=true
and set my REDIS_HOST= and REDIS_PORT= appropriately

 the first start of ROMM with these settings gave me the normal ROMM homepage

after a few refreshes i would get a login screen, Putting in my ROMM_AUTH_USERNAME and ROMM_AUTH_PASSWORD details would get me a "forbidden" Error

![Screenshot 2023-12-20 172718](https://github.com/zurdi15/romm/assets/64010828/8f05116e-eaa2-4d87-8457-c18b55e2ae6f)

i have confirmed that my redis is working, but it would appear that its being used for everything But storing the user?

![Screenshot 2023-12-20 172515](https://github.com/zurdi15/romm/assets/64010828/aa3ea215-659d-43a7-ab11-b3faad0bb1cb)

any help or pointers would be great! ^-^

**Comment by Some1OnLine** [comment]
I too am trying to figure out how to setup this on my unraid host.

The docker won't start until I provide it with a Secret and an ID. Yet, Registering an App with IGDB Dev Portal requires an Auth Req URI which I though has to be the Docker App that wont start?

Confusing. But interesting.

**Comment by gantoine** [comment]
For IGDB you can put basically any url in, even localhost and it'll work as it doesn't actually try to contact your server. As for the auth issue, the Unraid docs in the wiki are the most the have so far.

Both of us (maintainers) are unfamiliar with unraid, so eventually i'd like to nominate some unraid experts in the community who can help maintain the docs and troubleshoot.

**Comment by mustafa-sibai** [comment]
I had the same issue. I am also running on Unraid. Going into Incognito mode fixed the issue. Clearing cookies worked for me too.

**Comment by gantoine** [comment]
We've merged in some improved error messages for the login page, which will hopefully make ti easier to debug these issues after the next release. 

@grantpeterwilliamson As far as I can tell your setup looks right, only thing I can recommend is to try hat mustafa did and clear your cache/cookies.

**Comment by grantpeterwilliamson** [comment]
I'll give it a go this evening when I get home and report back 😄

**Comment by cannibal3004** [comment]
FYI, I couldn't register the application in Chrome no matter what I did. I tried to add an application with Edge and it worked first try. So maybe try another browser if you can't get an application to register.

**Comment by gantoine** [comment]
That is really strange, but I'm happy to hear it work in one browser. @cannibal3004 Can you try to login on mobile as well?

**Comment by Jinorex** [comment]
@grantpeterwilliamson I had the same problem with the unraid community plugin. From Eurotimmy's.
I had a redis running but it wouldnt work. 
Hooked up a vm with docker and everything was good to go! 

So instead of using the unraid CA I created my own local unraid template. Using the provided .xml of this repo.
After some tweaking, changing the url and deleting the config path. Everything worked for me.

@gantoine As for Twitch Application registration, I just created a new developer account. Maybe I had to wait a day after that? 
Because the first day I could not create an application. The second day I had no problems creating one.
Now everything is running.

**Comment by grantpeterwilliamson** [comment]
First of all, MERRY CHRISTMAS! sorry had to done 😅


I see, where you running your own redis docker container as well as room
under unraid?

As for running it on a VM with docker I'll give that a go my self just to
make sure it works as it should 😄

**Comment by Jinorex** [comment]
Merry Christmas indeed!
Yes, in unraid I had both RomM and redis running as different "community applications". (Docker containers)

In the VM I did basically the same thing. But there i pulled them directly from dockerhub.
