### ISSUE TITLE
[Feature] MAME XML support for Neo Geo AES and MVS

### ISSUE THREAD

**Issue by Casuallynoted** [zurdi15/romm#503]
**Is your feature request related to a problem? Please describe.**
It looks like roms for the AES and MVS also use the MAME naming format, which makes sense considering for all intents and purposes they're also arcade roms.

**Describe the solution you'd like**
It would be a good idea to extend the MAME XML functionality to the AES and MVS platforms as well.

**Comment by gantoine** [comment]
Easy enough to do, i'll pop it in the backlog
