### ISSUE TITLE
[Bug] After every reboot: Twitch token invalid: fetching a new one...

### ISSUE THREAD

**Issue by adam-fox** [zurdi15/romm#505]
**RomM version**
2.1.0

**Describe the bug**
Every time I reload the docker container after first boot it crashes with the error "WARNING:  [RomM][2023-12-21 21:21:05] Twitch token invalid: fetching a new one..."

**To Reproduce**
1. Reload the docker container

**Expected behavior**
Docker container should load

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gantoine** [comment]
If you're not using the Redis backend that message is expected. Without redis the twitch token is stored in memory, which gets wiped on restart. Are you seeing the "twitch token fetched" success message after that one?

**Comment by adam-fox** [comment]
apologies! i actually just discovered this a few minutes ago. everything seems to be working as expected now. 

appreciate the response!

**Comment by cherryontopknife** [comment]
This occurs for me. The twitch token is not re-fetched.

So you have to use the redis backend in order for the container to work at all? I've never had this much trouble setting up a container before =/ Scanning also fails even though I follow the naming conventions perfectly.

**Comment by gantoine** [comment]
@cherryontopknife the redis backend is only required for authentication, twitch token fetching and scanning should work without it. 

The thing is romm does a lot of cool things, and there are some complex systems that make it all happen (folder change detection, file matching, scheduled tasks, hash matching (eventually) etc).
