### ISSUE TITLE
[Feature] Option to manually match custom rom folder vs IGDB Platform/system

### ISSUE THREAD

**Issue by oscruise** [zurdi15/romm#514]
**Is your feature request related to a problem? Please describe.**
I have my rom folders structure as requested (and automatically created) by Batocera. Many of the roms system folders are named different as of the IGDB web pages, e.g. “genesis” vs “megadrive-slash-genesis”, “dreamcast” vs “dc” or “psx” vs “ps”

**Describe the solution you'd like**
If there is a way that we can manually indicate that a folder could be linked to a specific IGDB naming system in romm settings, a lot of different gaming platforms/managers/launchers could be used and still be scrapped by romm without having to use fancy workarounds like symlinks or having to manually edit rom by rom in that system.

**Describe alternatives you've considered**
Maybe have the ability to use various scrapers? I see that there are a few others like screenscrapper.

**Comment by rodrigorodrigo** [comment]
+1, Emudeck user here.

having the same issue with various systems (gamecube, dreamcast, genesis to name a few) where metadata is not scraped because the (emudeck-generated) name is not what RomM expects

**Comment by gantoine** [comment]
You can configure which folders map to which platforms (IGDB slugs), take a look at the bottom of the [example config file](https://github.com/zurdi15/romm/blob/release/examples/config.example.yml).

**Comment by SalmonSays** [comment]
It's finally dawning on me after nearly an hour of messing around with this application that the folder naming scheme is configured to be very literal with respect to sample expectations- for example "gba" as a  real folder name, rather than shorthand. I personally think this is a bad design, as it limits human readability and traversability inside a human-centric filesystem. The following scenario:


![kkZdZ9F](https://github.com/zurdi15/romm/assets/11697389/9bfda4d6-3fe6-46ca-a361-ddfe9b81f757)


should scan/import correctly without further edits, for example. Even if fuzzy matching is too complex to implement on short notice, at least let us manually match folders to their corresponding expectations.

**Comment by gantoine** [comment]
Sorry I don't fully understand, that folder setup should work just fine with a config.yml file that looks like this:

```yaml
system:
  platforms:
    'Nintendo 3DS': '3ds',
    'Nintendo 64': 'n64',
    'Nintendo DS': 'nds',
    ...
```

Could you try setting that up and let me know how it goes? The reason we require exact slugs matching IGDB is not only for scanning purposes, but eventually for emulation/emulator matching and sync-with-device functionality.

**Comment by oscruise** [comment]
Thanks for the reply Antoine. I could now figured out. At first, I skipped the mapping of the config.yml file in docker since it was not automatically created by romm and it ended up with error of file not existing. I created the file based on your example, tested it and it worked on the example parameters. However, when I edited the file with my correct mapping, it did not update scrapping rules until I deleted my database, then it worked. I guess maybe just a restart could have done it, but the thing is that it is working now. Is the config.yml file refreshed and reloaded on restart? 
Maybe then the feature request is to do all of this in the UI to make it simple to the average user.

**Comment by gantoine** [comment]
> Is the config.yml file refreshed and reloaded on restart?

It should be, but to be honest we haven't spent a ton of time testing the config file, and edge cases like these are bound to happen. I'm glad to hear you got it working in the end!

> Maybe then the feature request is to do all of this in the UI to make it simple to the average user.

There's no doubt we'll eventually have a way to configure setup via the UI (or maybe a CLI tool you run before starting RomM), but at the moment this is the best we have. As self-hosted software this project does require a decent amount of know-how (docker, volume mounts, env variables, api keys, etc), more so then something like pi-hole.

**Comment by rodrigorodrigo** [comment]
please consider i'm not trying to be a jerk while reading this:

but since v1.5 romm claims to be "EmuDeck folder structure compatible" when in fact it isn't; I haven't touched the default configuration, and these folders are not recognized. 
Perhaps adding a .yml file specific for Emudeck (and RetroDeck, and so on) would be sufficient. When I have time I'll try something like that in the following days and will get back at this post

**Comment by gantoine** [comment]
> perhaps adding a .yml file specific for Emudeck (and RetroDeck, and so on) would be sufficient

Hmmm that's not a bad idea, we'll need to spend some time working on the defaults/wiki in the new year. It's "compatible" in that the folder structure supported by romm `/roms/<platform>/<games>` is also the default in Emudeck (a flat list of platforms), as opposed to something like `/roms/<platform>/<emulator>/<games>` or some other configuration.

In the next few months I hope to start working on a system that auto-syncs with your devices, at which point romm will explicitly know the folder structure of populat platforms (libretro, emudeck, retrodeck, onion, garlic, etc.). Hope that clarifies things!

**Comment by crispybegs** [comment]
found this thread as i recently set up batocera, and its folders / names are different to romm (which i set up ages ago).
what's my best path forward here if i want to set up romm from scratch again and point it at my batocera library on a different machine, and have it recognise all the correct folders etc?

**Comment by gantoine** [comment]
wait until we've build our platform sync system (which will include batocera), or reconfigure your roms folder to match romm's expectations

**Comment by crispybegs** [comment]
> wait until we've build our platform sync system (which will include batocera), or reconfigure your roms folder to match romm's expectations

oh amazing, thanks. i'll wait for the romm update. any idea on a timeline for that?

**Comment by gantoine** [comment]
> any idea on a timeline for that?

3-6 months to get a basic system in place, then we need to start adding support for each platform/device.

**Comment by crispybegs** [comment]
> > any idea on a timeline for that?
> 
> 3-6 months to get a basic system in place, then we need to start adding support for each platform/device.

terrific, thanks!
