### ISSUE TITLE
[Feature] Add 'Rescan Unidentified' function

### ISSUE THREAD

**Issue by Span24** [zurdi15/romm#519]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a function to the scan section to scan only those existing titles which were not identified previously.  This would allow to refresh titles added to idgb after initial import.

![image](https://github.com/zurdi15/romm/assets/50145815/00b29e9c-3576-4b9d-9808-040840454e31)

**Comment by zurdi15** [comment]
I truly like this one!
