### ISSUE TITLE
[Bug] "File not found" exception while downloading multi-file roms which filenames include comma characters

### ISSUE THREAD

**Issue by mvicomoya** [zurdi15/romm#520]
**RomM version**
2.1.0 _(Latest docker image from `zurdi15/romm`, which at the time of this report is pointing to 2.1.0)_

**Describe the bug**
Trying to download any multi-file rom which filenames include a comma character results in a file not found exception, leading to downloading an empty (0 Bytes) zip archive.

The problem with multi-file roms is that the code will generate a `download?files=[comma-separated list of filenames]` API request, so if the filenames themselves include a comma, the code will just believe they are separate files.

There are many roms out there with names such as `Lion King, The (Europe) (En,Fr,De).gb`.

**To Reproduce**
1. Have a multi-file rom in your library which filename(s) include commas. E.g.:
```
$ ls -l gbc/Legend\ of\ Zelda\,\ The\ -\ Link\'s\ Awakening\ DX/
total 1024
-rw-r--r-- 1 mvicomoya mvicomoya 1048576 Dec 24  1996 'Legend of Zelda, The - Link'\''s Awakening DX (USA, Europe) (Rev 2) (SGB Enhanced) (GB Compatible).gbc
``` 
2. Go to the details page of the corresponding rom
3. From the "Files" dropdown, select 1 or more files
4. Click the "Download" button under the rom's poster

**Expected behavior**
A zip archive including the selected files should be downloaded.

**Screenshots**
N/A (let me know if you really need screenshots)

**Desktop:**
 - OS: Linux 6.6.8-arch1-1
 - Browser: Chrome
 - Version: 120.0.6099.129 (Official Build) (64-bit)

(Happens with any browser on any device, really)

**Additional context**
N/A.

**Comment by mvicomoya** [comment]
@zurdi15, I ran into this issue and dive into the code to see if it was trivial to fix (like URL-encoding the filenames or something like that). However, although not too complicated, I think it might require more than a couple of lines of code and some unit tests.

Let me know if you'd want me to pull more info about this issue or whether you want me to test some potential fix.


Great project you've created here by the way!!

**Comment by zurdi15** [comment]
Oh, I didn't ran into this isu¡sue before, good catch. We'll try to fix it and add it to a new ``rc`` build. I'll ping you to test it then :)

Thank you!!
