### ISSUE TITLE
Config File Editing + Docker on unRAID

### ISSUE THREAD

**Issue by joshmans** [zurdi15/romm#528]
**RomM version**
2.1.0

**Describe the bug**
If I modify the config file I have to remove the image or else the docker image just stops shortly after starting.

**To Reproduce**
1. Stop Container
2. Edit config.yml file
3. Start Container
- Container will run for up to a minute then just stop, after having grabbed new twitch tokens. No additional logs present.  This also causes the database of scanned/detected roms to be wiped out and having to start over.

**Expected behavior**
Container should remain started and accessible

**Comment by joshmans** [comment]
Those actions do NOT solve it - I still have to completely remove the container and re-add it.

**Comment by joshmans** [comment]
I have.. it hangs right after grabbing the new twitch token regardless of how I stop/start.

**Comment by gantoine** [comment]
> [Error 98] Address in use

That's your issue and it's been fixed in the latest RC. If you're willing to try it (and able to), you can switch to [dev-2.1.1-rc.4](https://hub.docker.com/layers/zurdi15/romm/dev-2.1.1-rc.4/images/sha256-25524a5d546983d24a2e8f1b13b26f3d80587acbc57ac8b9a736eef86b60054d?context=explore) which has a fix for this bug.

**Comment by joshmans** [comment]
> So, when its working does it look like the top screen but after a STOP/EDIT/START looks like the bottom? ![RomM STOPSTART](https://private-user-images.githubusercontent.com/50145815/293286198-d02017d8-736f-4746-bfb1-7fe38f35cf13.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTIiLCJleHAiOjE3MDM4MDUwMjYsIm5iZiI6MTcwMzgwNDcyNiwicGF0aCI6Ii81MDE0NTgxNS8yOTMyODYxOTgtZDAyMDE3ZDgtNzM2Zi00NzQ2LWJmYjEtN2ZlMzhmMzVjZjEzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDIzMDUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYjgyMjJkNDQ3MzE1NmUyYWJhN2E2MjMwYzBjNGY5MjlhYTRhZmFlMTRmY2Q4YTRlMTQ0MmY0MTk2MTEwMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PeqCh-fvUuffxQf7R4eBL_eiFTz2ScfS7nOEvjlHRmM)

No.  I don't get the "Error 98" at all.  Mine fetches a new token and then just stops.

**Comment by gantoine** [comment]
> What is Error 98 telling us?

That romm is trying to bind to a port that's already in use. The fix in the latest RC makes sure the port is unbound before restarting/dealing with a crash.

> Also, when will this fix be available to UnRaid Docker?

Likely in the next minor version release, though I don't have a date for that yet.

**Comment by zurdi15** [comment]
Does anyone have news about if this still happens in the last release?
