### ISSUE TITLE
[Feature] Multiple discs organization

### ISSUE THREAD

**Issue by djlobster** [zurdi15/romm#533]
**Is your feature request related to a problem? Please describe.**
I have a lot of games with multiple discs and a large library so I'm seeing a lot of what looks like duplicate entries that take up space and there's no indication of which is which unless I mouse over the download button or click on them to open the page for that disc (which I have tagged as Disc 1 or Disc 2).

**Describe the solution you'd like**
I'd like it if instead of multiple entries, there is only one. You could press the download button and it would give you a list (Disc 1, Disc 2, Disc 3, etc).

**Describe alternatives you've considered**
Another alternative would be to have something on the graphic, like in the bottom left corner, that says CD1 or CD2 if there are more than one. I don't like this because it doesn't solve the large library and lots of space being taken up issue, but it would be better than nothing.

**Additional context**
This is an example, two games with 2 discs. I would rather they each only take up one space.
![image](https://github.com/zurdi15/romm/assets/12630047/7e8243f7-b19c-4ebc-987b-2a296b7db089)
Another example, two games, but they take up 9 spots in the library
![image](https://github.com/zurdi15/romm/assets/12630047/abf29c7e-3c47-4b7d-a6d9-3ec300abf7b5)

**Comment by gantoine** [comment]
Rom expects multi-disc games to be placed under a single folder, like so:
```
- roms
  - ps
    - BatenKaitos
      - Disc1.iso
      - Disc2.iso
```

Move them all into folders and run a complete rescan, it should then work as expected.
