### ISSUE TITLE
[Bug] Platform not found

### ISSUE THREAD

**Issue by karl0ss** [zurdi15/romm#535]
**RomM version**
2.1.0

**Describe the bug**
Struggling to work out the correct mapping for a bunch of platforms on IGDB

**To Reproduce**
1. Create folder structure
2. Scan with files in folders

**Expected behavior**
Platform should be added

**Screenshots**
```
INFO:	  [RomM][2023-12-31 10:00:48] · PS2
INFO:	  [RomM][2023-12-31 10:00:49]   Identified as PlayStation 2 🎮
INFO:	  [RomM][2023-12-31 10:00:49] · PSP
INFO:	  [RomM][2023-12-31 10:00:50]   Identified as PlayStation Portable 🎮
INFO:	  [RomM][2023-12-31 10:00:50] · Sega 32X
WARNING:  [RomM][2023-12-31 10:00:51]   Sega 32X not found in IGDB
INFO:	  [RomM][2023-12-31 10:00:51] · Sega CD
WARNING:  [RomM][2023-12-31 10:00:52]   Sega CD not found in IGDB
INFO:	  [RomM][2023-12-31 10:00:52] · Sega Saturn
WARNING:  [RomM][2023-12-31 10:00:53]   Sega Saturn not found in IGDB
INFO:	  [RomM][2023-12-31 10:01:08] · X360
WARNING:  [RomM][2023-12-31 10:01:09]   X360 not found in IGDB
```

Have checked on IGDB and have used both the "Name of the system" for example "Xbox 360" but it couldn't map that, and I also tried with the alternative name "X360" as stated on IGDB, but it doesn't appear to be found, not tooo sure what I am doing wrong...
![image](https://github.com/zurdi15/romm/assets/2493260/c33fcbb7-b32f-41ae-a11d-618e681fd361)

hope someone can help

**Comment by zurdi15** [comment]
Hi! Yeah this may be a little bit confusing, we are working in a better documentation for new users. You need to name your folders like the slug that appears in the ``url``, in this case, your ``Xbox360`` folder should be ``xbox360``.

Another approach if you don't want to change your folder names is to use the [config.yml file](https://github.com/zurdi15/romm/blob/9eafa6def21151f94fac58b5b22f2132fc4ed20d/examples/config.example.yml#L34) to map your folders to the IGDB ``slugs``

**Comment by karl0ss** [comment]
ah, wicked, thanks alot @zurdi15 :)
