### ISSUE TITLE
[Bug] Search by name doesn't work

### ISSUE THREAD

**Issue by JamesDAdams** [zurdi15/romm#536]
**RomM version**
dev-2.2.0-rc.1

**Describe the bug**
The IGDb search by name doesn't work for PS4, QUEST...

**To Reproduce**
4. search in IGDb for a game
5. No results found

**Expected behavior**
retrieve a list to select my game

**Screenshots**
<img width="691" alt="image" src="https://github.com/zurdi15/romm/assets/20860324/a9ae65ee-977e-4ce2-ade0-9a19f71f4e17">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Version 1.61.109

**Additional context**

**Comment by gantoine** [comment]
Seems to work fine for that search term in ps4, make sure the PS4 platform is detected correctly.

<img width="1224" alt="Screenshot 2023-12-31 at 12 14 56 PM" src="https://github.com/zurdi15/romm/assets/3247106/abb4bf06-eccc-442a-a3b7-8b13a4002f1f">

**Comment by zurdi15** [comment]
Also update your image to the last ``v2.2.0`` if possible :)
