### ISSUE TITLE
[Feature] Global Search

### ISSUE THREAD

**Issue by Jinorex** [zurdi15/romm#547]
**Is your feature request related to a problem? Please describe.**
Since RomM is inspired by various media systems such as JellyFin, I think a global search is quite helpful and a QoL improvement.
At the moment you can only search in the platform. So if I do not know the platform I have to search in another programm/tool.
For example in the [IDGB Search for Pokemon](https://www.igdb.com/search?type=1&q=pokemon)

**Describe the solution you'd like**
If more than one platform is found, we could separate them by platform name:

![image](https://github.com/zurdi15/romm/assets/35707423/7c17e1b1-86f5-4659-aca9-847039a871af)

Another approach would be to display the appropriate platform icon as a tag and show all roms together without separating them.
![image](https://github.com/zurdi15/romm/assets/35707423/6b7108c6-c6a5-434f-a478-c8bf55b0077e)

**Comment by bfenty** [comment]
This is a great idea, I like the first option of sectioning the results. I'd definitely like the option to find all my Pokemon or Star Wars games, across all platforms, for instance.

**Comment by zurdi15** [comment]
@bfenty @Jinorex #612 😄

**Comment by Jinorex** [comment]
@zurdi15 nice one! This looks very good!
