### ISSUE TITLE
[Feature] Savefiles/states management

### ISSUE THREAD

**Issue by zurdi15** [zurdi15/romm#55]
**Is your feature request related to a problem? Please describe.**
Posibility to manage (download and upload) different savefiles/states for each game

**Comment by XargonWan** [comment]
Suggestion: set in the config a path for state files and a different one for save files.
Romm should check these folders and match the save name with the game name (usually they are the same).

When a game is renamed it asks to rename even the save files prompting the user a preview of the new names.

**Comment by Casuallynoted** [comment]
This appears to be resolved in 3.0.

**Comment by zurdi15** [comment]
> This appears to be resolved in 3.0.

Finally yes! 😄
