### ISSUE TITLE
[Feature] PS2 icon too dark

### ISSUE THREAD

**Issue by crispybegs** [zurdi15/romm#56]
this is a tiny, cosmetic point, but anyway - the PS2 icon is pretty invisible when using the dark theme. Would be nice to have a more visible one at some point in the future

<img width="299" alt="Screenshot 2023-03-28 at 18 38 57" src="https://user-images.githubusercontent.com/129169122/228323004-b87351a8-3fea-4677-aebc-c72d9a156e6f.png">

**Comment by zurdi15** [comment]
I know my messy job about platforms icons (I used free-copyright icons), so I wanted at some point to redesign all of them with someone that knows how to do it as my design skills are not so powerfull. Agree with the ps2 icon thought.

I'll keep this open as a reminder to make more beautiful icons set

**Comment by zurdi15** [comment]
I am closing this as I made a full rework in the icons. In any case, still thinking in a way of making the dark icons more visibles.
