### ISSUE TITLE
Added Admin User, But After Restart I'm Getting "Unable to login: CSRF token verification failed"

### ISSUE THREAD

**Issue by gantoine** [zurdi15/romm#560]
From @Budlyte

Hello,
I setup RomM in Unraid and got my Twitch dev login put in. I noticed that the app by default didn't have any users setup, and I couldn't change any settings, besides grouping multiples.  So I added the below variables to my install:

ROMM_AUTH_ENABLED: true
ROMM_AUTH_USERNAME: user
ROMM_AUTH_PASSWORD: password

Then relaunched the application and was able to login with my admin account. But I still couldn't change any settings, and scanning just shows my platforms but doesn't do anything else, so I restarted the container again.

Now I'm getting the error "Unable to login: CSRF token verification failed" on the login screen.</div>

**Comment by gantoine** [comment]
Read the wiki on authentication and make sure you follow the text under "enabling authentication" https://github.com/zurdi15/romm/wiki/Authentication#enabling-authentication

**Comment by Budlyte** [comment]
Thanks. 
I followed the guide, but I'm still stuck on that same error.

We can see here that Redis is reachable on 192.168.1.202:6379
![image](https://github.com/zurdi15/romm/assets/4451365/45517352-baa9-4f49-af4a-3431ece52c15)
![image](https://github.com/zurdi15/romm/assets/4451365/3fbfba97-848a-4a06-bc16-d1d01f0efcb3)

But here's my RomM setup to reach it, and I'm still getting the same error.
![image](https://github.com/zurdi15/romm/assets/4451365/03cd6610-c63e-4a36-910f-5e64e9aa130e)

If I change the REDIS_HOST to "localhost" then the app skips the login screen and opens up, but I can't do anything. I think this means that with the IP in the config that it is correctly reaching Redis.

**Comment by zodac** [comment]
I am also having the same "Unable to login: CSRF token verification failed" error, similar configuration to @Budlyte above.

![image](https://github.com/zurdi15/romm/assets/2502611/4ecb7a7b-5e8c-4d90-b268-b7da50b776e7)

This was using Google Chrome. However, if I test it on Firefox, it does seem to work fine. Unsure if there's some extra config needed for Chrome?

Not going through any reverse proxy, just connecting over localhost (though I have mapped the external port to something other than 8080).

**Comment by zurdi15** [comment]
This sometimes happens to me aswel but I don't know why it is happening. Clearing cookies should work.

**Comment by gantoine** [comment]
> This was using Google Chrome. However, if I test it on Firefox, it does seem to work fine.

I see the same behavior on Chrome, and it often takes a manual clearing of cookies and a hard reload (CMD+R/CTRL+R) to fix it (though sometimes it doesn't work the first time).

**Comment by zurdi15** [comment]
> > This was using Google Chrome. However, if I test it on Firefox, it does seem to work fine.
> 
> I see the same behavior on Chrome, and it often takes a manual clearing of cookies and a hard reload (CMD+R/CTRL+R) to fix it (though sometimes it doesn't work the first time).

I am realizing that this is true, never happened to me in Opera

**Comment by Casuallynoted** [comment]
Worth mentioning that this is almost definitely a symptom of Romm being very intense about caching. I've tried running the PWA on my phone but always run into this exact CSRF error with no way to clear cookies because it's cached so much. Is there a way that admins might be able to adjust caching times for the app? (Not intending to hijack this issue but thought it was worth mentioning, can always make another issue too if it's better to do that)

**Comment by zurdi15** [comment]
> Worth mentioning that this is almost definitely a symptom of Romm being very intense about caching. I've tried running the PWA on my phone but always run into this exact CSRF error with no way to clear cookies because it's cached so much. Is there a way that admins might be able to adjust caching times for the app? (Not intending to hijack this issue but thought it was worth mentioning, can always make another issue too if it's better to do that)

Definitely we need to take a look into this

**Comment by Jaonea** [comment]
Also on Unraid. For some reason what worked for me was not adding the username and password variables and then using the default admin/admin to log in and create the desired user manually.

**Comment by zurdi15** [comment]
> Also on Unraid. For some reason what worked for me was not adding the username and password variables and then using the default admin/admin to log in and create the desired user manually.

Oh wow really? And you didn't have any problem over the days?

**Comment by Jaonea** [comment]
Still day 1 but have to delete/reset the cache sporadically. What this helped with is getting in the first place. 
Until deleting those two variables I was not able to log in at all with the error given "Unable to login: CSRF token verification failed" no matter the platform or browser. My experience is probably more related to #502 .

**Comment by Jaonea** [comment]
After roughly a week I have now logged out and tried logging in again without any issues. Please let me know if you want me to do any specific tests.

**Comment by gantoine** [comment]
@Jaonea for the upcoming 3.0 release we're making changes to caching that should 🤞🏼 stop this CSRF issue

**Comment by Casuallynoted** [comment]
Appears to truly be fixed as of 3.0!! Thank goodness haha

**Comment by zurdi15** [comment]
Yeah CSRF have been a pain in the ass 🤣

**Comment by PhuriousGeorge** [comment]
Sorry to disrupt the party, but fresh install and getting the same CSRF error.  Works on Firefox, but not on Chrome (Brave or Vivaldi).

**Comment by gantoine** [comment]
Damn, and does clearing cookies do anything?

**Comment by PhuriousGeorge** [comment]
Nope, I've tried every trick I can think of and can't get either of those Chromium browsers to work

**Comment by gantoine** [comment]
Ok try these 2 things in order:

* Stop and **rm** the romm container, **manually** clear cookies and cache, then try logging in again
* Add `DISABLE_CSRF_PROTECTION=true` to your environment variables and restart romm

**Comment by PhuriousGeorge** [comment]
Step 1 didn't change anything.
Step 2 worked.

**Comment by gantoine** [comment]
And that's why we added that env variable, glad to hear it worked! With CSRF disabled we strongly suggest we don't expose RomM to the wider internet.

**Comment by PhuriousGeorge** [comment]
I didn't even realize that variable was an option.  Personally okay by me, I have no intention of exposing past my LAN.  Thanks.  Wish I knew more about the tech to help; I imagine you're going to hear about CSRF a lot.

**Comment by gantoine** [comment]
We heard about it a lot in 2.x, and we made some changes in 3.0 that change how CSRF headers are set on requests. It has reduced the number of issues, but unfortunately not eliminated them.

**Comment by ktfcaptain** [comment]
Just FYI - I had this error and read down to someone mentioning switching to Firefox to resolve.  I was using Firefox already so switched to Chrome and had no issue logging in, for whatever that's worth....
