### ISSUE TITLE
[Bug] Some platforms are not picked up by Webrcade

### ISSUE THREAD

**Issue by Casuallynoted** [zurdi15/romm#564]
**RomM version**
2.2.1

**Describe the bug**
If you add a Romm feed, some platforms will be detected and their games will be added, but others will be detected as having 0 games when they do have games in Romm.

**To Reproduce**
1. Add a feed to Webrcade that has games from a platform this issue is happening to (list below)
2. Does not show in Webrcade
3. Check the Webrcade feed editor and import Romm feed
4. Shows, but has 0 games

**Expected behavior**
Ideally, all platforms that work with webrcade should be detected.

**Screenshots**
![Screenshot_20240102_193602](https://github.com/zurdi15/romm/assets/6272557/4889d7fb-cbb2-4782-8b86-e632cda14e71)

**Additional context**
Platforms that demonstrate this issue on my end:
3DO
Atari 5200
Colecovision
Nintendo 64
Neo Geo CD
PlayStation
Sega CD
WonderSwan
WonderSwan Color

Platforms that are detected properly:
Arcade
Atari 2600
Atari 7800
Sega Game Gear
Game Boy
Game Boy Advance
Game Boy Color
Sega Mega Drive/Genesis
Atari Lynx
Neo Geo Pocket
Neo Geo Pocket Color
Neo Geo AES
NES
Sega Master System
SNES
PC Engine Super Grafx
Turbografx 16
Virtual Boy

**Comment by gantoine** [comment]
Closing this as it's a webrcade bug, try your luck opening an issue there (though they're fairly slow to respond).
