### ISSUE TITLE
[Feature] Support for 'platform subversions'

### ISSUE THREAD

**Issue by Span24** [zurdi15/romm#569]
Is your feature request related to a problem? Please describe:
The naomi-2 slug is a 'version' of the 'arcade' platform.  as in /arcade/version/naomi-2.  RomM is currently unable to handle this ''subversion' of arcade?

Describe the solution you'd like:
RomM should support platform 'subversions' so that users can separate rom platform subtypes

![image](https://github.com/zurdi15/romm/assets/50145815/9582cb9c-590d-464d-b88c-fe098cd6f2ef)

**Comment by Casuallynoted** [comment]
This may also serve as an inadvertent solution to IGDB's weird separation of both NES/Famicom and SNES/Super Famicom as being their own platforms, as well as IGDB's classification of the iQue Player as being a variant of the N64.
