### ISSUE TITLE
[Feature] Add more metadata to game details page

### ISSUE THREAD

**Issue by zurdi15** [zurdi15/romm#57]
**Describe the solution you'd like**
Add more useful metadata, like publisher, release date, etc to the game details page

**Comment by XargonWan** [comment]
Media side suggestions:
Screenshots, cover, medium (cartdrige/disk image), wheel.

**Comment by XargonWan** [comment]
Data side suggetsion:

![image](https://user-images.githubusercontent.com/6771419/235149672-2783682f-8bf4-4eb8-a04d-5aeaba5dd014.png)

**Comment by Afaren57** [comment]
Could be nice to also sort or filter with this additional metadata. E.g. sorti titles by date or filter by a development studio or specific publisher

**Comment by Casuallynoted** [comment]
As of 3.0, this appears to have been done! ^_^

**Comment by zurdi15** [comment]
> As of 3.0, this appears to have been done! ^_^

True, I was wondering if at some point we will add more, but I am happy enough with the current state to close this :)
