### ISSUE TITLE
[Feature] Add wildcards to config.yml

### ISSUE THREAD

**Issue by jiannazzone** [zurdi15/romm#575]
Since I sometimes access my NAS via MacOS, my ROM folders sometimes get `_.` sidecar files added by the operating system. RomM sees these files and includes them with the main ROM (see screenshot).

![Screenshot 2024-01-06 185051](https://github.com/zurdi15/romm/assets/46025473/82213277-4c4a-47b2-892b-06a6773a2e03)

I would like to be able to add `_.*` in my `config.yml` and exclude all such files.

**Comment by gantoine** [comment]
Nice and quick https://github.com/zurdi15/romm/pull/576
