### ISSUE TITLE
[Bug] Romm serving ~500mb webpage downloads instead of ROM files

### ISSUE THREAD

**Issue by Casuallynoted** [zurdi15/romm#581]
**RomM version**
dev-latest

**Describe the bug**
Lately, when I've gone to download files from my Romm instance, it'll spit out a between 500-700ish mb file containing this:

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<link rel="icon" href="/favicon.ico" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>RomM</title>
<script type="module" crossorigin src="/assets/index.9d6b43e3.js"></script>
<link rel="stylesheet" href="/assets/index.7ad7edb8.css">
<link rel="manifest" href="/manifest.webmanifest"><script id="vite-plugin-pwa:register-sw" src="/registerSW.js"></script></head>
<body>
<div id="app"></div>
</body>
</html>

It has the name and extension of what I'm trying to download but definitely isn't it.

So far, I've determined that it seems to happen sometime after the app is started (if I restart it does seem to go away for a while if I've cleared my browser cache/cookies) and doesn't seem to be specific to any browser/OS. I've also double checked that Cloudflare isn't interfering with this by disabling all CF caching/proxying features while testing. It also doesn't seem to have anything to do with the download being a single or multi file rom.

**Additional context**
Previously discussed in the Discord thread here:
https://discord.com/channels/1138838206532554853/1193393278842839142

**Comment by gantoine** [comment]
This is likely also a symptom of the PWA thing you mentioned in the other issue. I think relaxing how hard romm caches assets should help things quite a bit.

**Comment by gdiazbanuelos** [comment]
Are you using Firefox? I had the same issue and I tried Chrome and Edge and it downloaded fine. I am not sure if this is something that can be fixed or if it is just a Firefox limitation on how it handles downloads.

**Comment by Casuallynoted** [comment]
I am, but I’ve had the same issue on chrome as well, and I can say Romm used to work perfectly with Firefox. The issue also happens with Safari.

**Comment by gantoine** [comment]
Closing in favor of #630
