### ISSUE TITLE
[Other] iPhone rendering issue

### ISSUE THREAD

**Issue by crispybegs** [zurdi15/romm#59]
not sure why this would be the case, but my Romm instance renders perfectly on iphone in chrome, but is totally blank when opening with safari

**Chrome**

![IMG_63A22AC015CA-1](https://user-images.githubusercontent.com/129169122/228330884-9488fe2d-8e90-4304-94b2-b4aa44c1a1fc.jpeg)

**Safari**

![IMG_0EB4471A9861-1](https://user-images.githubusercontent.com/129169122/228330985-cd97194f-bdb8-425a-b2a2-25b015a349e1.jpeg)

**Comment by DebugDax** [comment]
I'm not having this issue with Safari on an iPhone 14, iOS 16.4.

Can you tap the "aA" at the top left of Safari and then try tapping "Turn off Content Blockers".
Also, maybe try declaring specifically it as http://192.168.x.x, I don't have to but I see in Chrome you get the (!) but in Safari it should say "Not Secure" to show it's loading it as http and not https.

**Comment by crispybegs** [comment]
> I'm not having this issue with Safari on an iPhone 14, iOS 16.4.
> 
> Can you tap the "aA" at the top left of Safari and then try tapping "Turn off Content Blockers". Also, maybe try declaring specifically it as http://192.168.x.x, I don't have to but I see in Chrome you get the (!) but in Safari it should say "Not Secure" to show it's loading it as http and not https.

I can't see an option for turning off content blockers in any menu / submenu. 
I tried specifying the http:// as well but it made no difference.
Also tried requesting as desktop site but that also made no difference.

**Comment by zurdi15** [comment]
I am sorry, as I don't have an iPhone and can't access to anyone I can't help with this, but indeed seems to be iphone/safari related.
Hope someone else can help with this :(

**Comment by crispybegs** [comment]
not a problem! i was only opening it in safari as i would have then been able to add RomM as an icon of it's own to my homepage, but no big deal!

**Comment by fatflyingpigs** [comment]
I'm using an iPhone X, v15.7.1 and I don't have this issue; it renders fine on both safari and chrome

**Comment by crispybegs** [comment]
> I'm using an iPhone X, v15.7.1 and I don't have this issue; it renders fine on both safari and chrome

oh i forgot to update this thread earlier. 
after a couple of days of this not working, out of frustration i hammered the refresh button and then suddenly this evening it srpang into life and loaded! no idea why it was being so difficult but it worked and i was able to add it to my homescreen. Just need to figure out how to give it a nice icon now.

![IMG_12350E735D6E-1](https://user-images.githubusercontent.com/129169122/228971675-fc03ee2f-bfe2-4b79-82b3-9ee6c75ad000.jpeg)

**Comment by crispybegs** [comment]
fixed, somehow
