### ISSUE TITLE
[Bug] Odd sorting for game list

### ISSUE THREAD

**Issue by bricas** [zurdi15/romm#591]
**RomM version**
2.3.1

**Describe the bug**
After a discussion on discord I was led to believe the default sort list for games is alpha by filename. I don't think that's what I'm seeing.

**Screenshots**
File list:
![files](https://github.com/zurdi15/romm/assets/18400/993e7190-5104-49d3-83e7-a8507a512457)
Grid view:
![grid](https://github.com/zurdi15/romm/assets/18400/1c6e90d0-0879-4f89-a9d9-8cab06b04c9d)
List view:
![list](https://github.com/zurdi15/romm/assets/18400/0089d31c-b7cb-461a-99e2-17859a5a978c)

**Comment by gantoine** [comment]
This has been addressed in 3.0, where roma will be sorted both on the backend and frontend for consistency. Keep an eye out for the next release candidate if you want to try it early.
