### ISSUE TITLE
[Feature] Manually add artwork/description

### ISSUE THREAD

**Issue by bfenty** [zurdi15/romm#592]
**Is your feature request related to a problem? Please describe.**
If IGDB doesn't have an entry for an item, there's no way to get screenshots or a cover

**Describe the solution you'd like**
Manually uploading cover and editing title and description

**Comment by gantoine** [comment]
You can do that already when editing a game, right at the bottom of the modal

<img width="913" alt="Screenshot 2024-01-09 at 3 04 07 PM" src="https://github.com/zurdi15/romm/assets/3247106/ebdddc02-b843-4540-8062-1aa74f63d40a">
