### ISSUE TITLE
[Feature] make games with multiple regions and revisions appear under one entry

### ISSUE THREAD

**Issue by victor10100111001** [zurdi15/romm#60]
It would be cool if the program was able to put different regions and revisions under one game entry. Currently games with multiple regions and revisions have multiple game entries. Some examples of different regions and revisions could be:
-Zelda no Densetsu - Yume o Miru Shima (Japan) (Rev 1).gb
-Zelda no Densetsu - Yume o Miru Shima (Japan).gb
-The Legend of Zelda: Link's Awakening (Europe).gb
I think these should be under the same game entry and then when you click on the game you should be able to choose which revision and region you would like to download. Maybe there should also be a "default" download button, where it chooses a prechosen region (that you can set in the settings) and the latest revision.

**Comment by zurdi15** [comment]
RomM now supports regions and revisions, as well as other generic tags. [v1.5](https://github.com/zurdi15/romm/releases/tag/v1.5)

I didn't decide yet if different region games should be under the same detail page or in different, as other approach is to have multiple covers for each region in the gallery.

I am closing the issue until i decide what to do, for now you can enjoy your new regions/revision tags
