### ISSUE TITLE
[Bug] No pagination when browser window is set to 'maximized'

### ISSUE THREAD

**Issue by sonofmartinus** [zurdi15/romm#617]
**RomM version**
2.3.1

**Describe the bug**
Noticed that console page was not paginating when browser window is set to 'maximized'. It will load 35 tiles and no matter how much you scroll with your mouse wheel it will not load further pages. I may note that this only happens in the 'default' sorting and it only happens on first load of collection. If you toggle through sorting then pagination works fine in a 'maximized' window. The only way to get it to paginate is to change the sorting within RoMM or changing browser size to where the browser scrollbar appears. Screenshot attached.

**To Reproduce**
1. browse to RoMM site
2. click on console collection while having a maximized browser window
3. pagination will not work no matter how much you scroll

**Expected behavior**
Paginate while maximized browser window on first load

**Screenshots**

![firefox_WmEF6GiqmQ](https://github.com/zurdi15/romm/assets/152257537/6732db3a-8f3e-4e6d-b392-9a5e0efb100c)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Firefox 
 - Version: 121.0

**Smartphone (please complete the following information):**
I believe this wouldn't apply on mobile but have not tested.

**Comment by Casuallynoted** [comment]
You know, I've run into this too! At first I thought it was just me. It doesn't happen every time for me but definitely has happened.

**Comment by zurdi15** [comment]
Oh wow this is a very specific behaviour, good catch, i'll check it

**Comment by gantoine** [comment]
OK I have a fix for this, will be available in the 3.1 release!
