### ISSUE TITLE
[Feature] EmulatorJS integration

### ISSUE THREAD

**Issue by Seruschl** [zurdi15/romm#622]
Using [EmulatorJS](https://github.com/EmulatorJS/EmulatorJS) on a regular base i think it could be a good feature to have an integration so that you are able to play the games right from Romm in your Browser.

**Comment by zurdi15** [comment]
Hi! There is an issue already for that #95 , and you would like to know that we are already developing it!

Keep an eye for the next release 👀

**Comment by Seruschl** [comment]
thanks for the information. I've missed that issue. Keep looking forward to this and thanks for this great project
