### ISSUE TITLE
[Bug] Downloading Rom (Firefox) yields a 1KB file

### ISSUE THREAD

**Issue by sonofmartinus** [zurdi15/romm#630]
**RomM version**
2.3.1

**Describe the bug**
Downloading Rom (zipped) files from Firefox download a 1KB corrupted file. Works fine in Chrome and Edge.

**To Reproduce**

1. Using Firefox, browse to RomM site
2. Pick a Rom and click the download control
3. Browser will download a 1KB corrupted 'Rom' file.

**Expected behavior**
Compressed Rom file should download and be able to expand (unzip).

**Screenshots**

![issue](https://github.com/zurdi15/romm/assets/152257537/67443579-9f9f-497e-92ca-46beac4be625)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Firefox 
 - Version: 121.0.1

**Smartphone (please complete the following information):**
Have not tested from Smartphone

**Additional context**

**Comment by gantoine** [comment]
We're aware of the issue, and we've made some changes for the upcoming 3.0 release that should reduce the chances of this happening. In the meantime you can try clearing your cache and removing the service worker in Firefox.

**Comment by zurdi15** [comment]
> Should be fixed as of 3.0 (so happy about this haha) :P

Did you verify it?

**Comment by Casuallynoted** [comment]
> > Should be fixed as of 3.0 (so happy about this haha) :P
> 
> Did you verify it?

Yes! :D For me, it's worked perfectly!
