### ISSUE TITLE
[Bug] troubles on download speed

### ISSUE THREAD

**Issue by ufoccjipo7** [zurdi15/romm#631]
I have set up ROMM on my NAS using docker, and everything is functioning properly. However, the download speed is significantly lower than when directly downloading from the NAS itself. My local network speed limit is 100MB/s, and I can reach this maximum speed when downloading straight from the NAS. But when downloading from ROMM, the speed only ranges from 20MB to 30MB/s.

**Comment by gantoine** [comment]
Are you downloading single or multi-file roms? Multi-file roms are zipped on the server, so there's some processing that needs to happen there.

**Comment by ufoccjipo7** [comment]
> Are you downloading single or multi-file roms? Multi-file roms are zipped on the server, so there's some processing that needs to happen there.

Indeed, after compressing  game files to a single file, download speeds revert to normal, and hope  future RomM support to facilitate downloading multi files simultaneously.
