### ISSUE TITLE
What folder name to use for PC Engine?

### ISSUE THREAD

**Issue by crispybegs** [zurdi15/romm#635]
I have a bunch of .pce ROMs, but I'm not sure what to call the folder so they scan properly in ROMM, as there are three different PC Engine platform listings in IGDB

<img width="576" alt="Screenshot 2024-01-26 at 20 16 15" src="https://github.com/zurdi15/romm/assets/129169122/bdc5257e-a0b5-46bd-beee-ff43930ebe6d">

I tried calling the folder `turbografx-16-slash-pc-engine-cd` and the result was that the scan picked up a few games, but couldn't find the rest.

<img width="1429" alt="Screenshot 2024-01-26 at 20 14 45" src="https://github.com/zurdi15/romm/assets/129169122/3524df94-38b6-4fee-9e30-3753b8dfc880">

Any tips on how go go about fixing this?

**Comment by gantoine** [comment]
I think you want the original, **turbografx16--1**

**Comment by crispybegs** [comment]
> I think you want the original, **turbografx16--1**

you're an angel, that worked. thank you so much
