### ISSUE TITLE
[Feature] User configure of folder structure

### ISSUE THREAD

**Issue by fatflyingpigs** [zurdi15/romm#65]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could set our own folder structure. Allowing some sort of mapping schema would allow for more people to easily use this project without having to modify their existing folder structure. For example, I personally don't use a 'rom' folder like you do. I think someone mentioned something similar on the reddit thread, but I didn't see a github issue.

Personally I use the following structure:

```
library/
├─ gbc/
│     ├─ rom_1.gbc
│     ├─ rom_1.sav
│     ├─ rom_1.sav1
│     ├─ rom_2.gbc
|
├─ switch/
│     ├─ rom_1
│           ├─ rom_1.xci
│           ├─ rom_1.nsp
│     ├─ rom_2.xci
|
├─ pc/
│     ├─ game_1/
│           ├─ game_1.iso
│           ├─ game_1_patch.exe
│     ├─ game_2/
│           ├─ soundtrack/
│                  ├─ song_1.mp3
│                  ├─ song_2.mp3
│           ├─ game_2.iso
│           ├─ game_2_patch.exe
│     ├─ random1_game.iso
│     ├─ random2_game.7z
│     ├─ random3_game.rar

```

**Describe the solution you'd like**
I'd like to have a more dynamic method of linking folders/files to game entries. Additionally it could be useful to exclude certain files/folders (eg: the 'soundtrack' folder in my example above)

Appreciate you making this app and sharing it with us!

**Comment by XargonWan** [comment]
Same for me as well, my folder structure is `roms/<system>/files.ext` where `roms` is mapped as `library`.

**Comment by javijuji** [comment]
Same here. I rather have switch roms in their own game folder since sometimes I have DLCs or version updated in there as well. Throwing everything under switch/roms would just make everything a mess.

**Comment by zurdi15** [comment]
RomM is now more flexible with the folder structure! [v1.5](https://github.com/zurdi15/romm/releases/tag/v1.5)

As it is more flexible but can't define your own structure through config yet I will remain the issue open

**Comment by zurdi15** [comment]
I am updating the title to be more generic

**Comment by XargonWan** [comment]
Related: https://github.com/zurdi15/romm/issues/152

**Comment by GAntoine** [comment]
Closed as this is now supported.
