### ISSUE TITLE
[Bug] Twitch token invalid: fetching a new one...

### ISSUE THREAD

**Issue by mckls** [zurdi15/romm#665]
**RomM version**
latest

**Describe the bug**
When I start the docker container iterately the following error occurs: Twitch token invalid: "fetching a new one..."

**To Reproduce**
1. Start the container with set IGDB_CLIENT_ID and IGDB_CLIENT_SECRET environment variables.

**Comment by gantoine** [comment]
As long as it says "twitch token fetched" after that is normal and expected. If not you should check your env variables. You can mitigate this by running the redis container, which will cache your twitch token between restarts.
