### ISSUE TITLE
[Bug] Decompress Game Core

### ISSUE THREAD

**Issue by msrlrocket** [zurdi15/romm#695]
**RomM version**
3

**Describe the bug**
Trying out the new built in emulator. No matter which rom I choose, I get a black pill notification in the middle that says 'Decompress Game Core'

Through troubleshooting, I was originally getting an SSL error, so I now have it running through nginx with websocket support.

**To Reproduce**
Launch any Rom. Tried with both GBA and SNES

![image](https://github.com/zurdi15/romm/assets/66177288/df50f28a-4b5e-4342-a9c5-63a9690f9680)

**Comment by gantoine** [comment]
We're aware of the issue, and i'll be fixed in the next release (3.0.1)
