### ISSUE TITLE
Question: External Redis ? (low priority)

### ISSUE THREAD

**Issue by znoxx** [zurdi15/romm#698]
As far as I understand, redis is built-in in latest (3.x) docker images.
However, I already use Redis in my infra, and _maybe_ it will make sense to re-use existing instance, rather than running inside docker container.

Is there an option to use "external" redis, pointing it to address and disabling "built-in" one ? For sure, it breaks "simplicity" somehow and not a priority at all,  but anyway ? =).

Thanks in advance for an answer.

**Comment by gantoine** [comment]
> maybe it will make sense to re-use existing instance,

I _strongly_ recommend against using a redis instance for multiple apps, since key collisions can (and have) happened between apps, like when using background workers. Eventually we'll add the option to run redis outside of romm for those who want to do so, or need to for some config reason.

**Comment by znoxx** [comment]
Thanks for clarification!
However, using "external" redis may be just a good practice to keep romm image little bit smaller and follow docker practice "one container - one product"

**Comment by gantoine** [comment]
While I agree on principal (and why it was external in 2.x), we've received a lot of push back from users about having to run redis alongside RomM. Mainly that other tools don't require so many extra containers. Instead of thinking of it as redis, think of it as builtin-async-task-runner-for-romm! It's use should be fully transparent to most users.

**Comment by zurdi15** [comment]
Hmm while I agree with both of you, shouldn't be the best user experience to integrate it inside romm as we have it now but give the user the possibility to use a external one if desired even if it's not recommended?
