### ISSUE TITLE
[Feature] Support Alternate PUID/GUID

### ISSUE THREAD

**Issue by alexfornuto** [zurdi15/romm#700]
**Is your feature request related to a problem? Please describe.**
This is a QoL request. I admin the server running ROMM using VSCodium with a remote session as my user. Having config files and other assets/resources owned by root means I can't edit directly in my editor with my user.  

**Describe the solution you'd like**
I'd like to specify PUID and GUID for the romm container, so I can make edits to config files without dropping to the terminal to `sudo`.

**Additional context**
If you have questions about this request, LMK and I'll (try to) respond in a timely manner.

**Comment by gantoine** [comment]
Closed in favour of #516
