### ISSUE TITLE
[Feature] Add alternative rom names when scanning library

### ISSUE THREAD

**Issue by zurdi15** [zurdi15/romm#75]
**Is your feature request related to a problem? Please describe.**
Some games have different localized names so it would be nice to search for all of them when scanning  the library

**Comment by zurdi15** [comment]
As @Casuallynoted commented [here](https://github.com/zurdi15/romm/issues/637#issuecomment-1918154034), apart from supporting other sources than IGDB, IGDB itself have an alternate name field in their API that we should use.

**Comment by gantoine** [comment]
Complete!
