### ISSUE TITLE
[Feature] Option to search a game by its IGDB id

### ISSUE THREAD

**Issue by crispybegs** [zurdi15/romm#76]
Plex has the useful ability to fix occasions when a movie will stubbornly refused to find its match on IMDB by letting you search by the IMDB id instead of the movie name, like so:

<img width="617" alt="Screenshot 2023-03-29 at 11 50 48" src="https://user-images.githubusercontent.com/129169122/228511727-8927f8ad-41a7-4aa9-85d3-99f1cce8621f.png">

I have several roms which, for reasons I can't work out, refuse to be matched on IGDB so it would be useful to be able to do the same here. I see the search already drags in the IGDB id when matching.

<img width="742" alt="Screenshot 2023-03-29 at 11 50 58" src="https://user-images.githubusercontent.com/129169122/228512163-606c89e5-ceaa-40da-a656-a8d3e6c985bc.png">

**Comment by XargonWan** [comment]
Came here to ask the same

![image](https://user-images.githubusercontent.com/6771419/230406291-a6146407-bddb-450e-86eb-980b5b6175b0.png)

**Comment by zurdi15** [comment]
Added in the last release [v1.6.4](https://github.com/zurdi15/romm/releases/tag/v1.6.4)
