### ISSUE TITLE
[Bug] Database not Supported Error

### ISSUE THREAD

**Issue by crazybob1215** [zurdi15/romm#83]
**Describe the bug**
On a fresh container stood up using a lightly modified version of the provided docker-compose.yml (see below for the docker compose I'm using), I'm seeing an error and RomM isn't able to find the roms I've put in the library directory.

Error from the container logs:
![image](https://user-images.githubusercontent.com/45743617/228728031-df5e0eb1-5ced-43cb-8995-3f36098aa294.png)

Error shown by RomM:
![image](https://user-images.githubusercontent.com/45743617/228728072-50a42a13-db37-47ee-a0c2-02a317177bff.png)

**To Reproduce**
The error in the container logs seems to only show up on boot/reboot of the RomM container, while the error in the RomM webpage shows up anytime I click the "Scan" button.

**Expected behavior**
The roms that I've placed in the library directory should be showing up in the RomM web console (web page?).

**Additional context**
The library directory structure is following the exact requirements shown in the instructions. For example, I have one rom loaded as this: /library/gbc/roms/Pokemon_YellowVersion.gbc

The docker-compose.yml (only passwords and api keys omitted)

> version: '3'
services:
  romm:
    image: 'zurdi15/romm:latest'
    container_name: romm
    environment:
      - ROMM_DB_DRIVER="mariadb"
      - DB_HOST=romm_db
      - DB_PORT=3306
      - DB_USER=romm-user
      - DB_NAME=romm
      - DB_PASSWD=
      - CLIENT_ID=
      - CLIENT_SECRET=
    volumes:
      - '/host/path/to/romm:/library'
    ports:
      - 8080:80
    depends_on:
      - romm_db
    restart: 'unless-stopped'
 romm_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: romm_db
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=
    volumes:
      - ./config:/config
    ports:
      - 3306:3306
    restart: 'unless-stopped'

**Comment by zurdi15** [comment]
Hi, try removing the quotes in the ROMM_DB_DRIVER variable

- ROMM_DB_DRIVER="mariadb" -> - ROMM_DB_DRIVER=mariadb

**Comment by crazybob1215** [comment]
That worked! I'm using Portainer to manage docker containers, so it may have been something with how it handled the quotes.
