### ISSUE TITLE
[Other] Better App Name?

### ISSUE THREAD

**Issue by crispybegs** [zurdi15/romm#88]
I know you can come up with a better name for this than 'ROM Manager'. C'mon man, this is a really great app and you need a better name to go with it :)

Maybe we can brainstorm it in this thread.

**Comment by crispybegs** [comment]
just to get the ball rolling, i thought of some other services.. for example [Kavita](https://www.kavitareader.com/), which means 'poem' in hindi. kind of fitting for a reading app.

straight copying that idea, the word for 'play' or 'game' in Hindi is 'Khel'
In Arabic - 'Lueba'
In Macedonian - 'Igra'
In Italian - 'Gioco'

'Play' in Icelandic is 'Leika'

and so on

**Comment by crispybegs** [comment]
**Rommantic**

<img width="488" alt="Screenshot 2023-03-30 at 22 29 26" src="https://user-images.githubusercontent.com/129169122/228969038-830d3c4d-451d-4364-a250-b86a45f821fb.png">

_someone put me out, i'm on fire_

**Comment by zurdi15** [comment]
I love your enthusiasm my dude, for real. I'll keep the name for now, at least until RomM get te point to be extremely robust and with a lot more features. Maybe in the future I can think in a rebrand with a more significant/beautiful name and logo.

But keep that way, you are helping me a lot to improve RomM

**Comment by crispybegs** [comment]
lol all good, it was a slow evening and i was just spitballing. you do your thing brother!
