### ISSUE TITLE
[Bug] UI freezes up with huge/massive collection

### ISSUE THREAD

**Issue by fatflyingpigs** [zurdi15/romm#89]
**RomM version**
V1.5

**Describe the bug**
When attempting to load a platform with a large number of entries, there is a huge lag.
700 entries: takes 1-5 seconds, loads smoothly
8500 entires: takes 60+ seconds, sometimes Chrome will prompt to terminate the tab. Scrolling down quickly seems to lazy load the image for each game (in this case, 'cover missing' for most of them). 

**To Reproduce**
1. Have two folders, folder 'ds' has 1 file and folder 'gba' 8500 files. Scan the files.
2. After the scan, click on the 'ds' section. Then click on the 'gba' section and wait for the lag.

**Expected behavior**
It would be nice if large collections could be loaded lazily, instead of the page trying to fetch every game at once. Actually, the implementation doesn't really matter - I'd just like the page to load faster, even if the cover images load in later.

**Desktop (please complete the following information):**
Windows 10, Chrome v109.0.5414.75

**Comment by zurdi15** [comment]
I agree with the implementation details. For large collections there should be a lazy scroll load

**Comment by w00tlarr** [comment]
Hey. Hi. I actually love the simplicity of this app. But hmm... do I need to do something for pagination to really paginate? When I reach to the bottom at 60 at listview.. it keeps increasing the from 60 to 120 and the pagination UI went down and keeps going down and down after +60. It's not really a pagination list with left/right arrow to use but more an appended infinite list. I can't also set to filter by X number as it just says All in the dropdown.

**Comment by zurdi15** [comment]
Yes you are right with that is not really a pagination, it's a infinite scroll, with 60 games loaded each time. It's meant to use with the filter by name and was made to avoid load large collections. 

The feature to "jump" directly to X page is not implemented yet, like in a usual data table like this one.
