### ISSUE TITLE
[Bug] Scan is broken after latest update

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#94]
**RomM version**
docker:latest

**Describe the bug**
Scan is broken after the systems update

**To Reproduce**
1. docker compose up -d
2. Click on 'Scan'

**Expected behavior**
Roms are scanned

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS (Linux Debian)
 - Browser Vivaldi, Chrome
 - Version latest on 29/03/2023
 
[romm.log](https://github.com/zurdi15/romm/files/11119263/romm.log)

**Comment by zurdi15** [comment]
In the [v1.5](https://github.com/zurdi15/romm/releases/tag/v1.5) I did some database changes and as RomM doesn't have a CLI or any tool to automate the migrations between versions I suggested to wipe the database.

I am a totally  noob in terms of releasing new software updates in that way, so I don't really know how to handle the database changes facing users. 

You seem to be much more experienced with that, maybe you could give me some tips to improve it?

**Comment by XargonWan** [comment]
> In the [v1.5](https://github.com/zurdi15/romm/releases/tag/v1.5) I did some database changes and as RomM doesn't have a CLI or any tool to automate the migrations between versions I suggested to wipe the database.
> 
> I am a totally noob in terms of releasing new software updates in that way, so I don't really know how to handle the database changes facing users.
> 
> You seem to be much more experienced with that, maybe you could give me some tips to improve that process?
> 
> Edit: Thank you very much for putting that effort triying out RomM btw.

Thanks for your quick reply, where is the sqlite database stored?

About updating a database unfortunately I dont know, yet.
RetroDECK doesn't use a database, RetroMan will do but not in this moment of the develop.

Whenever I will have more info I will tell you.

One tip:
you could check for the version and delete the database if the version is greater, eg:
version 0.1.3 is 13, version 0.2.3 is 23, so 13 < 23, then you can trigger a "post-update" script.

**Comment by zurdi15** [comment]
The sqlite database is stored at root level of your library independently of which structure folder are you using:
 - /path/to/library/**database**

About the tip, It is a really good idea, I'll try to implement it when the (probably) next database change will appear. Thank you very much :)

**Comment by XargonWan** [comment]
So another tip if I can: give the user the option to put the database in a specific place in docker (just add a volume) for example ./config/romm.

Usually as a developer I try to don't edit the user's file until it's possible :)

**Comment by zurdi15** [comment]
Definitely adding that as a part of the config

**Comment by XargonWan** [comment]
So I deleted the database, force recreated romm, it scans, no errors given.
However 0 roms are found, my folder stucture is: `roms/<system>/<rom>.<ext>`, is it supported or I should configure it manually? (you added that function if I'm not mistaken)

**Comment by XargonWan** [comment]
Ok I solved the issue, was pretty simple:

I had `library/systems/files` instead of `library/roms/system/files`.

Moreover: where the scraped files are located?

**Comment by zurdi15** [comment]
That need of having ``/library/roms/platforms`` is because EmuDeck, and as a part of the planned features of managing other emulators files, the folder structure will need ``/library/roms``, ``/library/saves``, etc.

The scraped files are located in ``/library/resources``, but as you sugguested with the database I think it is a better idea to let the user specify where to store the resources aswell as the other managing folders

I am realizing I need to work much more in the structure system and make it much more flexible

**Comment by XargonWan** [comment]
Thanks :)

**Comment by AlexKalopsia** [comment]
Was experiencing the same issue, and I agree that it feels weird to force the user to have a `roms` folder. I think that ideally we should be able to mount separate volumes for roms, config, saves, etc
