### ISSUE TITLE
[Feature] Play games in browser

### ISSUE THREAD

**Issue by Gaming4LifeDE** [zurdi15/romm#95]
I wonder if it would be possible to play games directly in the browser. Could be coupled with [EmulatorJS](https://github.com/EmulatorJS/EmulatorJS).

This would make it awesome for parents with their kids, where they can just add a shortcut to RomM somehwere on their systems and they can just open it, pick a game an play.

**Comment by r4lix** [comment]
would love this, even a shorcut that redirect to a hosted instance of EmulatorJS would be great

**Comment by zurdi15** [comment]
This is not in the near scope, but definetly would be a very good feature

**Comment by webysther** [comment]
@zurdi15 I think the best alternative is using a .env to allow enable a external link or sort of. Then selfhosted of any service can be used. Like the jellyfin provide link to imdb, tmdb and another services, a icon from emulatorjs with the game. To get the game ID I think need to be implemented in future to be automatic as a plugin, but manual link help a lot.

**Comment by webysther** [comment]
@AndrewBudziszek maybe can be expanded to linuxserver.io emulatorjs that use the same name project (but is different one), they use emulatorjs as engine and from libreretro with wasm. They have the same problem, is not possible to open a canonical url to the game in browser.

**Comment by Casuallynoted** [comment]
I believe this issue has also been resolved with the 3.0 update, but I realise there are a select few platforms that are still not fully working (N64 to be fixed in the next update, and CD-based consoles requiring bios support). Figured I'd comment and say this is a thing in 3.0, but not sure if the issue should be closed due to those outstanding things or if those would count as their own issues.

**Comment by zurdi15** [comment]
> I believe this issue has also been resolved with the 3.0 update, but I realise there are a select few platforms that are still not fully working (N64 to be fixed in the next update, and CD-based consoles requiring bios support). Figured I'd comment and say this is a thing in 3.0, but not sure if the issue should be closed due to those outstanding things or if those would count as their own issues.

Yeah I think this can be closed sinde the feature is there, the rest is a matter of upgrading emulatorjs in our side when we can :)
